all:
  - language_interface
  - language_content
  - language_url
configurable:
  - language_interface
  - language_content
negotiation:
  language_content:
    enabled:
      language-url: -20
      language-interface: -15
      language-selected: -14
    method_weights:
      language-url: -20
      language-content-entity: -19
      language-session: -18
      language-user: -17
      language-browser: -16
      language-interface: -15
      language-selected: -14
      language-admin-preference: -4
  language_url:
    enabled:
      language-url: 0
      language-url-fallback: 1
  language_interface:
    enabled:
      language-user-admin: -20
      language-admin-preference: -19
      language-url: -18
      language-selected: -14
    method_weights:
      language-user-admin: -20
      language-admin-preference: -19
      language-url: -18
      language-session: -17
      language-user: -16
      language-browser: -15
      language-selected: -14
