max_links: 10000
cron_generate: true
cron_generate_interval: 24
generate_duration: 10000
entities_per_queue_item: 100
remove_duplicates: true
skip_untranslated: true
xsl: false
base_url: ''
default_variant: default
custom_links_include_images: false
disable_language_hreflang: false
excluded_languages: {  }
enabled_entity_types:
  - node
  - menu_link_content
