display:
  default:
    display_options:
      filters:
        status:
          group_info:
            group_items:
              1:
                title: Published
                operator: '='
                value: '1'
              2:
                title: Unpublished
                operator: '='
                value: '0'
