display:
  default:
    display_title: Förvald
    display_options:
      exposed_form:
        options:
          submit_button: Verkställ
          reset_button_label: Återställ
          exposed_sorts_label: 'Sortera efter'
          sort_asc_label: Stigande
          sort_desc_label: Fallande
      pager:
        options:
          tags:
            next: Nästa
            previous: Föregående
            first: Första
            last: Sista
          expose:
            items_per_page_label: 'Inlägg per sida'
            items_per_page_options_all_label: '- Alla -'
            offset_label: Kompensera
      fields:
        name:
          separator: ', '
      arguments:
        id:
          exception:
            title: Alla
  service_units:
    display_title: Block
