<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraphs_accordion' module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\helfi_paragraphs_accordion\Entity\Accordion;
use Drupal\helfi_paragraphs_accordion\Entity\AccordionItem;
use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_paragraphs_accordion_helfi_paragraph_types() : array {
  return [
    new ParagraphTypeCollection('paragraph', 'accordion_item', 'field_accordion_item_content', 'text', 0),
    new ParagraphTypeCollection('paragraph', 'accordion_item', 'field_accordion_item_content', 'image', 1),
    new ParagraphTypeCollection('paragraph', 'accordion_item', 'field_accordion_item_content', 'phasing', 2),
    new ParagraphTypeCollection('paragraph', 'accordion_item', 'field_accordion_item_content', 'columns', 3),
    new ParagraphTypeCollection('paragraph', 'accordion', 'field_accordion_items', 'accordion_item'),
    new ParagraphTypeCollection('paragraphs_library_item', 'paragraphs_library_item', 'paragraphs', 'accordion'),
  ];
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function helfi_paragraphs_accordion_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['paragraph']['accordion'])) {
    $bundles['paragraph']['accordion']['class'] = Accordion::class;
  }
  if (isset($bundles['paragraph']['accordion_item'])) {
    $bundles['paragraph']['accordion_item']['class'] = AccordionItem::class;
  }
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function helfi_paragraphs_accordion_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle): void {
  if ($entity_type->id() === 'paragraph' && $bundle == 'accordion') {
    // Add constraint to check if accordion has items.
    if (array_key_exists('field_accordion_items', $fields)) {
      $fields['field_accordion_items']->addConstraint('AccordionItems', []);
    }
  }

  if ($entity_type->id() === 'paragraph' && $bundle == 'accordion_item') {
    // Add constraint to check if accordion items has content.
    if (array_key_exists('field_accordion_item_content', $fields)) {
      $fields['field_accordion_item_content']->addConstraint('AccordionItemContent', []);
    }
  }

}
