hdbt_admin_tools.settings:
  type: config_entity
  label: 'HDBT Admin tools settings'
  mapping:
    path_to_json:
      type: string
hdbt_admin_tools.site_settings:
  type: config_object
  label: 'Site settings'
  mapping:
    site_settings:
      label: 'Site settings'
      type: mapping
      mapping:
        default_icon:
          label: 'Default icon'
          type: label
        theme_color:
          label: 'Theme color'
          type: label
        koro:
          label: Koro
          type: label
    footer_settings:
      label: 'Footer settings'
      type: mapping
      mapping:
        footer_color:
          label: 'Footer color'
          type: label
field.widget.settings.link_target_field_widget:
  type: field.widget.settings.linkit
field.widget.settings.link_target_icon_field_widget:
  type: field.widget.settings.linkit
field.widget.settings.design_field_widget:
  type: mapping
  label: 'Design field widget widget settings'
  mapping:
    size:
      type: integer
      label: Size
    placeholder:
      type: textfield
      label: Placeholder
