field.widget.settings.textfield_character_counter:
  type: mapping
  label: 'Character counter textfield widget display format settings'
  mapping:
    counter_step:
      type: integer
      label: 'Counter step'
    counter_total:
      type: integer
      label: 'Counter total'
    size:
      type: integer
      label: 'Size of textfield'
    placeholder:
      type: label
      label: 'Placeholder'
