dependencies:
  config:
    - field.field.paragraph.content_liftup.field_content_liftup_unit
content:
  field_content_liftup_unit:
    weight: 2
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
    type: entity_reference_autocomplete
    region: content
