dependencies:
  config:
    - paragraphs.paragraphs_type.unit_search
settings:
  handler_settings:
    target_bundles:
      unit_search: unit_search
    target_bundles_drag_drop:
      unit_search:
        enabled: '1'
        weight: '30'
