dependencies:
  config:
    - field.field.tpr_service.tpr_service.field_metatags
  module:
    - metatag
content:
  address:
    type: address_plain
  field_metatags:
    weight: 3
    label: above
    settings: {  }
    third_party_settings: {  }
    type: metatag_empty_formatter
    region: content
