dependencies:
  config:
    - paragraphs.paragraphs_type.service_list
    - paragraphs.paragraphs_type.unit_search
  module:
    - entity_reference_revisions
settings:
  handler_settings:
    target_bundles:
      unit_search: unit_search
      service_list: service_list
    target_bundles_drag_drop:
      service_list:
        enabled: true
        weight: 36
      unit_search:
        enabled: true
        weight: 28
