<?php

/**
 * @file
 * Provides module hooks for helfi_user_roles module.
 */

declare(strict_types=1);

/**
 * Implements hook_platform_config_grant_permissions().
 */
function helfi_user_roles_platform_config_grant_permissions() : array {
  return [
    'anonymous' => [
      'access content',
    ],
    'admin' => [
      // @user.
      'access user profiles',
      'administer users',
      'cancel account',
      'change own username',
      'view helfi_multisite_content external entity',
    ],
    'content_producer' => [
      // @user.
      'cancel account',
      'change own username',
      'view helfi_multisite_content external entity',
    ],
    'editor' => [
      // @user.
      'cancel account',
      'change own username',
      'view helfi_multisite_content external entity',
    ],
  ];
}
