field.field.node.landing_page.field_content:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            map: map
          target_bundles_drag_drop:
            map:
              enabled: true
              weight: 31
field.field.node.page.field_content:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            map: map
          target_bundles_drag_drop:
            map:
              enabled: true
              weight: 31
field.field.node.page.field_lower_content:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            map: map
          target_bundles_drag_drop:
            map:
              enabled: true
              weight: 31
user.role.admin:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'create hel_map media'
        - 'delete any hel_map media'
        - 'delete own hel_map media'
        - 'edit any hel_map media'
        - 'edit own hel_map media'
user.role.content_producer:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'create hel_map media'
        - 'delete own hel_map media'
        - 'edit own hel_map media'
