<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraph_hearing' module.
 */

declare(strict_types = 1);

/**
 * Gets the block configurations.
 *
 * Example block:
 *
 * @code
 * [
 *   'breadcrumbs' => [
 *     'block' => [
 *       ...
 *     ],
 *     'variations' => [
 *       ...
 *     ],
 *   ],
 * ];
 * @endcode
 *
 * @return array[]
 *   The block configurations.
 */
function helfi_paragraph_hearing_get_block_configurations(string $theme) : array {
  return [
    'hearing' => [
      'block' => [
        'id' => 'helfihearing',
        'plugin' => 'helfi_paragraph_hearing',
        'settings' => [
          'id' => 'helfi_paragraph_hearing',
          'label' => 'Hearings',
          'provider' => 'helfi_paragraph_hearing',
        ],
        'provider' => 'helfi_paragraph_hearing',
        'weight' => -14,
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'before_content',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function helfi_paragraph_hearing_cron(): void {
}
