field.field.node.page.field_content:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            remote_webform: remote_webform
          target_bundles_drag_drop:
            remote_webform:
              enabled: true
              weight: 38
field.field.node.page.field_lower_content:
  expected_config: { }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            remote_webform: remote_webform
          target_bundles_drag_drop:
            remote_webform:
              enabled: true
              weight: 38
