<?php

/**
 * @file
 * Helper functions related to deleting user accounts.
 *
 * This is in a separate module, so it can be turned off easier,
 * and we can reassign module weights / run order if necessary.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\user\Entity\User;

/**
 * Implements hook_form_alter().
 */
function helfi_users_form_alter(&$form, FormStateInterface $form_state, $form_id): void {
  if (!in_array($form_id, ["user_multiple_cancel_confirm", "user_cancel_form"])) {
    return;
  }

  // Hide email confirmation checkbox.
  $form['user_cancel_confirm']['#access'] = FALSE;
  $form['user_cancel_method']['#description'] = new TranslatableMarkup(
    "Banning accounts prevents them from logging in. If the account is no longer needed, it should be deleted."
  );
}

/**
 * Implements hook_user_cancel_methods_alter().
 */
function helfi_users_user_cancel_methods_alter(array &$methods): void {
  // User can only access allowed methods. User must also have
  // 'administer users' permission from core to be able to cancel users.
  $allowed_methods = [
    'user_cancel_block' => new TranslatableMarkup("Ban the account and keep their content."),
    'user_cancel_block_unpublish' => new TranslatableMarkup("Ban the account and unpublish their content."),
    'user_cancel_reassign' => new TranslatableMarkup("Delete the account and make their content belong to %uid1. This action cannot be undone.", [
      '%uid1' => User::load(1)->getAccountName(),
    ]),
  ];

  foreach ($allowed_methods as $name => $title) {
    $methods[$name]['title'] = $title;
  }

  // Without special permission, user is not allowed to access all methods.
  if (!\Drupal::currentUser()->hasPermission('allow all user cancel methods')) {
    foreach ($methods as $name => &$method) {
      $method['access'] = array_key_exists($name, $allowed_methods);
    }
  }
}
