name: HELfi platform config
type: module
package: Custom
core_version_requirement: ^10 || ^11
dependencies:
  - drupal:language
  - drupal:views
  - helfi_platform_config:helfi_platform_config
  - helfi_api_base:helfi_api_base
  - config_rewrite:config_rewrite
  - menu_block_current_language:menu_block_current_language
'interface translation project': helfi_platform_config
'interface translation server pattern': modules/contrib/helfi_platform_config/translations/new/%language.po
