name: HELfi platform config
type: module
package: Custom
core: 8.x
core_version_requirement: ^8 || ^9
dependencies:
  - 'drupal:language'
  - 'menu_block_current_language:menu_block_current_language'
  - 'helfi_api_base:helfi_api_base'
