matomo_settings_form:
  path: '/admin/tools/matomo-settings'
  defaults:
    _form: '\Drupal\helfi_platform_config\Form\MatomoSettings'
    _title: 'Matomo settings'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE
