name: HELfi platform config
type: module
package: Custom
core: 8.x
core_version_requirement: ^8 || ^9
dependencies:
  - 'drupal:language'
  - 'features:features'
  - 'menu_block_current_language:menu_block_current_language'
  - 'helfi_api_base:helfi_api_base'
'interface translation project': helfi_platform_config
'interface translation server pattern': modules/custom/%project/translations/%language/strings.po
