<?php

/**
 * @file
 * Contains HELfi platform configuration alterations.
 */

use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Language\LanguageInterface;
use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\helfi_api_base\Environment\Project;

/**
 * Helper function to enable paragraph type for given entity/bundle/field combination.
 *
 * @param string $entityType
 *   The entity type.
 * @param string $bundle
 *   The entity bundle.
 * @param string $fields
 *   The field name.
 * @param string $paragraphType
 *   The paragraph type to enable.
 *
 * @throws \InvalidArgumentException
 */
function helfi_platform_config_enable_paragraph_fields(string $entityType, string $bundle, array $fields, string $paragraphType) : void {
  /** @var \Drupal\Core\Entity\EntityFieldManagerInterface $entityFieldManager */
  $entityFieldManager = Drupal::service('entity_field.manager');

  if (!$definitions = $entityFieldManager->getFieldDefinitions($entityType, $bundle)) {
    throw new InvalidArgumentException(
      sprintf('Failed to load field definition for %s, %s', $entityType, $bundle)
    );
  }
  $definitions = array_filter($definitions, function (FieldDefinitionInterface $definition) use ($fields) : bool {
    return in_array($definition->getName(), $fields);
  });

  foreach ($definitions as $field) {
    if (!str_contains($field->getSetting('handler'), 'paragraph')) {
      throw new InvalidArgumentException(
        sprintf('"%s" field is not a valid paragraph reference', $field->getName()),
      );
    }
    $handlerSettings = $field->getSetting('handler_settings');

    if (isset($handlerSettings['target_bundles'])) {
      $handlerSettings['target_bundles'][$paragraphType] = $paragraphType;
      $handlerSettings['target_bundles_drag_drop'][$paragraphType] = [
        'weight' => 30,
        'enabled' => TRUE,
      ];
    }
    $field->setSetting('handler_settings', $handlerSettings);
    $field->save();
  }
}

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function helfi_platform_config_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Replace node title on nodes with the visible title field.
  // @todo Needs work on caches, wrong title is displayed if user visits content listing.
  if ($entity->hasField('field_unit_visible_title')) {
    $entity->set('title', Drupal::token()->replace((string) $entity->get('field_unit_visible_title')->value));
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function helfi_platform_config_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'modules_installed') {
    $moduleHandler = Drupal::service('module_handler');
    if ($moduleHandler->moduleExists('locale')) {
      unset($implementations['locale']);
    }
  }
}

/**
 * Implements hook_modules_installed().
 */
function helfi_platform_config_modules_installed() {
  $moduleHandler = Drupal::service('module_handler');
  if ($moduleHandler->moduleExists('locale')) {
    locale_system_set_config_langcodes();
  }
}

/**
 * Implements hook_page_attachments().
 */
function helfi_platform_config_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'helfi_platform_config/clear_localstorage';
}

/**
 * Implements hook_theme().
 */
function helfi_platform_config_theme() {
  return [
    'react_and_share' => [
      'variables' => [
        'title' => NULL,
        'content' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_token_info().
 */
function helfi_platform_config_token_info() {
  $info['tokens']['site']['page-title-suffix'] = [
    'name' => t('Page title suffix'),
    'description' => t('Official suffix for page title.'),
  ];
  return $info;
}

/**
 * Implements hook_tokens().
 */
function helfi_platform_config_tokens(
  $type,
  $tokens,
  array $data,
  array $options,
  BubbleableMetadata $bubbleable_metadata
) {
  $replacements = [];

  foreach ($tokens as $name => $original) {
    if ($name === 'page-title-suffix') {
      $language = Drupal::languageManager()->getCurrentLanguage();

      switch ($language->getId()) {
        case 'fi':
          $replacements[$original] = 'Helsingin kaupunki';
          break;

        case 'sv':
          $replacements[$original] = 'Helsingfors stad';
          break;

        case 'ru':
          $replacements[$original] = 'Гopoд Xeльcинки';
          break;

        default:
          $replacements[$original] = 'City of Helsinki';
          break;
      }
    }
  }

  return $replacements;
}

/**
 * Implements hook_system_breadcrumb_alter().
 */
function helfi_platform_config_system_breadcrumb_alter(
  Breadcrumb &$breadcrumb,
  RouteMatchInterface $route_match,
  array $context
) {
  // Skip admin routes.
  if ($route_match->getRouteObject()?->getOption('_admin_route')) {
    return;
  }

  /** @var \Drupal\helfi_api_base\Environment\EnvironmentResolver $resolver */
  $resolver = \Drupal::service('helfi_api_base.environment_resolver');
  $activeEnvironment = $resolver->getActiveEnvironment()->getEnvironmentName();
  $environment = $resolver->getEnvironment(Project::ETUSIVU, $activeEnvironment);
  $currentLanguage = Drupal::languageManager()
    ->getCurrentLanguage(LanguageInterface::TYPE_CONTENT)
    ->getId();

  // Revert to English path, if current language path is not found.
  try {
    $url = $environment->getUrl($currentLanguage);
  }
  catch (\Exception $e) {
    $url = $environment->getUrl('en');
  }

  // @todo We need a better way to deal with local docker.so urls.
  $url = str_replace(['http://', ':8080'], ['https://', ''], $url);

  $links = $breadcrumb->getLinks();
  array_unshift($links, Link::fromTextAndUrl(t('Front page'), Url::fromUri($url)));

  // Include front page in breadcrumb if it's the only item.
  if (count($links) === 1 && Drupal::service('path.matcher')->isFrontPage()) {
    $entities = array_filter($route_match->getParameters()->all(), function ($value) {
      return $value instanceof EntityInterface;
    });

    if ($entity = reset($entities)) {
      $links[] = Link::createFromRoute($entity->label(), '<none>');
    }
  }

  // We have to recreate entire breadcrumb trail here, because breadcrumb
  // class forbids setting links after they've been set once.
  // @see \Drupal\Core\Breadcrumb\Breadcrumb::setLinks().
  $newBreadcrumb = new Breadcrumb();
  $newBreadcrumb->setLinks($links);
  // Merge cacheable metadata.
  $newBreadcrumb->addCacheTags($breadcrumb->getCacheTags())
    ->addCacheContexts($breadcrumb->getCacheContexts());

  $breadcrumb = $newBreadcrumb;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function helfi_platform_config_preprocess_react_and_share(&$variables) {
  $variables['privacy_policy_url'] = _helfi_platform_config_eu_cookie_compliance_get_privacy_policy_url();
}

/**
 * Helper function to get the privacy policy link URL.
 */
function _helfi_platform_config_eu_cookie_compliance_get_privacy_policy_url(): Url|string {
  $config = Drupal::config('eu_cookie_compliance.settings');
  $link = $config->get('popup_link');

  return (UrlHelper::isExternal($link))
    ? Url::fromUri($link)
    : Url::fromUserInput($link === '<front>' ? '/' : $link);
}
