<?php

/**
 * @file
 * HELfi platform config hooks.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\helfi_platform_config\TextConverter\Document;

/**
 * Modify the list of paragraphs of first-paragraph-grey.
 *
 * The paragraphs on the list will get the special class
 * has-first-paragraph-gray.
 *
 * @param array $paragraphs
 *   Array of paragraph machine names.
 */
function hook_first_paragraph_grey_alter(array &$paragraphs) {
}

/**
 * Alter markup generated by RenderTextConverter.
 *
 * @param \Drupal\helfi_platform_config\TextConverter\Document $document
 *   The markup rendered using text_converter display.
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The original entity.
 *
 * @see \Drupal\helfi_platform_config\TextConverter\RenderTextConverter::convert()
 */
function hook_text_conversion_alter(Document $document, EntityInterface $entity) : void {
  $document->stripNodes("//*[contains(@class, 'visually-hidden')]");
}

/**
 * Alter markup generated by RenderTextConverter for specific entity types.
 *
 * @param \Drupal\helfi_platform_config\TextConverter\Document $document
 *   The markup rendered using text_converter display.
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The original entity.
 *
 * @see \Drupal\helfi_platform_config\TextConverter\RenderTextConverter::convert()
 */
function hook_entity_type_text_conversion_alter(Document $document, EntityInterface $entity) : void {
  assert($entity->getEntityTypeId(), 'entity_type');
}
