image.style.linkit_result_thumbnail:
  expected_config: {  }
  update_actions:
    add:
      effects:
        2943df29-38ea-459c-ba1d-290489bb1807:
          data:
            anchor: center-center
user.role.anonymous:
  expected_config:
    permissions: {  }
  update_actions:
    change:
      permissions:
        - 'access content'
        - 'view media'
user.role.authenticated:
  expected_config:
    permissions: {  }
  update_actions:
    change:
      permissions:
        - 'access content'
        - 'view media'
