core.entity_view_display.media.remote_video.default:
  expected_config:
    content:
      field_media_oembed_video:
        settings:
          max_height: 0
          max_width: 0
  update_actions:
    change:
      content:
        field_media_oembed_video:
          settings:
            max_height: 714
            max_width: 1264
media.type.remote_video:
  expected_config: {  }
  update_actions:
    add:
      source_configuration:
        providers:
          - 'Icareus Suite'
      third_party_settings:
        crop:
          image_field: null
