views.view.media_library:
  expected_config: {  }
  update_actions:
    add:
      display:
        widget:
          display_options:
            fields:
              edit_media:
                absolute: 0
                admin_label: ''
                alter:
                  absolute: false
                  alt: 'Edit {{ name }}. {{ ''Opens in a new tab''|t }}'
                  alter_text: true
                  ellipsis: true
                  external: false
                  html: false
                  link_class: ''
                  make_link: false
                  max_length: 0
                  more_link: false
                  more_link_path: ''
                  more_link_text: ''
                  nl2br: false
                  path: ''
                  path_case: none
                  prefix: ''
                  preserve_tags: ''
                  rel: ''
                  replace_spaces: false
                  strip_tags: false
                  suffix: ''
                  target: _new
                  text: '<a href="/media/{{ mid }}/edit" class="media-library-item__edit icon-link" title="{% trans %}Edit {{ name }}. Opens in a new tab.{% endtrans %}" target="_new">{% trans %}Edit {{ name }}{% endtrans %}</a>'
                  trim: false
                  trim_whitespace: false
                  word_boundary: true
                element_class: ''
                element_default_classes: false
                element_label_class: ''
                element_label_colon: false
                element_label_type: ''
                element_type: ''
                element_wrapper_class: ''
                element_wrapper_type: '0'
                empty: ''
                empty_zero: false
                entity_type: media
                exclude: false
                field: edit_media
                group_type: group
                hide_alter_empty: true
                hide_empty: false
                id: edit_media
                label: ''
                output_url_as_text: 0
                plugin_id: helfi_media_entity_link_edit
                relationship: none
                table: media
                text: Edit
              mid:
                admin_label: ''
                alter:
                  absolute: false
                  alt: ''
                  alter_text: false
                  ellipsis: true
                  external: false
                  html: false
                  link_class: ''
                  make_link: false
                  max_length: 0
                  more_link: false
                  more_link_path: ''
                  more_link_text: ''
                  nl2br: false
                  path: ''
                  path_case: none
                  prefix: ''
                  preserve_tags: ''
                  rel: ''
                  replace_spaces: false
                  strip_tags: false
                  suffix: ''
                  target: ''
                  text: ''
                  trim: false
                  trim_whitespace: false
                  word_boundary: true
                click_sort_column: value
                delta_first_last: false
                delta_limit: 0
                delta_offset: 0
                delta_reversed: false
                element_class: ''
                element_default_classes: false
                element_label_class: ''
                element_label_colon: false
                element_label_type: ''
                element_type: ''
                element_wrapper_class: ''
                element_wrapper_type: ''
                empty: ''
                empty_zero: false
                entity_field: mid
                entity_type: media
                exclude: true
                field: mid
                field_api_classes: false
                group_column: value
                group_columns: {  }
                group_rows: true
                group_type: group
                hide_alter_empty: true
                hide_empty: false
                id: mid
                label: ''
                multi_type: separator
                plugin_id: field
                relationship: none
                separator: ', '
                settings:
                  prefix_suffix: false
                  thousand_separator: ''
                table: media_field_data
                type: number_integer
              name:
                admin_label: ''
                alter:
                  absolute: false
                  alt: ''
                  alter_text: false
                  ellipsis: true
                  external: false
                  html: false
                  link_class: ''
                  make_link: false
                  max_length: 0
                  more_link: false
                  more_link_path: ''
                  more_link_text: ''
                  nl2br: false
                  path: ''
                  path_case: none
                  prefix: ''
                  preserve_tags: ''
                  rel: ''
                  replace_spaces: false
                  strip_tags: false
                  suffix: ''
                  target: ''
                  text: ''
                  trim: false
                  trim_whitespace: false
                  word_boundary: true
                click_sort_column: value
                delta_first_last: false
                delta_limit: 0
                delta_offset: 0
                delta_reversed: false
                element_class: ''
                element_default_classes: true
                element_label_class: ''
                element_label_colon: false
                element_label_type: ''
                element_type: ''
                element_wrapper_class: ''
                element_wrapper_type: ''
                empty: ''
                empty_zero: false
                entity_field: name
                entity_type: media
                exclude: true
                field: name
                field_api_classes: false
                group_column: value
                group_columns: {  }
                group_rows: true
                group_type: group
                hide_alter_empty: true
                hide_empty: false
                id: name
                label: ''
                multi_type: separator
                plugin_id: field
                relationship: none
                separator: ', '
                settings:
                  link_to_entity: false
                table: media_field_data
                type: string
