core.entity_form_display.media.file.default:
  expected_config: { }
  update_actions:
    change:
      content:
        created:
          weight: 5
        field_media_file:
          weight: 1
        langcode:
          weight: 3
        name:
          weight: 0
        path:
          weight: 7
        replace_file:
          region: content
          settings: {  }
          third_party_settings: {  }
          weight: 2
        status:
          weight: 8
        translation:
          weight: 6
        uid:
          weight: 4
core.entity_form_display.media.image.default:
  expected_config: { }
  update_actions:
    change:
      content:
        created:
          weight: 6
        field_photographer:
          weight: 3
        langcode:
          weight: 4
        path:
          weight: 8
        replace_file:
          region: content
          settings: {  }
          third_party_settings: {  }
          weight: 2
        status:
          weight: 9
        translation:
          weight: 7
        uid:
          weight: 5
core.extension:
  expected_config: { }
  update_actions:
    change:
      module:
        action: 0
        address: 0
        admin_toolbar: 0
        admin_toolbar_tools: 0
        aet: 0
        allowed_formats: 0
        block: 0
        breakpoint: 0
        ckeditor: 0
        config: 0
        config_filter: 0
        config_ignore: 0
        config_rewrite: 0
        config_translation: 0
        config_update: 0
        content_lock: 0
        content_lock_timeout: 0
        content_translation: 10
        crop: 0
        ctools: 0
        datetime: 0
        diff: 0
        dynamic_page_cache: 0
        easy_breadcrumb: 0
        editor: 0
        entity: 0
        entity_reference_revisions: 0
        entity_usage: 0
        eu_cookie_compliance: 1001
        externalauth: 10
        field: 0
        field_group: 0
        field_ui: 0
        file: 0
        filelog: 0
        filter: 0
        flysystem: 0
        flysystem_azure: 0
        focal_point: 0
        gin_toolbar: 0
        hal: 0
        hdbt_admin_editorial: 0
        hdbt_admin_tools: 0
        hdbt_component_library: 0
        hdbt_content: 0
        helfi_announcements: 0
        helfi_announcements_tpr: 0
        helfi_api_base: 0
        helfi_azure_fs: 0
        helfi_base_config: 0
        helfi_charts: 0
        helfi_contact_cards: 0
        helfi_content: 0
        helfi_gdpr_compliance: 0
        helfi_hotjar: 0
        helfi_languages: 0
        helfi_media: 0
        helfi_media_map: 0
        helfi_media_map_config: 0
        helfi_news_item: 0
        helfi_platform_config: 0
        helfi_proxy: 0
        helfi_siteimprove_config: 0
        helfi_toc: 0
        helfi_tpr: 0
        helfi_tpr_config: 0
        helfi_tunnistamo: 0
        image: 0
        image_style_quality: 0
        imagecache_external: 0
        inline_form_errors: 0
        key_value_field: 0
        language: 0
        link: 0
        linkit: 0
        locale: 0
        media: 0
        media_entity_file_replace: 0
        media_entity_soundcloud: 0
        media_library: 0
        menu_block_current_language: 0
        menu_link_attributes: 0
        menu_link_content: 0
        menu_ui: 0
        metatag: 0
        metatag_hreflang: 0
        metatag_open_graph: 0
        metatag_twitter_cards: 0
        metatag_views: 0
        migrate: 0
        minimal: 1000
        node: 0
        oembed_providers: 0
        openid_connect: 0
        options: 0
        page_cache: 0
        paragraphs: 11
        paragraphs_asymmetric_translation_widgets: 0
        paragraphs_library: 0
        path: 0
        path_alias: 0
        pathauto: 1
        publication_date: 99
        purge: 0
        purge_drush: 0
        purge_processor_cron: 0
        purge_queuer_coretags: 0
        purge_tokens: 0
        raven: 0
        rdf: 0
        readonly_field_widget: 0
        redirect: 0
        redis: 0
        responsive_image: 0
        rest: 0
        role_delegation: 0
        scheduler: 0
        select2: 0
        select2_icon: 0
        serialization: 0
        simple_sitemap: 0
        siteimprove: 0
        social_media: 0
        system: 0
        taxonomy: 0
        telephone: 0
        text: 0
        token: 0
        token_filter: 0
        toolbar: 0
        translatable_menu_link_uri: 0
        twig_tweak: 0
        update: 0
        update_helper: 0
        user: 0
        varnish_purge_tags: 0
        varnish_purger: 0
        view_unpublished: 0
        views: 10
        views_bulk_edit: 0
        views_bulk_operations: 0
        views_infinite_scroll: 0
        views_ui: 0
      profile: minimal
      theme:
        claro: 0
        gin: 0
        hdbt: 0
        hdbt_admin: 0
        stable9: 0
