<?php

/**
 * @file
 * Contains hooks for 'helfi_image_styles' module.
 */

declare(strict_types=1);

use Drupal\Component\Utility\UrlHelper;

/**
 * Implements hook_og_image_uri_alter().
 *
 * @see \Drupal\helfi_platform_config\Token\OGImageManager::buildUrl()
 */
function helfi_image_styles_og_image_uri_alter(&$image_uri) : void {
  // Apply image style to internal uris.
  if (!UrlHelper::isExternal($image_uri)) {
    /** @var \Drupal\image\Entity\ImageStyle $image_style */
    $image_style = \Drupal::entityTypeManager()
      ->getStorage('image_style')
      ->load('1.9_1200w_630h');

    $image_uri = $image_style->buildUrl($image_uri);
  }
}
