label: 'Lyhyt otsikko'
description: 'Lyhyt otsikko näytetään uutislistauksissa, nostoissa ja sosiaalisessa mediassa. Kun lyhyt otsikko on syötetty, se yliajaa normaalin otsikkokentän kaikkialla paitsi itse uutisessa.'
