display:
  latest_news:
    display_options:
      title: 'Uusimmat uutiset'
    display_title: 'Uusimmat uutiset'
  default:
    display_options:
      fields:
        view_node:
          text: näkymä
      title: 'Uusimmat uutiset'
      arguments:
        nid:
          exception:
            title: Kaikki
