<?php

/**
 * @file
 * Contains hooks for 'helfi_base_content' module.
 */

declare(strict_types = 1);

use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_base_content_helfi_paragraph_types() : array {
  $types = [
    'paragraphs' => [
      'accordion',
      'banner',
      'columns',
      'content_cards',
      'contact_card_listing',
      'image',
      'text',
      'list_of_links' ,
      'liftup_with_image',
      'sidebar_text',
    ],
  ];

  $enabled = [];
  foreach ($types as $field => $paragraphTypes) {
    foreach ($paragraphTypes as $paragraphType) {
      $enabled[] = new ParagraphTypeCollection('paragraphs_library_item', 'paragraphs_library_item', $field, $paragraphType);
    }
  }
  return $enabled;
}

