<?php

/**
 * @file
 * Contains alterations for the Hel.fi base content.
 */

declare(strict_types=1);

use Drupal\config_rewrite\ConfigRewriterInterface;

/**
 * Implements hook_platform_config_grant_permissions().
 */
function helfi_base_content_platform_config_grant_permissions() : array {
  return [
    'anonymous' => [
      'access content',
      // @helfi_api_base
      'view remote entities',
      'access debug api',
      // @raven
      'send javascript errors to sentry',
    ],
    'authenticated' => [
      'access content',
      'view unpublished paragraphs',
      // @helfi_api_base.
      'view remote entities',
      // @raven
      'send javascript errors to sentry',
    ],
    'admin' => [
      // @block.
      'administer blocks',
      // @content_translation.
      'create content translations',
      'delete content translations',
      'translate any entity',
      'translate editable entities',
      'update content translations',
      // @config_translation.
      'translate configuration',
      // @content_lock.
      'break content lock',
      // @menu_link_attributes.
      'use menu link attributes',
      // @menu_link_content.
      'translate menu_link_content',
      // @node.
      'access content overview',
      'administer nodes',
      'delete all revisions',
      'revert all revisions',
      'view all revisions',
      'view own unpublished content',
      // @helfi_api_base.
      'access remote entities overview',
      'create remote entities',
      'delete remote entities',
      'edit remote entities',
      // @view_unpublished.
      'view any unpublished content',
      // @paragraphs.
      'administer paragraphs library',
      'create paragraph library item',
      'edit paragraph library item',
      'view unpublished paragraphs',
      // @path / path_alias.
      'create url aliases',
      'administer url aliases',
      // @pathauto.
      'administer pathauto',
      // @redirect.
      'administer redirects',
      // @role_delegation.
      'assign content_producer role',
      'assign editor role',
      'assign read_only role',
      // @scheduler.
      'schedule publishing of nodes',
      'view scheduled content',
      // @simple_sitemap.
      'administer sitemap settings',
      // @system.
      'administer menu',
      'access administration pages',
      'access site in maintenance mode',
      'view the administration theme',
      // @taxonomy.
      'access taxonomy overview',
      // @entity_usage
      'access entity usage statistics',
    ],
    'content_producer' => [
      // @content_translation.
      'translate editable entities',
      // @helfi_api_base.
      'access remote entities overview',
      // @menu_link_content.
      'translate menu_link_content',
      // @node.
      'access content overview',
      'administer nodes',
      'view all revisions',
      'view own unpublished content',
      // @paragraphs.
      'administer paragraphs library',
      'create paragraph library item',
      'edit paragraph library item',
      'view unpublished paragraphs',
      // @path / path_alias.
      'create url aliases',
      // @scheduler.
      'schedule publishing of nodes',
      'view scheduled content',
      // @system.
      'view the administration theme',
      // @taxonomy.
      'access taxonomy overview',
      // @view_unpublished.
      'view any unpublished content',
      // @entity_usage
      'access entity usage statistics',
    ],
    'editor' => [
      // @content_translation.
      'create content translations',
      'delete content translations',
      'translate any entity',
      'translate editable entities',
      'update content translations',
      // @node.
      'access content overview',
      'administer nodes',
      'view all revisions',
      'view own unpublished content',
      // @helfi_api_base.
      'access remote entities overview',
      'create remote entities',
      'delete remote entities',
      'edit remote entities',
      // @menu_link_attributes.
      'use menu link attributes',
      // @menu_link_content.
      'translate menu_link_content',
      // @paragraphs.
      'administer paragraphs library',
      'create paragraph library item',
      'edit paragraph library item',
      'view unpublished paragraphs',
      // @path / path_alias.
      'create url aliases',
      'administer url aliases',
      // @redirect.
      'administer redirects',
      // @scheduler.
      'schedule publishing of nodes',
      'view scheduled content',
      // @system.
      'administer menu',
      'access administration pages',
      'view the administration theme',
      // @taxonomy.
      'access taxonomy overview',
      // @view_unpublished.
      'view any unpublished content',
      // @entity_usage
      'access entity usage statistics',
    ],
    'read_only' => [
      // @node.
      'view own unpublished content',
      // @paragraphs.
      'view unpublished paragraphs',
    ],
  ];
}

/**
 * Implements hook_themes_installed().
 */
function helfi_base_content_themes_installed($theme_list) {

  /** @var Drupal\helfi_platform_config\Helper\BlockInstaller $block_installer */
  $block_installer = Drupal::service('helfi_platform_config.helper.block_installer');

  foreach ($theme_list as $theme) {
    if (in_array($theme, ['stark', 'hdbt', 'hdbt_subtheme'])) {
      // Set the current theme as default theme.
      Drupal::configFactory()->getEditable('system.theme')
        ->set('default', $theme)
        ->save();

      foreach (helfi_base_content_get_block_configurations($theme) as $block_config) {
        ['block' => $block, 'variations' => $variations] = $block_config;
        $block_installer->install($block, $variations);
      }
    }
  }
}

/**
 * Gets the block configurations.
 *
 * Example block:
 *
 * @code
 * [
 *   'breadbrumbs' => [
 *     'block' => [
 *       ...
 *     ],
 *     'variations' => [
 *       ...
 *     ],
 *   ],
 * ];
 * @endcode
 *
 * @return array[]
 *   The block configurations.
 */
function helfi_base_content_get_block_configurations(string $theme) : array {
  return [
    'breadcrumbs' => [
      'block' => [
        'id' => 'breadcrumbs',
        'plugin' => 'system_breadcrumb_block',
        'provider' => 'helfi_base_content',
        'settings' => [
          'id' => 'system_breadcrumb_block',
          'label' => 'Breadcrumbs',
          'provider' => 'system',
        ],
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'breadcrumb',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
    'hero_block' => [
      'block' => [
        'id' => 'heroblock',
        'plugin' => 'hero_block',
        'provider' => 'helfi_base_content',
        'settings' => [
          'id' => 'hero_block',
          'label' => 'Hero block',
          'provider' => 'helfi_platform_config',
        ],
        'weight' => -11,
        'visibility' => [
          'entity_bundle:node' => [
            'id' => 'entity_bundle:node',
            'negate' => FALSE,
            'context_mapping' => [
              'node' => '@node.node_route_context:node',
            ],
            'bundles' => [
              'landing_page' => 'landing_page',
              'page' => 'page',
            ],
          ],
        ],
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'before_content',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
    'mainnavigation' => [
      'block' => [
        'id' => 'mainnavigation',
        'plugin' => 'menu_block_current_language:main',
        'provider' => 'helfi_base_content',
        'settings' => [
          'id' => 'menu_block_current_language:main',
          'label' => 'Main navigation',
          'level' => 1,
          'expand_all_items' => TRUE,
          'depth' => 2,
          'provider' => 'menu_block_current_language',
          'translation_providers' => [
            'views' => 'views',
            'menu_link_content' => 'menu_link_content',
            'default' => '0',
          ],
        ],
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'header_bottom',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
    'main_navigation_level_2' => [
      'block' => [
        'id' => 'main_navigation_level_2',
        'plugin' => 'menu_block_current_language:main',
        'provider' => 'helfi_base_content',
        'settings' => [
          'id' => 'menu_block_current_language:main',
          'label' => 'Main navigation (Level 2 ->)',
          'level' => 2,
          'expand_all_items' => TRUE,
          'depth' => 0,
          'provider' => 'menu_block_current_language',
          'translation_providers' => [
            'views' => 'views',
            'menu_link_content' => 'menu_link_content',
            'default' => '0',
          ],
        ],
        'visibility' => [],
        'weight' => -12,
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'sidebar_first',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
    'mobile_navigation' => [
      'block' => [
        'id' => 'mobile_navigation',
        'plugin' => 'menu_block_current_language:main',
        'provider' => 'helfi_base_content',
        'settings' => [
          'id' => 'menu_block_current_language:main',
          'label' => 'Mobile navigation',
          'level' => 1,
          'expand_all_items' => TRUE,
          'depth' => 0,
          'provider' => 'menu_block_current_language',
          'translation_providers' => [
            'views' => 'views',
            'menu_link_content' => 'menu_link_content',
            'default' => '0',
          ],
        ],
        'weight' => 4,
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'header_branding',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
    'footerbottomnavigation' => [
      'block' => [
        'id' => 'footerbottomnavigation',
        'plugin' => 'menu_block_current_language:footer-bottom-navigation',
        'provider' => 'helfi_base_content',
        'settings' => [
          'id' => 'menu_block_current_language:footer-bottom-navigation',
          'label' => 'Footer - Bottom navigation',
          'level' => 1,
          'expand_all_items' => FALSE,
          'depth' => 1,
          'provider' => 'menu_block_current_language',
        ],
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'footer_bottom',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
    'footertopnavigation' => [
      'block' => [
        'id' => 'footertopnavigation',
        'plugin' => 'menu_block_current_language:footer-top-navigation',
        'provider' => 'helfi_base_content',
        'settings' => [
          'id' => 'menu_block_current_language:footer-top-navigation',
          'label' => 'City of Helsinki',
          'label_display' => TRUE,
          'level' => 1,
          'expand_all_items' => FALSE,
          'depth' => 1,
          'provider' => 'menu_block_current_language',
          'translation_providers' => [
            'views' => 'views',
            'menu_link_content' => 'menu_link_content',
            'default' => '0',
          ],
        ],
        'weight' => -4,
        'translations' => [
          'fi' => 'Helsingin kaupunki',
          'sv' => 'Helsingfors stad',
        ],
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'footer_top',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
    'footertopnavigationsecond' => [
      'block' => [
        'id' => 'footertopnavigationsecond',
        'plugin' => 'menu_block_current_language:footer-top-navigation-2',
        'provider' => 'helfi_base_content',
        'settings' => [
          'id' => 'menu_block_current_language:footer-top-navigation-2',
          'label' => 'Connect',
          'label_display' => TRUE,
          'level' => 1,
          'expand_all_items' => FALSE,
          'depth' => 1,
          'provider' => 'menu_block_current_language',
          'translation_providers' => [
            'views' => 'views',
            'menu_link_content' => 'menu_link_content',
            'default' => '0',
          ],
        ],
        'weight' => 2,
        'translations' => [
          'fi' => 'Ota yhteyttä',
          'sv' => 'Ta kontakt',
        ],
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'footer_top',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
    'headertopnavigation' => [
      'block' => [
        'id' => 'headertopnavigation',
        'plugin' => 'menu_block_current_language:header-top-navigation',
        'provider' => 'helfi_base_content',
        'settings' => [
          'id' => 'menu_block_current_language:header-top-navigation',
          'label' => 'Header - Top navigation',
          'level' => 1,
          'expand_all_items' => FALSE,
          'depth' => 1,
          'provider' => 'menu_block_current_language',
          'translation_providers' => [
            'views' => 'views',
            'menu_link_content' => 'menu_link_content',
            'default' => '0',
          ],
        ],
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'header_top',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
    'language_switcher' => [
      'block' => [
        'id' => 'language_switcher',
        'plugin' => 'language_block:language_content',
        'provider' => 'helfi_base_content',
        'settings' => [
          'id' => 'language_block:language_content',
          'label' => 'Language switcher',
          'provider' => 'language',
        ],
        'weight' => 2,
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'header_branding',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
    'page_title' => [
      'block' => [
        'id' => 'page_title',
        'plugin' => 'page_title_block',
        'provider' => 'helfi_base_content',
        'weight' => -12,
        'settings' => [
          'id' => 'page_title_block',
          'label' => 'Page title',
          'provider' => 'core',
        ],
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'content',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
    'lowercontentblock' => [
      'block' => [
        'id' => 'lowercontentblock',
        'plugin' => 'lower_content_block',
        'provider' => 'helfi_base_content',
        'weight' => -9,
        'settings' => [
          'id' => 'lower_content_block',
          'label' => 'Lower content block',
          'provider' => 'helfi_platform_config',
        ],
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'after_content',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
    'sidebarcontentblock' => [
      'block' => [
        'id' => 'sidebarcontentblock',
        'plugin' => 'sidebar_content_block',
        'provider' => 'helfi_base_content',
        'weight' => -9,
        'settings' => [
          'id' => 'sidebar_content_block',
          'label' => 'Sidebar content block',
          'provider' => 'helfi_platform_config',
        ],
        'visibility' => [
          'entity_bundle:node' => [
            'id' => 'entity_bundle:node',
            'negate' => TRUE,
            'context_mapping' => [
              'node' => '@node.node_route_context:node',
            ],
            'bundles' => [
              'landing_page' => 'landing_page',
            ],
          ],
        ],
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'sidebar_second',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
    'sitebranding' => [
      'block' => [
        'id' => 'sitebranding',
        'plugin' => 'system_branding_block',
        'provider' => 'helfi_base_content',
        'weight' => 1,
        'settings' => [
          'id' => 'system_branding_block',
          'label' => 'Site branding',
          'provider' => 'system',
          'use_site_logo' => TRUE,
          'use_site_name' => TRUE,
          'use_site_slogan' => FALSE,
        ],
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'header_branding',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_rewrite_config_update().
 */
function helfi_base_content_config_rewrite_config_update(string $module, ConfigRewriterInterface $configRewriter): void {
  // Rewrite module configuration.
  if ($module === 'helfi_base_content') {
    $configRewriter->rewriteModuleConfig('helfi_base_content');
  }
}
