<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\entity\BundleFieldDefinition;

function helfi_announcements_form_node_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'node_announcement_edit_form':
    case 'node_announcement_form':
      $form['field_announcement_content_pages']['#states'] = [
        'visible' => [
          ':input[name="field_announcement_all_pages[value]"]' => ['checked' => FALSE],
        ],
      ];
      break;
  }
}
