helfi_calculator.calculator_settings:
  type: config_object
  label: 'Calculator settings'
  mapping:
    house_cleaning_service_voucher:
      label: 'House cleaning service voucher'
      type: mapping
      mapping:
        active:
          label: 'Is active'
          type: boolean
        json:
          label: 'Json'
          type: text
    home_care_service_voucher:
      label: 'Home care service voucher'
      type: mapping
      mapping:
        active:
          label: 'Is active'
          type: boolean
        json:
          label: 'Json'
          type: text
    home_care_client_payment:
      label: 'Home care client payment'
      type: mapping
      mapping:
        active:
          label: 'Is active'
          type: boolean
        json:
          label: 'Json'
          type: text
