description: 'Etsi ja ylläpidä mediatiedostoja.'
display:
  default:
    display_title: Oletus
    display_options:
      exposed_form:
        options:
          submit_button: Suodatin
          reset_button_label: Palauta
          exposed_sorts_label: Lajittele
          sort_asc_label: Nousevasti
          sort_desc_label: Laskevasti
      pager:
        options:
          expose:
            items_per_page_label: 'Merkintöjä sivua kohti'
            items_per_page_options_all_label: '- Kaikki -'
            offset_label: Offset
          tags:
            previous: '‹ Edellinen'
            next: 'Seuraava ›'
            first: '« Ensimmäinen'
            last: 'Viimeinen »'
      fields:
        media_bulk_form:
          action_title: Toiminto
        thumbnail__target_id:
          label: Pienoiskuva
          separator: ', '
        name:
          label: 'Mediatiedoston nimi'
          separator: ', '
        bundle:
          label: Tyyppi
          separator: ', '
        uid:
          label: Kirjoittaja
          separator: ', '
        status:
          label: Tila
          settings:
            format_custom_true: Julkaistu
            format_custom_false: Julkaisematon
          separator: ', '
        changed:
          label: Päivitetty
          separator: ', '
        operations:
          label: Toimenpiteet
      filters:
        name:
          expose:
            label: 'Mediatiedoston nimi'
        bundle:
          expose:
            label: Tyyppi
        status:
          expose:
            label: Tosi
          group_info:
            label: Julkaisutila
            group_items:
              1:
                title: Julkaistu
              2:
                title: Julkaisematon
        langcode:
          expose:
            label: Kieli
      title: Media
      empty:
        area_text_custom:
          content: 'Ei mediatiedostoja saatavilla.'
  media_page_list:
    display_title: Media
    display_options:
      menu:
        title: Media
