name: 'HELfi TPR configuration'
type: module
core_version_requirement: '^8.9 || ^9'
package: HELfi
dependencies:
  - 'drupal:field'
  - 'drupal:link'
  - 'drupal:media_library'
  - 'drupal:path'
  - 'drupal:telephone'
  - 'drupal:text'
  - 'drupal:user'
  - 'drupal:views'
  - 'field_group:field_group'
  - 'helfi_content:helfi_content'
  - 'helfi_tpr:helfi_tpr'
  - 'hdbt_admin_editorial:hdbt_admin_editorial'
  - 'imagecache_external:imagecache_external'
  - 'metatag:metatag'
  - 'paragraphs:paragraphs'
  - 'readonly_field_widget:readonly_field_widget'
  - 'select2:select2'
  - 'update_helper:update_helper'
  - 'views_infinite_scroll:views_infinite_scroll'
'interface translation project': helfi_tpr_config
'interface translation server pattern': modules/contrib/helfi_platform_config/helfi_features/helfi_tpr_config/translations/%language.po
