<?php

/**
 * @file
 * Primary module hooks for helfi_media_chart module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\Entity\BaseFieldOverride;
use Drupal\Core\Form\FormStateInterface;
use Drupal\helfi_media_chart\Entity\HelfiChart;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function helfi_media_chart_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['media']['helfi_chart'])) {
    $bundles['media']['helfi_chart']['class'] = HelfiChart::class;
  }
}

/**
 * Implements hook_platform_config_grant_permissions().
 */
function helfi_media_chart_platform_config_grant_permissions() : array {
  return [
    'admin' => [
      'create helfi_chart media',
      'delete any helfi_chart media',
      'delete own helfi_chart media',
      'edit any helfi_chart media',
      'edit own helfi_chart media',
    ],
    'content_producer' => [
      'create helfi_chart media',
      'delete own helfi_chart media',
      'edit any helfi_chart media',
      'edit own helfi_chart media',
    ],
    'editor' => [
      'create helfi_chart media',
      'delete any helfi_chart media',
      'delete own helfi_chart media',
      'edit any helfi_chart media',
      'edit own helfi_chart media',
    ],
  ];
}

/**
 * Implements hook_field_widget_single_element_link_default_form_alter().
 *
 * @param array<string, mixed> $element
 *   The widget form element.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 * @param array<string, mixed> $context
 *   The widget context.
 */
function helfi_media_chart_field_widget_single_element_link_default_form_alter(array &$element, FormStateInterface $form_state, array $context) : void {
  $field_definition = $context['items']->getFieldDefinition();

  if (
    $field_definition->getName() === 'field_helfi_chart_url' &&
    $field_definition->getTargetBundle() === 'helfi_chart'
  ) {
    // Core wraps the user-entered field description together with its own
    // "This must be an external URL..." text in an item list. We want to keep
    // only the first item in the list since that one is added by us.
    if (isset($element['uri']['#description']['#items'][0])) {
      $element['uri']['#description'] = $element['uri']['#description']['#items'][0];
    }
  }
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function helfi_media_chart_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) : void {
  if (
    $entity_type->id() === 'media' &&
    $bundle === 'helfi_chart' &&
    isset($fields['field_helfi_chart_url'])
  ) {
    $fields['field_helfi_chart_url']->addConstraint('ValidHelfiChartLink', []);
  }
}

/**
 * Implements hook_entity_bundle_field_info().
 */
function helfi_media_chart_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions) : array {
  $fields = [];

  // Switch Helfi Chart media type 'name' label to "Administrative title".
  if (
    $entity_type->id() == 'media' &&
    $bundle == 'helfi_chart' &&
    !empty($base_field_definitions['name'])
  ) {
    $field = BaseFieldOverride::createFromBaseFieldDefinition($base_field_definitions['name'], $bundle);
    $field->setLabel(t('Administrative title'));
    // @phpstan-ignore-next-line Drupal accepts TranslatableMarkup.
    $field->setDescription(t('This is only visible in the content creator view. The title is created automatically, but you can edit it if you wish.'));
    $fields['name'] = $field;
  }

  return $fields;
}

/**
 * Implements hook_theme().
 */
function helfi_media_chart_theme($existing, $type, $theme, $path) : array {
  return [
    'chart_iframe' => [
      'variables' => [
        'title' => NULL,
        'url' => NULL,
        'domain' => NULL,
      ],
      'template' => 'chart-iframe',
    ],
    'chart_iframe__media_library' => [
      'variables' => [
        'title' => NULL,
        'url' => NULL,
      ],
      'template' => 'chart-iframe--media-library',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function helfi_media_chart_preprocess_chart_iframe(&$variables): void {
  $variables['chart_service_url'] = $variables['domain'];

  if (Drupal::moduleHandler()->moduleExists('hdbt_cookie_banner')) {
    /** @var \Drupal\hdbt_cookie_banner\Services\CookieSettings $cookie_settings */
    $cookie_settings = \Drupal::service('hdbt_cookie_banner.cookie_settings');
    $variables['privacy_policy_url'] = $cookie_settings->getCookieSettingsPageUrl();
  }
}
