<?php

/**
 * @file
 * Contains hooks for 'helfi_global_announcement' module.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\entity\BundleFieldDefinition;

/**
 * Gets the block configurations.
 *
 * Example block:
 *
 * @code
 * [
 *   'breadbrumbs' => [
 *     'block' => [
 *       ...
 *     ],
 *     'variations' => [
 *       ...
 *     ],
 *   ],
 * ];
 * @endcode
 *
 * @return array[]
 *   The block configurations.
 */
function helfi_global_announcement_get_block_configurations(string $theme) : array {
  return [
    'global_announcement' => [
      'block' => [
        'id' => 'globalannouncement',
        'plugin' => 'global_announcements',
        'settings' => [
          'id' => 'global_announcements',
          'label' => 'Global announcement',
          'provider' => 'helfi_global_announcement',
        ],
        'provider' => 'helfi_global_announcement',
        'weight' => -14,
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'before_content',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function helfi_global_announcement_entity_bundle_field_info_alter(
  &$fields,
  EntityTypeInterface $entity_type
) : void {
  if ($entity_type->id() === 'helfi_announcements') {

    // Additional entity info fields.
    $entity_info_fields = [
      'published_at' => new TranslatableMarkup('Published at'),
      'unpublish_on' => new TranslatableMarkup('Unpublish on'),
      'notification' => new TranslatableMarkup('Notification'),
      'langcode' => new TranslatableMarkup('Langcode'),
      'body' => new TranslatableMarkup('Body'),
      'status' => new TranslatableMarkup('Status'),
      'announcement_type' => new TranslatableMarkup('Announcement type'),
      'announcement_link_text' => new TranslatableMarkup('Announcement link text'),
      'announcement_link_url' => new TranslatableMarkup('Announcement link url'),
    ];

    foreach ($entity_info_fields as $field_name => $field_label) {
      $fields[$field_name] = BundleFieldDefinition::create('string')
        ->setName($field_name)
        ->setLabel($field_label)
        ->setDisplayConfigurable('view', TRUE)
        ->setDisplayConfigurable('form', TRUE);
    }
  }
}
