entity_type_groups:
  tpr_service:
    tpr_service:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
  tpr_unit:
    tpr_unit:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
  node:
    landing_page:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
    page:
      basic: basic
      open_graph: open_graph
      twitter_cards: twitter_cards
