name: 'HELfi TPR configuration'
type: module
core_version_requirement: '^8.9 || ^9'
package: HELfi
dependencies:
  - 'address:address'
  - 'drupal:field'
  - 'drupal:link'
  - 'drupal:media_library'
  - 'drupal:path'
  - 'drupal:telephone'
  - 'drupal:text'
  - 'drupal:user'
  - 'drupal:views'
  - 'field_group:field_group'
  - 'helfi_content:helfi_content'
  - 'helfi_tpr:helfi_tpr'
  - 'imagecache_external:imagecache_external'
  - 'metatag:metatag'
  - 'paragraphs:paragraphs'
  - 'readonly_field_widget:readonly_field_widget'
  - 'select2:select2'
  - 'views_infinite_scroll:views_infinite_scroll'
