<?php

/**
 * @file
 * Contains module hooks for 'helfi_platform_config_base'.
 */

declare(strict_types=1);

/**
 * Implements hook_platform_config_grant_permissions().
 */
function helfi_platform_config_base_platform_config_grant_permissions() : array {
  return [
    'admin' => [
      'access toolbar',
    ],
    'content_producer' => [
      'access toolbar',
    ],
    'editor' => [
      'access toolbar',
    ],
    'read_only' => [
      'access toolbar',
    ],
  ];
}
