field.field.node.landing_page.field_content:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            chart: chart
          target_bundles_drag_drop:
            chart:
              enabled: true
              weight: 25
field.field.node.page.field_content:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            chart: chart
          target_bundles_drag_drop:
            chart:
              enabled: true
              weight: 25
field.field.node.page.field_lower_content:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            chart: chart
          target_bundles_drag_drop:
            chart:
              enabled: true
              weight: 25
