popup_agree_button_message: Accepterar
popup_more_info_button_message: 'Visa cookies'
popup_find_more_button_message: 'Visa cookies'
popup_hide_button_message: Dölj
popup_info:
  value: "<h2>Hel.fi använder cookies</h2><p>Vi använder viktiga cookies på vår webbplats för att få webbplatsen att fungera. Även tredjepartscookies används om du ger oss ditt tillstånd.</p>\r\n"
disagree_button_label: 'Nej, tack'
withdraw_action_button_label: 'Återkalla samtycke'
withdraw_tab_button_label: Sekretessinställningar
save_preferences_button_label: 'Acceptera valda cookies'
accept_all_categories_button_label: 'Acceptera alla cookies'
