<?php

/**
 * Implements hook_form_alter().
 */
function helfi_gdpr_compliance_form_eu_cookie_compliance_block_form_alter(&$form, &$form_state, $form_id) {
  unset($form['#markup']);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function helfi_gdpr_compliance_preprocess_form_element(&$variables) {
$a = 1;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function helfi_gdpr_compliance_theme_suggestions_form_element(array $variables) {
  $suggestions = [];
  $node = $variables['elements']['#node'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'node__' . $sanitized_view_mode;
  $suggestions[] = 'node__' . $node->bundle();
  $suggestions[] = 'node__' . $node->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'node__' . $node->id();
  $suggestions[] = 'node__' . $node->id() . '__' . $sanitized_view_mode;

  return $suggestions;
}
