<?php

/**
 * @file
 * Contains 'helfi_ckeditor' hooks.
 */

declare(strict_types=1);

use Drupal\ckeditor5\Plugin\CKEditor5PluginDefinition;
use Drupal\Core\Language\LanguageInterface;

/**
 * Modify the list of available CKEditor 5 plugins.
 *
 * @param array $plugin_definitions
 *   An array of all the existing plugin definitions, passed by reference.
 *
 * @see \Drupal\ckeditor5\Plugin\CKEditor5PluginManager
 */
function helfi_ckeditor_ckeditor5_plugin_info_alter(array &$plugin_definitions): void {
  /** @var Drupal\ckeditor5\Plugin\CKEditor5PluginDefinition $table_plugin_definition */
  $table_plugin_definition = $plugin_definitions['ckeditor5_table'];
  $original_table_plugin = $table_plugin_definition->toArray();

  // Unset the 'table.PlainTableOutput' CKEditor5 plugin as we want to preserve
  // the <figure class="table"> > <figcaption> functionality.
  if (($plugin = array_search('table.PlainTableOutput', $original_table_plugin['ckeditor5']['plugins'])) !== FALSE) {
    unset($original_table_plugin['ckeditor5']['plugins'][$plugin]);
  }

  // Save ckeditor5_table plugin definitions.
  $plugin_definitions['ckeditor5_table'] = new CKEditor5PluginDefinition($original_table_plugin);
}

/**
 * Implements hook_js_settings_alter().
 */
function helfi_ckeditor_js_settings_alter(array &$settings) {
  // UI language is used to decide the content direction on editor.
  // Overwrite the UI langcode to show correct direction.
  // Turn editor header around to make it render correctly.
  $language_manager = \Drupal::languageManager();
  $content_language = $language_manager
    ->getCurrentLanguage(LanguageInterface::TYPE_CONTENT);
  
  $ui_language_direction = $language_manager
    ->getCurrentLanguage(LanguageInterface::TYPE_INTERFACE)
    ->getDirection();

  $language_id = $content_language->getId();
  if (isset($settings['editor']['formats']['full_html'])) {
    $settings['editor']['formats']['full_html']['editorSettings']['language']['ui'] = $language_id;
    if ($ui_language_direction === 'ltr') {
      $reversed = array_reverse($settings['editor']['formats']['full_html']['editorSettings']['toolbar']['items']);
      $settings['editor']['formats']['full_html']['editorSettings']['toolbar']['items'] = $reversed;
    }
  }
  if (isset($settings['editor']['formats']['simple_html'])) {
    $settings['editor']['formats']['simple_html']['editorSettings']['language']['ui'] = $language_id;
    if ($ui_language_direction === 'ltr') {
      $reversed = array_reverse($settings['editor']['formats']['simple_html']['editorSettings']['toolbar']['items']);
      $settings['editor']['formats']['simple_html']['editorSettings']['toolbar']['items'] = $reversed;
    }
  }
  if (isset($settings['editor']['formats']['minimal'])) {
    $settings['editor']['formats']['minimal']['editorSettings']['language']['ui'] = $language_id;
    if ($ui_language_direction === 'ltr') {
      $reversed = array_reverse($settings['editor']['formats']['minimal']['editorSettings']['toolbar']['items']);
      $settings['editor']['formats']['minimal']['editorSettings']['toolbar']['items'] = $reversed;
    }
  }
}
