<?php

/**
 * @file
 * Contains 'helfi_ckeditor' hooks.
 */

declare(strict_types=1);

use Drupal\Core\Language\LanguageInterface;
use Drupal\ckeditor5\Plugin\CKEditor5PluginDefinition;

/**
 * Implements hook_platform_config_grant_permissions().
 */
function helfi_ckeditor_platform_config_grant_permissions() : array {
  return [
    'admin' => [
      'use text format full_html',
      'use text format minimal',
    ],
    'content_producer' => [
      'use text format full_html',
      'use text format minimal',
    ],
    'editor' => [
      'use text format full_html',
      'use text format minimal',
    ],
  ];
}

/**
 * Modify the list of available CKEditor 5 plugins.
 *
 * @param array $plugin_definitions
 *   An array of all the existing plugin definitions, passed by reference.
 *
 * @see \Drupal\ckeditor5\Plugin\CKEditor5PluginManager
 */
function helfi_ckeditor_ckeditor5_plugin_info_alter(array &$plugin_definitions): void {
  /** @var Drupal\ckeditor5\Plugin\CKEditor5PluginDefinition $table_plugin_definition */
  $table_plugin_definition = $plugin_definitions['ckeditor5_table'];
  $original_table_plugin = $table_plugin_definition->toArray();

  // Unset the 'table.PlainTableOutput' CKEditor5 plugin as we want to preserve
  // the <figure class="table"> > <figcaption> functionality.
  if (($plugin = array_search('table.PlainTableOutput', $original_table_plugin['ckeditor5']['plugins'])) !== FALSE) {
    unset($original_table_plugin['ckeditor5']['plugins'][$plugin]);
  }

  // Save ckeditor5_table plugin definitions.
  $plugin_definitions['ckeditor5_table'] = new CKEditor5PluginDefinition($original_table_plugin);
}

/**
 * Implements hook_editor_js_settings_alter().
 */
function helfi_ckeditor_editor_js_settings_alter(array &$settings): void {
  if (
    !isset($settings['editor']['formats']) ||
    !is_array($settings['editor']['formats'])
  ) {
    return;
  }

  $language = \Drupal::languageManager()
    ->getCurrentLanguage(LanguageInterface::TYPE_CONTENT);

  // Set the CKEditor content language according to the page content language.
  foreach ($settings['editor']['formats'] as &$format) {
    $format['editorSettings']['language']['content'] = $language->getId();
  }
}
