<?php

/**
 * @file
 * Contains hooks for 'helfi_node_announcement' module.
 */

declare(strict_types=1);

/**
 * Implements hook_form_FORM_ID_alter().
 */
function helfi_node_announcement_form_node_form_alter(&$form, &$form_state, $form_id) : void {
  switch ($form_id) {
    case 'node_announcement_edit_form':
    case 'node_announcement_form':
      // Don't show "menu link translation" published checkbox, as
      // announcements cannot be added to any menu.
      if (isset($form['menu']['content_translation_status'])) {
        $form['menu']['content_translation_status']['#access'] = FALSE;
      }

      $contentPageStates = [
        'visible' => [
          ':input[name="field_announcement_all_pages[value]"]' => ['checked' => FALSE],
        ],
      ];

      if (isset($form['field_publish_externally'])) {
        $contentPageStates['visible'][':input[name="field_publish_externally[value]"]'] =
           ['checked' => FALSE];

        $form['field_announcement_all_pages']['#states'] = [
          'visible' => [
            ':input[name="field_publish_externally[value]"]' => ['checked' => FALSE],
          ],
        ];
      }

      $form['field_announcement_content_pages']['#states'] = $contentPageStates;
      break;
  }
}

/**
 * Implements hook_content_translation_status_access().
 */
function helfi_node_announcement_content_translation_status_access($form_id) : bool {
  return !in_array($form_id, ['node_announcement_edit_form', 'node_announcement_form']);
}
