<?php

/**
 * @file
 * Contains hooks for 'helfi_node_announcement' module.
 */

declare(strict_types = 1);

/**
 * Implements hook_form_FORM_ID_alter().
 */
function helfi_node_announcement_form_node_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'node_announcement_edit_form':
    case 'node_announcement_form':
      $form['field_announcement_content_pages']['#states'] = [
        'visible' => [
          ':input[name="field_announcement_all_pages[value]"]' => ['checked' => FALSE],
        ],
      ];
      break;
  }
}

/**
 * Implements hook_themes_installed().
 */
function helfi_node_announcement_themes_installed($theme_list) {
  /** @var Drupal\helfi_platform_config\Helper\BlockInstaller $block_installer */
  $block_installer = Drupal::service('helfi_platform_config.helper.block_installer');

  $block = [
    'id' => 'announcements',
    'plugin' => 'announcements',
    'settings' => [
      'id' => 'announcements',
      'label' => 'Announcements',
    ],
    'provider' => 'helfi_node_announcement',
    'weight' => -12,
  ];

  $variations = [
    [
      'theme' => 'hdbt',
      'region' => 'before_content',
    ],
    [
      'theme' => 'stark',
      'region' => 'content',
    ],
  ];
  $block_installer->install($block, $variations);
}
