<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraphs_contact_card_listing' module.
 */

declare(strict_types=1);

use Drupal\helfi_paragraphs_contact_card_listing\Entity\ContactCard;
use Drupal\helfi_paragraphs_contact_card_listing\Entity\SocialMediaLink;
use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_paragraphs_contact_card_listing_helfi_paragraph_types() : array {
  return [
    new ParagraphTypeCollection('paragraph', 'contact_card_listing', 'field_contact_card', 'contact_card'),
    new ParagraphTypeCollection('paragraphs_library_item', 'paragraphs_library_item', 'paragraphs', 'contact_card_listing'),
  ];
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function helfi_paragraphs_contact_card_listing_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['paragraph']['contact_card'])) {
    $bundles['paragraph']['contact_card']['class'] = ContactCard::class;
  }
  if (isset($bundles['paragraph']['social_media_link'])) {
    $bundles['paragraph']['social_media_link']['class'] = SocialMediaLink::class;
  }
}

/**
 * Implements hook_theme().
 */
function helfi_paragraphs_contact_card_listing_theme(): array {
  return [
    'helfi_social_media_link' => [
      'variables' => ['social_media_link' => NULL],
      'template' => 'helfi-social-media-link',
    ],
  ];
}
