<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraphs_content_cards' module.
 */

declare(strict_types=1);

use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_paragraphs_content_cards_helfi_paragraph_types() : array {
  return [
    new ParagraphTypeCollection('paragraphs_library_item', 'paragraphs_library_item', 'paragraphs', 'content_cards'),
  ];
}
