<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraphs_content_cards' module.
 */

declare(strict_types=1);

use Drupal\helfi_paragraphs_content_cards\Entity\ContentCards;
use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_paragraphs_content_cards_helfi_paragraph_types() : array {
  return [
    new ParagraphTypeCollection('paragraphs_library_item', 'paragraphs_library_item', 'paragraphs', 'content_cards'),
  ];
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function helfi_paragraphs_content_cards_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['paragraph']['content_cards'])) {
    $bundles['paragraph']['content_cards']['class'] = ContentCards::class;
  }
}

/**
 * Hero design values.
 *
 * @return int[]
 *   Values to select.
 */
function helfi_paragraphs_content_cards_allowed_values() : array {
  $designs = [
    'small-cards' => t('Small cards'),
    'large-cards' => t('Large cards'),
  ];
  /** @var \Drupal\Core\Extension\ModuleHandlerInterface $moduleHandler */
  $moduleHandler = Drupal::service('module_handler');

  // Let other modules alter the content cards design form validation.
  $moduleHandler->alter('hook_helfi_content_cards_design_alter', $designs);
  return $designs;
}
