field.field.node.page.field_content:
  expected_config: {}
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            calculator: calculator
          target_bundles_drag_drop:
            calculator:
              weight: 34
              enabled: true
field.field.node.page.field_lower_content:
  expected_config: {}
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            calculator: calculator
          target_bundles_drag_drop:
            calculator:
              weight: 34
              enabled: true
