user.role.admin:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'view any unpublished content'
user.role.content_producer:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'view any unpublished landing_page content'
        - 'view any unpublished page content'
