metatag.metatag_defaults.global:
  expected_config: {  }
  update_actions:
    add:
      tags:
        og_site_name: '[site:page-title-suffix]'
metatag.metatag_defaults.node:
  expected_config:
    tags:
      og_site_name: '[site:name]'
  update_actions:
    delete:
      tags:
        og_site_name: '[site:name]'
metatag.metatag_defaults.user:
  expected_config:
    tags:
      description: '[site:name]'
  update_actions:
    delete:
      tags:
        description: '[site:name]'
