entity_usage.settings:
  expected_config:
    local_task_enabled_entity_types: {  }
  update_actions:
    change:
      delete_warning_message_entity_types:
        - paragraphs_library_item
      edit_warning_message_entity_types:
        - paragraphs_library_item
      local_task_enabled_entity_types:
        - paragraphs_library_item
core.entity_form_display.paragraph.from_library.default:
  expected_config:
    content:
      field_reusable_paragraph:
        settings:
          match_limit: 10
        type: entity_reference_autocomplete
  update_actions:
    add:
      content:
        field_reusable_paragraph:
          settings:
            width: 100%
    change:
      content:
        field_reusable_paragraph:
          settings:
            autocomplete: false
            match_limit: 20
          type: select2_entity_reference
core.entity_view_display.paragraph.from_library.default:
  expected_config:
    content:
      field_reusable_paragraph:
        label: above
  update_actions:
    change:
      content:
        field_reusable_paragraph:
          label: hidden
core.entity_view_display.paragraphs_library_item.paragraphs_library_item.summary:
  expected_config:
    hidden: {  }
  update_actions:
    change:
      hidden:
        langcode: true
paragraphs.paragraphs_type.from_library:
  expected_config: {  }
  update_actions:
    add:
      description: 'The reusable paragraph allows you to insert a specific paragraph to multiple pages.'
      icon_default: null
      icon_uuid: null
user.role.anonymous:
  expected_config:
    permissions: {  }
  update_actions:
    add:
      permissions:
        - 'access content'
        - 'view remote entities'
user.role.authenticated:
  expected_config:
    permissions: {  }
  update_actions:
    add:
      permissions:
        - 'access content'
        - 'use text format full_html'
        - 'use text format minimal'
        - 'view remote entities'
views.view.paragraphs_library:
  expected_config:
    core: 8.x
  update_actions:
    delete:
      core: 8.x
    add:
      display:
        default:
          display_options:
            filters:
              default_langcode:
                expose:
                  operator_limit_selection: false
                  operator_list: {  }
              default_langcode_1:
                expose:
                  operator_limit_selection: false
                  operator_list: {  }
              label:
                expose:
                  operator_limit_selection: false
                  operator_list: {  }
              type:
                expose:
                  operator_limit_selection: false
                  operator_list: {  }
linkit.linkit_profile.default:
  expected_config: {  }
  update_actions:
    add:
      matchers:
        556010a3-e317-48b3-b4ed-854c10f4b950:
          settings:
            limit: 100
system.action.pathauto_update_alias_node:
  expected_config: {  }
  update_actions:
    add:
      configuration: {  }
system.action.pathauto_update_alias_user:
  expected_config: {  }
  update_actions:
    add:
      configuration: {  }
metatag.metatag_defaults.global:
  expected_config:
    tags:
      title: '[current-page:title] | [site:name]'
  update_actions:
    change:
      tags:
        image_src: '[site:base-url]/themes/custom/hdbt/src/images/og-global.png'
        title: '[current-page:title] | [site:page-title-suffix]'
        twitter_cards_page_url: '[current-page:url]'
        twitter_cards_title: '[current-page:title] | [site:page-title-suffix]'
        twitter_cards_type: summary_large_image
metatag.metatag_defaults.node:
  expected_config:
    tags:
      description: '[node:summary]'
      title: '[node:title] | [site:name]'
  update_actions:
    add:
      tags:
        article_modified_time: '[node:created:html_datetime]'
        article_published_time: '[node:created:html_datetime]'
    change:
      tags:
        content_language: '[node:langcode]'
        description: '[node:field_lead_in]'
        og_image_url: '[node:field_liftup_image:entity:field_media_image:og_image:url],[site:base-url]/themes/custom/hdbt/src/images/og-global.png'
        og_site_name: '[site:name]'
        og_title: '[node:title]'
        og_updated_time: '[node:changed:html_datetime]'
        og_url: '[current-page:url:absolute]'
        title: '[node:title] | [site:page-title-suffix]'
        twitter_cards_image: '[node:field_liftup_image:entity:field_media_image:1_1_thumbnail:url]'
metatag.metatag_defaults.taxonomy_term:
  expected_config:
    tags:
      title: '[term:name] | [site:name]'
  update_actions:
    change:
      tags:
        title: '[term:name] | [site:page-title-suffix]'
metatag.metatag_defaults.user:
  expected_config:
    tags:
      title: '[user:display-name] | [site:name]'
  update_actions:
    change:
      tags:
        title: '[user:display-name] | [site:page-title-suffix]'
field.field.paragraph.from_library.field_reusable_paragraph:
  expected_config:
    settings:
      handler: 'default:paragraphs_library_item'
  update_actions:
    add:
      settings:
        handler_settings:
          view:
            arguments: {  }
            display_name: entity_reference
            view_name: paragraphs_selection
    change:
      settings:
        handler: views
scheduler.settings:
  expected_config:
    lightweight_cron_access_key: ''
  update_actions:
    change:
      lightweight_cron_access_key: 4b55ad815783dea619af
social_media.settings:
  expected_config:
    social_media:
      email:
        default_img: 1
        text: Email
      facebook_share:
        attributes: |-
          target|_blank
          class|facebook-share
          rel|noopener noreferrer
        default_img: 1
        text: Facebook
      linkedin:
        attributes: |-
          target|_blank
          class|linkedin
          rel|noopener noreferrer
        default_img: 1
        text: Linkedin
      twitter:
        api_url: 'https://twitter.com/intent/tweet?url=[current-page:url]&url=[current-page:url]&hashtags=Hashtag'
        attributes: |-
          target|_blank
          class|twitter
          rel|noopener noreferrer
        default_img: 1
        text: Twitter
  update_actions:
    change:
      social_media:
        email:
          default_img: 0
          drupalSettings: ''
          enable_forward: 0
          img: email
          library: ''
          show_forward: 1
          text: 'Send as an email'
        facebook_share:
          attributes: "target|_blank\r\nclass|facebook-share"
          default_img: 0
          drupalSettings: ''
          img: facebook
          library: ''
          text: 'Share in Facebook'
        linkedin:
          attributes: "target|_blank\r\nclass|linkedin"
          default_img: 0
          drupalSettings: ''
          img: linkedin
          library: ''
          text: 'Share in Linkedin'
        twitter:
          api_url: 'https://twitter.com/intent/tweet?url=[current-page:url]&status=[current-page:title]+[current-page:url]'
          attributes: "target|_blank\r\nclass|twitter"
          default_img: 0
          drupalSettings: ''
          img: twitter
          library: ''
          text: 'Share in Twitter'
field.field.paragraph.text.field_text:
  expected_config: {  }
  update_actions:
    add:
      third_party_settings:
        allowed_formats:
          full_html: full_html
          minimal: '0'
          plain_text: '0'
core.date_format.long:
  expected_config:
    pattern: 'l, F j, Y - H:i'
  update_actions:
    change:
      pattern: 'j.n.Y - H:i'
core.date_format.medium:
  expected_config:
    pattern: 'D, m/d/Y - H:i'
  update_actions:
    change:
      pattern: 'jS F Y'
core.date_format.short:
  expected_config:
    pattern: 'm/d/Y - H:i'
  update_actions:
    change:
      pattern: j.n.Y

