field.field.tpr_service.tpr_service.field_content:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            phasing: phasing
          target_bundles_drag_drop:
            phasing:
              enabled: true
              weight: 50
            phasing_item:
              enabled: false
              weight: 30
field.field.tpr_service.tpr_service.field_lower_content:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            phasing: phasing
          target_bundles_drag_drop:
            phasing:
              enabled: true
              weight: 50
            phasing_item:
              enabled: false
              weight: 30
