core.entity_view_display.node.page.default:
  expected_config:
    content:
      field_content:
        weight: 2
      field_lower_content:
        weight: 4
      field_metatags:
        weight: 3
      field_sidebar_content:
        weight: 5
  update_actions:
    add:
      content:
        toc_enabled:
          label: hidden
          region: content
          settings:
            format: default
            format_custom_false: ''
            format_custom_true: ''
          third_party_settings: {  }
          type: boolean
          weight: 2
    change:
      content:
        field_content:
          weight: 3
        field_lower_content:
          weight: 5
        field_metatags:
          weight: 4
        field_sidebar_content:
          weight: 6
