core.entity_form_display.node.page.default:
  expected_config: {  }
  update_actions:
    add:
      content:
        hide_sidebar_navigation:
          type: boolean_checkbox
          weight: 21
          region: content
          settings:
            display_label: true
          third_party_settings: {  }
