metatag.metatag_defaults.global:
  expected_config:
    tags:
      image_src: '[site:base-url]/themes/custom/hdbt/src/images/og-global.png'
  update_actions:
    add:
      tags:
        og_image: '[site:default-og-image]'
    delete:
      tags:
        image_src: '[site:base-url]/themes/custom/hdbt/src/images/og-global.png'
metatag.metatag_defaults.node:
  expected_config:
    tags:
      og_image_url: '[node:field_liftup_image:entity:field_media_image:og_image:url],[site:base-url]/themes/custom/hdbt/src/images/og-global.png'
  update_actions:
    add:
      tags:
        og_image: '[node:shareable-image]'
    delete:
      tags:
        og_image_url: '[node:field_liftup_image:entity:field_media_image:og_image:url],/themes/contrib/hdbt/src/images/og-global.png'
