field.field.node.landing_page.field_content:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            popular_services: popular_services
            target_group_links: target_group_links
          target_bundles_drag_drop:
            popular_services:
              weight: 42
              enabled: true
            target_group_link_item:
              weight: 45
              enabled: false
            target_group_links:
              weight: 24
              enabled: true
