user.role.admin:
  expected_config: { }
  update_actions:
    add:
      permissions:
        - 'use text format full_html'
        - 'use text format minimal'
user.role.editor:
  expected_config: { }
  update_actions:
    add:
      permissions:
        - 'use text format full_html'
        - 'use text format minimal'
user.role.content_producer:
  expected_config: { }
  update_actions:
    add:
      permissions:
        - 'use text format full_html'
        - 'use text format minimal'
