entity_usage.settings:
  expected_config:
    local_task_enabled_entity_types: {  }
  update_actions:
    change:
      delete_warning_message_entity_types:
        - paragraphs_library_item
      edit_warning_message_entity_types:
        - paragraphs_library_item
      local_task_enabled_entity_types:
        - paragraphs_library_item
core.entity_form_display.paragraph.from_library.default:
  expected_config:
    content:
      field_reusable_paragraph:
        settings:
          match_limit: 10
        type: entity_reference_autocomplete
  update_actions:
    add:
      content:
        field_reusable_paragraph:
          settings:
            width: 100%
    change:
      content:
        field_reusable_paragraph:
          settings:
            autocomplete: false
            match_limit: 20
          type: select2_entity_reference
core.entity_view_display.paragraph.from_library.default:
  expected_config:
    content:
      field_reusable_paragraph:
        label: above
  update_actions:
    change:
      content:
        field_reusable_paragraph:
          label: hidden
core.entity_view_display.paragraphs_library_item.paragraphs_library_item.summary:
  expected_config:
    hidden: {  }
  update_actions:
    change:
      hidden:
        langcode: true
paragraphs.paragraphs_type.from_library:
  expected_config: {  }
  update_actions:
    add:
      description: null
      icon_default: null
      icon_uuid: null
user.role.anonymous:
  expected_config:
    permissions: {  }
  update_actions:
    add:
      permissions:
        - 'access content'
user.role.authenticated:
  expected_config:
    permissions: {  }
  update_actions:
    add:
      permissions:
        - 'access content'
views.view.paragraphs_library:
  expected_config:
    core: 8.x
  update_actions:
    delete:
      core: 8.x
    add:
      display:
        default:
          display_options:
            filters:
              default_langcode:
                expose:
                  operator_limit_selection: false
                  operator_list: {  }
              default_langcode_1:
                expose:
                  operator_limit_selection: false
                  operator_list: {  }
              label:
                expose:
                  operator_limit_selection: false
                  operator_list: {  }
              type:
                expose:
                  operator_limit_selection: false
                  operator_list: {  }
linkit.linkit_profile.default:
  expected_config: {  }
  update_actions:
    add:
      matchers:
        556010a3-e317-48b3-b4ed-854c10f4b950:
          settings:
            limit: 100
system.action.pathauto_update_alias_node:
  expected_config: {  }
  update_actions:
    add:
      configuration: {  }
system.action.pathauto_update_alias_user:
  expected_config: {  }
  update_actions:
    add:
      configuration: {  }
