core.entity_form_display.paragraph.phasing.default:
  expected_config:
    content:
    field_phasing_item_title_level:
      type: options_select
      weight: 4
      region: content
      settings: {  }
      third_party_settings: {  }
  update_actions:
    delete:
      content:
        field_phasing_item_title_level:
        type: options_select
        weight: 4
        region: content
        settings: {  }
        third_party_settings: {  }
core.entity_view_display.paragraph.phasing.default:
  expected_config:
    content:
    field_phasing_item_title_level:
      type: list_default
      label: hidden
      settings: {  }
      third_party_settings: {  }
      weight: 3
      region: content
  update_actions:
    delete:
      content:
        field_phasing_item_title_level:
        type: list_default
        label: hidden
        settings: {  }
        third_party_settings: {  }
        weight: 3
        region: content
