<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraphs_phasing' module.
 */

declare(strict_types = 1);

use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_paragraphs_phasing_helfi_paragraph_types() : array {
  return [
    new ParagraphTypeCollection('paragraph', 'phasing', 'field_phasing_item', 'phasing_item'),
  ];
}
