<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraphs_phasing' module.
 */

declare(strict_types = 1);

use Drupal\helfi_paragraphs_phasing\Entity\Phasing;
use Drupal\helfi_paragraphs_phasing\Entity\PhasingItem;
use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_paragraphs_phasing_helfi_paragraph_types() : array {
  return [
    new ParagraphTypeCollection('paragraph', 'phasing', 'field_phasing_item', 'phasing_item'),
  ];
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function helfi_paragraphs_phasing_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['paragraph']['phasing'])) {
    $bundles['paragraph']['phasing']['class'] = Phasing::class;
  }
  if (isset($bundles['paragraph']['phasing_item'])) {
    $bundles['paragraph']['phasing_item']['class'] = PhasingItem::class;
  }
}
