<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraphs_phasing' module.
 */

declare(strict_types = 1);

use Drupal\helfi_platform_config\DTO\EnableParagraphTypes;

/**
 * Implements hook_enable_paragraph_fields().
 */
function helfi_paragraphs_phasing_enable_paragraph_fields() : array {
  return [
    new EnableParagraphTypes('paragraph', 'phasing', 'field_phasing_item', 'phasing_item'),
  ];
}

