<?php

/**
 * @file
 * Contains installation tasks for hdbt_cookie_banner module.
 */

declare(strict_types=1);

use Drupal\user\Entity\Role;

/**
 * Implements hook_uninstall().
 */
function hdbt_cookie_banner_uninstall(): void {
  $config_factory = Drupal::configFactory();

  // The configurations to remove.
  $configurations = [
    'hdbt_cookie_banner.settings',
  ];

  // Remove each installed configuration.
  foreach ($configurations as $config) {
    $config_factory->getEditable($config)->delete();
  }
}

/**
 * Remove 'administer hdbt_cookie_banner' permission from 'admin' role.
 */
function hdbt_cookie_banner_update_11000(): void {
  if (!$role = Role::load('admin')) {
    return;
  }
  $role->revokePermission('administer hdbt_cookie_banner');
  $role->save();
}
