<?php

/**
 * @file
 * Contains module hooks for hdbt cookie banner.
 */

declare(strict_types=1);

use Drupal\Core\Language\LanguageInterface;
use Drupal\config_ignore\ConfigIgnoreConfig;
use Drupal\hdbt_cookie_banner\Form\HdbtCookieBannerForm;

/**
 * Implements hook_config_ignore_ignored_alter().
 */
function hdbt_cookie_banner_config_ignore_ignored_alter(ConfigIgnoreConfig $ignored): void {
  $settings_to_ignore = [
    'site_settings',
    'use_custom_settings',
    'use_internal_hds_cookie_js',
    'hds_cookie_js_override',
  ];

  $settings_to_ignore = array_map(
    fn($setting) => HdbtCookieBannerForm::SETTINGS . ':' . $setting,
    $settings_to_ignore,
  );

  // Add the configuration objects to the ignore list, but retain the
  // hdbt_cookie_banner.settings.
  foreach (['create', 'update', 'delete'] as $operation) {
    foreach (['import', 'export'] as $direction) {
      $list = array_merge(
        $ignored->getList($direction, $operation),
        $settings_to_ignore,
      );
      $ignored->setList($direction, $operation, $list);
    }
  }
}

/**
 * Implements hook_theme().
 */
function hdbt_cookie_banner_theme() : array {
  return [
    'cookie_settings_page' => [
      'variables' => [
        'title' => NULL,
        'content' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function hdbt_cookie_banner_page_attachments(array &$attachments) : void {
  $config = \Drupal::configFactory()->get(HdbtCookieBannerForm::SETTINGS);
  $langcode = \Drupal::languageManager()->getCurrentLanguage(LanguageInterface::TYPE_CONTENT)->getId();
  $attachments['#cache']['tags'] = array_merge($attachments['#cache']['tags'] ?? [], $config->getCacheTags());

  /** @var \Drupal\hdbt_cookie_banner\Services\CookieSettings $cookie_settings_service */
  $cookie_settings_service = \Drupal::service('hdbt_cookie_banner.cookie_settings');

  // By default, we use the hel.fi etusivu instance HDS cookie consent JS file.
  if (empty($config->get('use_custom_settings'))) {
    $cookie_settings_service->injectBannerJavaScript($attachments);
  }
  // We can also use the current instance HDS cookie consent JS file.
  elseif (empty($config->get('use_internal_hds_cookie_js'))) {
    $attachments['#attached']['library'][] = 'hdbt_cookie_banner/hds_cookie_consent';
  }
  // Or the custom HDS cookie consent JS file can be used.
  else {
    $cookie_settings_service->injectBannerJavaScript(
      $attachments,
      $config->get('hds_cookie_js_override')
    );
  }

  // Attach HDBT cookie banner initialization JS file.
  $attachments['#attached']['library'][] = 'hdbt_cookie_banner/hdbt_cookie_banner';

  // Attach HDBT cookie banner settings.
  $attachments['#attached']['drupalSettings']['hdbt_cookie_banner'] = [
    'apiUrl' => $cookie_settings_service->getCookieBannerApiUrl(),
    'langcode' => $langcode,
    'theme' => 'black',
    'settingsPageSelector' => '.cookie-settings',
    'settingsPageUrl' => $cookie_settings_service->getCookieSettingsPageUrl()?->setAbsolute()?->toString(),
  ];

  // Fallback for the old variable used in HDBT theme react search JS.
  // @todo UHF-10862 Remove once the HDBT cookie banner module is in use.
  $attachments['#attached']['drupalSettings']['helfi_react_search'] = [
    'cookie_privacy_url' => $cookie_settings_service->getCookieSettingsPageUrl()?->setAbsolute()?->toString(),
  ];
}
