config_rewrite: replace
report-only:
  enable: true
  directives:
    base-uri:
      base: none
    frame-ancestors:
      base: self
    default-src:
      base: self
    connect-src:
      base: self
      sources:
        - 'https://www.youtube-nocookie.com'
    img-src:
      base: self
      sources:
        - 'data:'
        - '*.blob.core.windows.net'
        - 'https://coh-chat-app-prod.ow6i4n9pdzm.eu-de.codeengine.appdomain.cloud'
    script-src:
      base: self
      flags:
        - report-sample
        - unsafe-inline
    style-src:
      base: self
      flags:
        - report-sample
    script-src-elem:
      base: self
      flags:
        - report-sample
        - unsafe-inline
      sources:
        - 'https://coh-chat-app-prod.ow6i4n9pdzm.eu-de.codeengine.appdomain.cloud'
    style-src-elem:
      base: self
      flags:
        - report-sample
        - unsafe-inline
      sources:
        - 'https://coh-chat-app-prod.ow6i4n9pdzm.eu-de.codeengine.appdomain.cloud'
    font-src:
      base: self
      sources:
        - 'https://coh-chat-app-prod.ow6i4n9pdzm.eu-de.codeengine.appdomain.cloud'
  reporting:
    plugin: raven
enforce:
  enable: false
  directives:
    object-src:
      base: none
    script-src:
      base: any
      flags:
        - report-sample
        - unsafe-inline
    style-src:
      base: any
      flags:
        - report-sample
        - unsafe-inline
    webrtc: block
    worker-src:
      base: self
    base-uri:
      base: self
    form-action:
      base: self
    frame-ancestors:
      base: self
  reporting:
    plugin: none
