config_rewrite: replace
report-only:
  enable: true
  directives:
    base-uri:
      base: none
    frame-ancestors:
      base: self
    default-src:
      base: self
    connect-src:
      base: self
      sources:
        - 'https://www.youtube-nocookie.com'
        - 'https://coh-chat-app-prod.ow6i4n9pdzm.eu-de.codeengine.appdomain.cloud'
        - 'https://*.hel.fi'
        - 'https://coh-chat-app-test.mo1wrhhyog0.eu-de.codeengine.appdomain.cloud'
    img-src:
      base: self
      sources:
        - 'data:'
        - '*.blob.core.windows.net'
        - 'https://coh-chat-app-prod.ow6i4n9pdzm.eu-de.codeengine.appdomain.cloud'
        - 'https://*.hel.fi'
        - 'https://coh-chat-app-test.mo1wrhhyog0.eu-de.codeengine.appdomain.cloud'
    script-src:
      base: self
      flags:
        - report-sample
        - unsafe-inline
    style-src:
      base: self
      flags:
        - report-sample
    script-src-elem:
      base: self
      flags:
        - report-sample
        - unsafe-inline
      sources:
        - 'https://coh-chat-app-prod.ow6i4n9pdzm.eu-de.codeengine.appdomain.cloud'
        - 'https://*.hel.fi'
        - 'https://coh-chat-app-test.mo1wrhhyog0.eu-de.codeengine.appdomain.cloud'
    style-src-elem:
      base: self
      flags:
        - report-sample
        - unsafe-inline
      sources:
        - 'https://coh-chat-app-prod.ow6i4n9pdzm.eu-de.codeengine.appdomain.cloud'
        - 'https://*.hel.fi'
        - 'https://coh-chat-app-test.mo1wrhhyog0.eu-de.codeengine.appdomain.cloud'
    font-src:
      base: self
      sources:
        - 'https://coh-chat-app-prod.ow6i4n9pdzm.eu-de.codeengine.appdomain.cloud'
        - 'https://*.hel.fi'
        - 'https://coh-chat-app-test.mo1wrhhyog0.eu-de.codeengine.appdomain.cloud'
    frame-src:
      base: self
      sources:
        - 'https://coh-chat-app-prod.ow6i4n9pdzm.eu-de.codeengine.appdomain.cloud'
        - 'https://*.hel.fi'
        - 'https://coh-chat-app-test.mo1wrhhyog0.eu-de.codeengine.appdomain.cloud'
        - 'https://*.siteimprove.com'
        - 'https://*.userneeds.com'
        - 'https://agreeable-island-03e85b803.azurestaticapps.net'
        - 'https://*.hotjar.com'
        - 'https://coh-chat-app-ibm.eu-de.mybluemix.net'
        - 'https://coh-chat-app-prod-ibm.eu-de.mybluemix.net'
        - 'https://suite.icareus.com'
        - 'https://*.helsinkikanava.fi'
        - 'https://*.youtube.com'
        - 'https://*.youtu.be'
        - 'https://*.facebook.com'
        - 'https://*.twitter.com'
        - 'https://*.linkedin.com'
        - 'https://*.readspeaker.com'
        - 'https://*.vimeo.com'
        - 'https://*.google.com'
        - 'https://*.siteimproveanalytics.com'
        - 'https://*.snoobi.com'
        - 'https://*.dreambroker.com'
        - 'https://youtu.be'
        - 'https://dreambroker.com'
        - 'https://pollev.com'
        - 'https://e.infogram.com'
        - 'https://tyoterveys-helsinki-pv.mail-eur.net'
        - 'https://walls.io'
        - 'https://*.youtube-nocookie.com'
        - 'https://*.flockler.com'
        - 'https://*.lightwidget.com'
        - 'https://hel-thk-botti.kuurahealth.com'
        - 'https://*.giosg.com'
        - 'https://*.giosgusercontent.com'
        - 'https://helfi.fi1.frosmo.com'
        - 'https://survey.feedbackly.com'
        - 'https://survey.userneeds.com'
        - 'https://*.powerbi.com'
        - 'https://coh-chat-app-test.eu-de.mybluemix.net'
        - 'https://coh-chat-app-dev.eu-de.mybluemix.net'
        - 'https://coh-chat-app-prod.eu-de.mybluemix.net'
        - 'https://hkp.maanmittauslaitos.fi'
        - 'https://reittiopas.hsl.fi'
        - 'https://players.icareus.com'
        - 'https://wds.ace.teliacompany.com'
  reporting:
    plugin: raven
enforce:
  enable: false
  directives:
    object-src:
      base: none
    script-src:
      base: any
      flags:
        - report-sample
        - unsafe-inline
    style-src:
      base: any
      flags:
        - report-sample
        - unsafe-inline
    webrtc: block
    worker-src:
      base: self
    base-uri:
      base: self
    form-action:
      base: self
    frame-ancestors:
      base: self
  reporting:
    plugin: none
