<?php

/**
 * @file
 * Contains alterations for 'helfi_eu_cookie_compliance' module.
 */

declare(strict_types=1);

use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\Url;

/**
 * Implements hook_platform_config_grant_permissions().
 */
function helfi_eu_cookie_compliance_platform_config_grant_permissions() : array {
  return [
    'anonymous' => [
      'display eu cookie compliance popup',
    ],
    'authenticated' => [
      'display eu cookie compliance popup',
    ],
    'admin' => [
      'administer eu cookie compliance categories',
      'administer eu cookie compliance popup',
    ],
  ];
}

/**
 * Implements hook_themes_installed().
 */
function helfi_eu_cookie_compliance_themes_installed($theme_list) {

  /** @var Drupal\helfi_platform_config\Helper\BlockInstaller $block_installer */
  $block_installer = Drupal::service('helfi_platform_config.helper.block_installer');

  foreach ($theme_list as $theme) {
    if (in_array($theme, ['stark', 'hdbt', 'hdbt_subtheme'])) {
      foreach (helfi_eu_cookie_compliance_get_block_configurations($theme) as $block_config) {
        ['block' => $block, 'variations' => $variations] = $block_config;
        $block_installer->install($block, $variations);
      }
    }
  }
}

/**
 * Gets the block configurations.
 *
 * Example block:
 *
 * @code
 * [
 *   'breadbrumbs' => [
 *     'block' => [
 *       ...
 *     ],
 *     'variations' => [
 *       ...
 *     ],
 *   ],
 * ];
 * @endcode
 *
 * @return array[]
 *   The block configurations.
 */
function helfi_eu_cookie_compliance_get_block_configurations(string $theme) : array {
  return [
    'eucookiecomplianceblock' => [
      'block' => [
        'id' => 'eucookiecomplianceblock',
        'plugin' => 'eu_cookie_compliance_block',
        'provider' => 'helfi_eu_cookie_compliance',
        'settings' => [
          'id' => 'eu_cookie_compliance_block',
          'label' => 'Eu Cookie Compliance Block',
          'provider' => 'eu_cookie_compliance',
        ],
        'weight' => -8,
        'visibility' => [
          'request_path' => [
            'id' => 'request_path',
            'negate' => FALSE,
            'pages' => '/cookie-information-and-settings',
          ],
        ],
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'after_content',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
  ];
}

/**
 * Helper function to get the privacy policy link URL.
 */
function helfi_eu_cookie_compliance_get_privacy_policy_url(): Url|string {
  $config = Drupal::config('eu_cookie_compliance.settings');
  $link = $config->get('popup_link');

  if (!$link) {
    return Url::fromRoute('<front>');
  }

  return (UrlHelper::isExternal($link))
    ? Url::fromUri($link)
    : Url::fromUserInput($link === '<front>' ? '/' : $link);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function helfi_eu_cookie_compliance_form_eu_cookie_compliance_block_form_alter(&$form): void {
  // Hide 'withdraw' button from EU Cookie compliance block form.
  $form['buttons']['withdraw']['#access'] = FALSE;
}

/**
 * Implements hook_page_attachments().
 */
function helfi_eu_cookie_compliance_page_attachments(array &$attachments) : void {
  // Attach temporary global cookie consent checker.
  $attachments['#attached']['library'][] = 'helfi_eu_cookie_compliance/cookie_consent';
}
