<?php

/**
 * @file
 * Contains alterations for 'helfi_eu_cookie_compliance' module.
 */

declare(strict_types = 1);

use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\eu_cookie_compliance\Entity\CookieCategory;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function helfi_eu_cookie_compliance_form_cookie_category_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\eu_cookie_compliance\Entity\CookieCategory $entity */
  $entity = $form_state->getFormObject()->getEntity();
  $settings = $entity->getThirdPartySettings('helfi_eu_cookie_compliance');

  // Disable the original description field.
  $form['description']['#access'] = FALSE;

  $form['third_party_settings']['helfi_eu_cookie_compliance']['content'] = [
    '#type' => 'text_format',
    '#format' => $settings['content']['format'] ?? NULL,
    '#title' => t('Description'),
    '#default_value' => $settings['content']['value'] ?? NULL,
    '#description' => t("The description that will be shown to the website visitor."),
    '#required' => FALSE,
  ];
  $form['#entity_builders'][] = 'helfi_eu_cookie_compliance_category_form_builder';
}

/**
 * The entity builder form callback.
 */
function helfi_eu_cookie_compliance_category_form_builder(string $entity_type, CookieCategory $category, array &$form, FormStateInterface $formState) : void {
  $category->setThirdPartySetting('helfi_eu_cookie_compliance', 'content', $formState->getValue('content'));
}

/**
 * Implements hook_themes_installed().
 */
function helfi_eu_cookie_compliance_themes_installed($theme_list) : void {
  /** @var Drupal\helfi_platform_config\Helper\BlockInstaller $block_installer */
  $block_installer = Drupal::service('helfi_platform_config.helper.block_installer');

  foreach ($theme_list as $theme) {
    if (in_array($theme, ['stark', 'hdbt', 'hdbt_subtheme'])) {
      foreach (helfi_eu_cookie_compliance_get_block_configurations($theme) as $block_config) {
        ['block' => $block, 'variations' => $variations] = $block_config;
        $block_installer->install($block, $variations);
      }
    }
  }
}

/**
 * Gets the block configurations.
 *
 * Example block:
 *
 * @code
 * [
 *   'breadbrumbs' => [
 *     'block' => [
 *       ...
 *     ],
 *     'variations' => [
 *       ...
 *     ],
 *   ],
 * ];
 * @endcode
 *
 * @return array[]
 *   The block configurations.
 */
function helfi_eu_cookie_compliance_get_block_configurations(string $theme) : array {
  return [
    'eucookiecomplianceblock' => [
      'block' => [
        'id' => 'eucookiecomplianceblock',
        'plugin' => 'eu_cookie_compliance_block',
        'provider' => 'helfi_eu_cookie_compliance',
        'settings' => [
          'id' => 'eu_cookie_compliance_block',
          'label' => 'Eu Cookie Compliance Block',
          'provider' => 'eu_cookie_compliance',
        ],
        'weight' => -8,
        'visibility' => [
          'request_path' => [
            'id' => 'request_path',
            'negate' => FALSE,
            'pages' => '/cookie-information-and-settings',
          ],
        ],
      ],
      'variations' => [
        [
          'theme' => $theme,
          'region' => 'after_content',
        ],
        [
          'theme' => 'stark',
          'region' => 'content',
        ],
      ],
    ],
  ];
}

/**
 * Helper function to get the privacy policy link URL.
 */
function helfi_eu_cookie_compliance_get_privacy_policy_url(): Url|string {
  $config = Drupal::config('eu_cookie_compliance.settings');
  $link = $config->get('popup_link');

  if (!$link) {
    return Url::fromRoute('<front>');
  }

  return (UrlHelper::isExternal($link))
    ? Url::fromUri($link)
    : Url::fromUserInput($link === '<front>' ? '/' : $link);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function helfi_eu_cookie_compliance_form_eu_cookie_compliance_block_form_alter(&$form): void {
  // Hide 'withdraw' button from EU Cookie compliance block form.
  $form['buttons']['withdraw']['#access'] = FALSE;
}
