<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraphs_phasing' module.
 */

declare(strict_types = 1);

use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_paragraphs_columns_helfi_paragraph_types() : array {
  return [
    new ParagraphTypeCollection('paragraph', 'columns', 'field_columns_right_column', 'text'),
    new ParagraphTypeCollection('paragraph', 'columns', 'field_columns_right_column', 'image'),
    new ParagraphTypeCollection('paragraph', 'columns', 'field_columns_left_column', 'text'),
    new ParagraphTypeCollection('paragraph', 'columns', 'field_columns_left_column', 'image'),
    new ParagraphTypeCollection('paragraphs_library_item', 'paragraphs_library_item', 'paragraphs', 'columns'),
  ];
}

