<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraphs_columns' module.
 */

declare(strict_types = 1);

use Drupal\helfi_platform_config\DTO\EnableParagraphTypes;

/**
 * Implements hook_enable_paragraph_fields().
 */
function helfi_paragraphs_columns_enable_paragraph_fields() : array {
  return [
    new EnableParagraphTypes('node', 'page', ['field_content', 'field_lower_content'], 'columns'),
    new EnableParagraphTypes('node', 'landing_page', ['field_content'], 'columns'),
    new EnableParagraphTypes('paragraph', 'columns', ['field_columns_left_column', 'field_columns_right_column'], 'text'),
    new EnableParagraphTypes('paragraph', 'columns', ['field_columns_left_column', 'field_columns_right_column'], 'image'),
  ];
}
