<?php

/**
 * @file
 * Primary module hooks for helfi_content module.
 */



/**
 * Implements hook_preprocess_HOOK().
 */
function helfi_content_preprocess_page(array &$variables) {
  $config_factory = \Drupal::configFactory();

  $hero_designs = $config_factory->getEditable('field.storage.paragraph.field_hero_design');
  $hero_designs_data = $hero_designs->getRawData();
  dump($hero_designs_data['settings']['allowed_values']);

  foreach ($hero_designs_data['settings']['allowed_values'] as $key => $allowed_value) {
    if (in_array('without-image-center', $allowed_value)) {
      unset($hero_designs_data['settings']['allowed_values'][$key]);
    }
    if (in_array('background-image', $allowed_value)) {
      unset($hero_designs_data['settings']['allowed_values'][$key]);
    }
  }
  
  $hero_designs_data['settings']['allowed_values'] = array_values($hero_designs_data['settings']['allowed_values']);
  dump($hero_designs_data['settings']['allowed_values']);
}
