<?php

/**
 * @file
 * Contains HELfi content alterations.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function helfi_content_page_attachments_alter(array &$attachments) {
  // Set custom content type metatag on all content pages.
  if (empty($attachments['#attached']['html_head'])) {
    return;
  }

  $entities = array_filter(
    \Drupal::routeMatch()->getParameters()->all(),
    function($param) {
      return $param instanceof \Drupal\Core\Entity\EntityInterface;
    }
  );

  $entity = !empty($entities) ? reset($entities) : NULL;
  if ($entity) {
    $tag_name = 'helfi_content_type';

    $type = method_exists($entity, 'getType') ? $entity->getType() : $entity->getEntityTypeId();
    $helfi_content_type = [
      '#tag' => 'meta',
      '#attributes' => [
        'name' => $tag_name,
        'content' => $type,
      ],
    ];
    $attachments['#attached']['html_head'][] = [$helfi_content_type, $tag_name];
  }
}
