<?php


/**
 * Base configuration for HELfi Content feature.
 */
function helfi_content_update_9001() {
  /** @var \Drupal\update_helper\Updater $updateHelper */
  $updateHelper = \Drupal::service('update_helper.updater');

  // Execute configuration update definitions with logging of success.
  $updateHelper->executeUpdate('helfi_content', 'helfi_content_update_9001');

  // Output logged messages to related channel of update execution.
  return $updateHelper->logger()->output();
}
