config_rewrite:
  replace: ['dependencies']
dependencies:
  config:
    - field.field.node.news_item.field_content
    - field.field.node.news_item.field_lead_in
    - field.field.node.news_item.field_main_image
    - field.field.node.news_item.field_main_image_caption
    - field.field.node.news_item.field_news_item_links_link
    - field.field.node.news_item.field_news_item_links_title
    - field.field.node.news_item.field_news_item_tags
    - field.field.node.news_item.field_short_title
    - node.type.news_item
  module:
    - field_group
    - hdbt_admin_tools
    - helfi_ai
    - linkit
    - media_library
    - paragraphs
    - path
    - publication_date
    - scheduler
    - select2
content:
  ai_summary:
    type: ai_summary
    weight: 18
    region: content
    settings: { }
    third_party_settings:
      allowed_formats:
        hide_help: '1'
        hide_guidelines: '1'
