config_rewrite:
  replace: [
    'settings.toolbar.items',
  ]
settings:
  toolbar:
    items:
      - bold
      - italic
      - '|'
      - bulletedList
      - numberedList
      - '|'
      - link
      - helfiLanguageSelector
      - '|'
      - helfiAiToneCheck
      - '|'
      - sourceEditing
