helfi_csp.settings:
  type: config_object
  label: 'HELFI CSP settings'
  mapping:
    time_window:
      type: integer
      label: 'Time window for aggregated logs (seconds)'
    treshold:
      type: integer
      label: 'Minimum number of log reports within the time window to include in the aggregation'
    stop_recieving:
      type: boolean
      label: 'Stop recieving incoming reports.'
    stop_sending:
      type: boolean
      label: 'Stop sending aggregated reports in cron runs.'