views.view.service_list:
  expected_config: { }
  update_actions:
    add:
      dependencies:
        config:
          - core.entity_view_mode.tpr_service.teaser_search_result
      display:
        block_1:
          id: block_1
          display_title: Block
          display_plugin: block
          position: 3
          display_options:
            title: 'Service list search'
            fields:
              name:
                id: name
                table: tpr_service_field_data
                field: name
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: null
                entity_field: name
                plugin_id: field
                label: ''
                exclude: false
                alter:
                  alter_text: false
                  text: ''
                  make_link: false
                  path: ''
                  absolute: false
                  external: false
                  replace_spaces: false
                  path_case: none
                  trim_whitespace: false
                  alt: ''
                  rel: ''
                  link_class: ''
                  prefix: ''
                  suffix: ''
                  target: ''
                  nl2br: false
                  max_length: 0
                  word_boundary: true
                  ellipsis: true
                  more_link: false
                  more_link_text: ''
                  more_link_path: ''
                  strip_tags: false
                  trim: false
                  preserve_tags: ''
                  html: false
                element_type: h2
                element_class: ''
                element_label_type: ''
                element_label_class: ''
                element_label_colon: false
                element_wrapper_type: ''
                element_wrapper_class: ''
                element_default_classes: true
                empty: ''
                hide_empty: false
                empty_zero: false
                hide_alter_empty: true
                click_sort_column: value
                type: string
                settings:
                  link_to_entity: false
                group_column: value
                group_columns: {  }
                group_rows: true
                delta_limit: 0
                delta_offset: 0
                delta_reversed: false
                delta_first_last: false
                multi_type: separator
                separator: ', '
                field_api_classes: false
              name_synonyms:
                id: name_synonyms
                table: tpr_service_field_data
                field: name_synonyms
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: tpr_service
                entity_field: name_synonyms
                plugin_id: field
                label: ''
                exclude: false
                alter:
                  alter_text: false
                  text: ''
                  make_link: false
                  path: ''
                  absolute: false
                  external: false
                  replace_spaces: false
                  path_case: none
                  trim_whitespace: false
                  alt: ''
                  rel: ''
                  link_class: ''
                  prefix: ''
                  suffix: ''
                  target: ''
                  nl2br: false
                  max_length: 0
                  word_boundary: true
                  ellipsis: true
                  more_link: false
                  more_link_text: ''
                  more_link_path: ''
                  strip_tags: false
                  trim: false
                  preserve_tags: ''
                  html: false
                element_type: ''
                element_class: ''
                element_label_type: ''
                element_label_class: ''
                element_label_colon: false
                element_wrapper_type: ''
                element_wrapper_class: ''
                element_default_classes: true
                empty: ''
                hide_empty: false
                empty_zero: false
                hide_alter_empty: true
                click_sort_column: value
                type: basic_string
                settings: {  }
                group_column: value
                group_columns: {  }
                group_rows: true
                delta_limit: 0
                delta_offset: 0
                delta_reversed: false
                delta_first_last: false
                multi_type: separator
                separator: ', '
                field_api_classes: false
              description__summary:
                id: description__summary
                table: tpr_service_field_data
                field: description__summary
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: tpr_service
                entity_field: description
                plugin_id: field
                label: ''
                exclude: false
                alter:
                  alter_text: false
                  text: ''
                  make_link: false
                  path: ''
                  absolute: false
                  external: false
                  replace_spaces: false
                  path_case: none
                  trim_whitespace: false
                  alt: ''
                  rel: ''
                  link_class: ''
                  prefix: ''
                  suffix: ''
                  target: ''
                  nl2br: false
                  max_length: 0
                  word_boundary: true
                  ellipsis: true
                  more_link: false
                  more_link_text: ''
                  more_link_path: ''
                  strip_tags: false
                  trim: false
                  preserve_tags: ''
                  html: false
                element_type: ''
                element_class: ''
                element_label_type: ''
                element_label_class: ''
                element_label_colon: false
                element_wrapper_type: ''
                element_wrapper_class: ''
                element_default_classes: true
                empty: ''
                hide_empty: false
                empty_zero: false
                hide_alter_empty: true
                click_sort_column: value
                type: text_default
                settings: {  }
                group_column: value
                group_columns: {  }
                group_rows: true
                delta_limit: 0
                delta_offset: 0
                delta_reversed: false
                delta_first_last: false
                multi_type: separator
                separator: ', '
                field_api_classes: false
            pager:
              type: full
              options:
                offset: 0
                items_per_page: 5
                total_pages: null
                id: 0
                tags:
                  next: 'Next ›'
                  previous: '‹ Previous'
                  first: '« First'
                  last: 'Last »'
                expose:
                  items_per_page: false
                  items_per_page_label: 'Items per page'
                  items_per_page_options: '5, 10, 25, 50'
                  items_per_page_options_all: false
                  items_per_page_options_all_label: '- All -'
                  offset: false
                  offset_label: Offset
                quantity: 9
            sorts:
              name:
                id: name
                table: tpr_service_field_data
                field: name
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: tpr_service
                entity_field: name
                plugin_id: standard
                order: ASC
                expose:
                  label: ''
                  field_identifier: name
                exposed: false
              name_override:
                id: name_override
                table: tpr_service_field_data
                field: name_override
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: tpr_service
                entity_field: name_override
                plugin_id: standard
                order: ASC
                expose:
                  label: ''
                  field_identifier: name_override
                exposed: false
            arguments:
              id_or_service_id:
                id: id_or_service_id
                table: tpr_service_field_data
                field: id_or_service_id
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: tpr_service
                plugin_id: id_or_service_id_handler
                default_action: ignore
                exception:
                  value: all
                  title_enable: false
                  title: All
                title_enable: false
                title: ''
                default_argument_type: fixed
                default_argument_options:
                  argument: ''
                default_argument_skip_url: false
                summary_options:
                  base_path: ''
                  count: true
                  override: false
                  items_per_page: 25
                summary:
                  sort_order: asc
                  number_of_records: 0
                  format: default_summary
                specify_validation: false
                validate:
                  type: none
                  fail: 'not found'
                validate_options: {  }
            filters:
              content_translation_status:
                id: content_translation_status
                table: tpr_service_field_data
                field: content_translation_status
                entity_type: tpr_service
                entity_field: content_translation_status
                plugin_id: boolean
                value: '1'
                group: 1
                expose:
                  operator: ''
                  operator_limit_selection: false
                  operator_list: {  }
              langcode:
                id: langcode
                table: tpr_service_field_data
                field: langcode
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: tpr_service
                entity_field: langcode
                plugin_id: language
                operator: in
                value:
                  '***LANGUAGE_language_content***': '***LANGUAGE_language_content***'
                group: 1
                exposed: false
                expose:
                  operator_id: ''
                  label: ''
                  description: ''
                  use_operator: false
                  operator: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  identifier: ''
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                  reduce: false
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: {  }
                  group_items: {  }
              combine:
                id: combine
                table: views
                field: combine
                relationship: none
                group_type: group
                admin_label: ''
                plugin_id: combine
                operator: word
                value: ''
                group: 1
                exposed: true
                expose:
                  operator_id: combine_op
                  label: 'Search services'
                  description: 'Search services by name or description.'
                  use_operator: false
                  operator: combine_op
                  operator_limit_selection: false
                  operator_list: {  }
                  identifier: combine
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                    anonymous: '0'
                    read_only: '0'
                    content_producer: '0'
                    editor: '0'
                    admin: '0'
                  placeholder: ''
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: {  }
                  group_items: {  }
                fields:
                  name: name
                  name_synonyms: name_synonyms
                  description__summary: description__summary
              status_extra:
                id: status_extra
                table: tpr_service_field_data
                field: status_extra
                relationship: none
                group_type: group
                admin_label: ''
                entity_type: tpr_service
                plugin_id: tpr_status
                operator: '='
                value: ''
                group: 1
                exposed: false
                expose:
                  operator_id: ''
                  label: ''
                  description: ''
                  use_operator: false
                  operator: ''
                  operator_limit_selection: false
                  operator_list: {  }
                  identifier: ''
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: {  }
                  group_items: {  }
            filter_groups:
              operator: AND
              groups:
                1: AND
            style:
              type: default
              options:
                row_class: ''
                default_row_class: true
                uses_fields: true
            row:
              type: 'entity:tpr_service'
              options:
                relationship: none
                view_mode: teaser_search_result
            defaults:
              title: false
              pager: false
              style: false
              row: false
              relationships: false
              fields: false
              sorts: false
              arguments: false
              filters: false
              filter_groups: false
            relationships: {  }
            display_extenders:
              metatag_display_extender:
                metatags: {  }
                tokenize: false
          cache_metadata:
            max-age: -1
            contexts:
              - 'languages:language_content'
              - 'languages:language_interface'
              - url
              - url.query_args
              - user
              - user.permissions
            tags: {  }
