core.entity_form_display.tpr_unit.tpr_unit.default:
  expected_config: { }
  update_actions:
    add:
      content:
        show_www:
          region: content
          settings:
            display_label: true
          third_party_settings: {  }
          type: boolean_checkbox
          weight: 11
