core.base_field_override.paragraphs_library_item.paragraphs_library_item.paragraphs:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            unit_search: unit_search
          target_bundles_drag_drop:
            unit_search:
              enabled: '1'
              weight: '30'
field.field.node.article.field_content:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            unit_search: unit_search
          target_bundles_drag_drop:
            unit_search:
              enabled: true
              weight: 28
field.field.node.landing_page.field_content:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            unit_search: unit_search
          target_bundles_drag_drop:
            unit_search:
              enabled: true
              weight: 28
field.field.node.page.field_content:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            unit_search: unit_search
          target_bundles_drag_drop:
            unit_search:
              enabled: true
              weight: 28
field.field.node.page.field_lower_content:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            unit_search: unit_search
          target_bundles_drag_drop:
            unit_search:
              enabled: true
              weight: -16
user.role.admin:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'access tpr_service overview'
        - 'access tpr_unit overview'
        - 'administer tpr_service'
        - 'administer tpr_unit'
        - 'revert all tpr_service revisions'
        - 'revert all tpr_unit revisions'
        - 'translate tpr_errand_service'
        - 'translate tpr_service'
        - 'translate tpr_service_channel'
        - 'translate tpr_unit'
        - 'update any tpr_service'
        - 'update any tpr_unit'
        - 'update own tpr_service'
        - 'update own tpr_unit'
        - 'update tpr_service'
        - 'update tpr_unit'
        - 'view all tpr_service revisions'
        - 'view all tpr_unit revisions'
        - 'view tpr_service'
        - 'view tpr_unit'
user.role.anonymous:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'view tpr_service'
        - 'view tpr_unit'
user.role.authenticated:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'view tpr_service'
        - 'view tpr_unit'
pathauto.settings:
  expected_config: { }
  update_actions:
    add:
      enabled_entity_types:
        - tpr_service
        - tpr_unit
