views.view.service_units:
  expected_config:
    display:
      default:
        display_options:
          pager:
            options:
              views_infinite_scroll:
                button_text: 'Load more service locations'
  update_actions:
    change:
      display:
        default:
          display_options:
            pager:
              options:
                views_infinite_scroll:
                  button_text: 'Load more service points'
