core.entity_view_display.tpr_unit.tpr_unit.teaser:
  expected_config:
    content:
      address:
        weight: 1
      name:
        weight: 0
      phone:
        label: hidden
        region: content
        settings:
          title: ''
        third_party_settings: {  }
        type: telephone_link
        weight: 2
    hidden:
      name_override: true
      picture_url: true
      picture_url_override: true
  update_actions:
    delete:
      content:
        phone:
          label: hidden
          region: content
          settings:
            title: ''
          third_party_settings: {  }
          type: telephone_link
          weight: 2
      hidden:
        name_override: true
        picture_url: true
        picture_url_override: true
    change:
      content:
        address:
          weight: 4
        name:
          weight: 2
        name_override:
          label: hidden
          region: content
          settings:
            link_to_entity: false
          third_party_settings: {  }
          type: string
          weight: 3
        picture_url:
          label: hidden
          region: content
          settings:
            imagecache_external_link: ''
            imagecache_external_responsive_style: image__3_2
          third_party_settings: {  }
          type: imagecache_external_responsive_image
          weight: 0
        picture_url_override:
          label: hidden
          region: content
          settings:
            link: false
            view_mode: image
          third_party_settings: {  }
          type: entity_reference_entity_view
          weight: 1
      hidden:
        phone: true
        provided_languages: true
