views.view.service_units:
  expected_config:
    display:
      default:
        display_options:
          row:
            options:
              view_mode: teaser
  update_actions:
    change:
      display:
        default:
          display_options:
            row:
              options:
                view_mode: teaser_with_image
