field.field.tpr_service.tpr_service.field_content:
  expected_config:
    settings:
      handler_settings:
        target_bundles:
          gallery: gallery
        target_bundles_drag_drop:
          gallery:
            enabled: true
  update_actions:
    delete:
      settings:
        handler_settings:
          target_bundles:
            gallery: gallery
    change:
      settings:
        handler_settings:
          target_bundles_drag_drop:
            gallery:
              enabled: false
field.field.tpr_service.tpr_service.field_lower_content:
  expected_config:
    settings:
      handler_settings:
        target_bundles:
          gallery: gallery
        target_bundles_drag_drop:
          gallery:
            enabled: true
  update_actions:
    delete:
      settings:
        handler_settings:
          target_bundles:
            gallery: gallery
    change:
      settings:
        handler_settings:
          target_bundles_drag_drop:
            gallery:
              enabled: false
field.field.tpr_unit.tpr_unit.field_content:
  expected_config:
    settings:
      handler_settings:
        target_bundles:
          gallery: gallery
        target_bundles_drag_drop:
          gallery:
            enabled: true
  update_actions:
    delete:
      settings:
        handler_settings:
          target_bundles:
            gallery: gallery
    change:
      settings:
        handler_settings:
          target_bundles_drag_drop:
            gallery:
              enabled: false
field.field.tpr_unit.tpr_unit.field_lower_content:
  expected_config:
    settings:
      handler_settings:
        target_bundles:
          gallery: gallery
        target_bundles_drag_drop:
          gallery:
            enabled: true
  update_actions:
    delete:
      settings:
        handler_settings:
          target_bundles:
            gallery: gallery
    change:
      settings:
        handler_settings:
          target_bundles_drag_drop:
            gallery:
              enabled: false
