core.entity_form_display.tpr_service.tpr_service.default:
  expected_config: {  }
  update_actions:
    add:
      content:
        hide_sidebar_navigation:
          type: boolean_checkbox
          weight: 21
          region: content
          settings:
            display_label: true
          third_party_settings: {  }
core.entity_form_display.tpr_unit.tpr_unit.default:
  expected_config: {  }
  update_actions:
    add:
      content:
        hide_sidebar_navigation:
          type: boolean_checkbox
          weight: 29
          region: content
          settings:
            display_label: true
          third_party_settings: {  }
