user.role.admin:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'view unpublished tpr_errand_service'
        - 'view unpublished tpr_service'
        - 'view unpublished tpr_service_channel'
        - 'view unpublished tpr_unit'
user.role.content_producer:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'view unpublished tpr_errand_service'
        - 'view unpublished tpr_service'
        - 'view unpublished tpr_service_channel'
        - 'view unpublished tpr_unit'
user.role.read_only:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'view unpublished tpr_errand_service'
        - 'view unpublished tpr_service'
        - 'view unpublished tpr_service_channel'
        - 'view unpublished tpr_unit'
