field.field.tpr_service.tpr_service.field_lower_content:
  expected_config: {  }
  update_actions:
    add:
      dependencies:
        config:
          - paragraphs.paragraphs_type.event_list
      settings:
        handler_settings:
          target_bundles:
            event_list: event_list
          target_bundles_drag_drop:
            event_list:
              weight: 44
              enabled: true
field.field.tpr_unit.tpr_unit.field_lower_content:
  expected_config: {  }
  update_actions:
    add:
      dependencies:
        config:
          - paragraphs.paragraphs_type.event_list
      settings:
        handler_settings:
          target_bundles:
            event_list: event_list
          target_bundles_drag_drop:
            event_list:
              weight: 44
              enabled: true
