pathauto.pattern.service_entity_pattern:
  expected_config:
    pattern: '[tpr_service:label]'
  update_actions:
    change:
      pattern: '[tpr_service:menu-link-parents]/[tpr_service:label]'
pathauto.pattern.unit_entity_pattern:
  expected_config:
    pattern: '[tpr_unit:label]'
  update_actions:
    change:
      pattern: '[tpr_unit:menu-link-parents]/[tpr_unit:label]'
pathauto.settings:
  expected_config: {  }
  update_actions:
    add:
      enabled_entity_types:
        - tpr_service
        - tpr_unit
      safe_tokens:
        - menu-link-parents
