views.view.service_list:
  expected_config:
    dependencies:
      module:
        - helfi_tpr
        - user
        - views_infinite_scroll
    display:
      default:
        display_options:
          pager:
            type: infinite_scroll
            options:
              tags:
                previous: '‹ Previous'
                next: 'Next ›'
              views_infinite_scroll:
                button_text: 'Load more services'
                automatically_load_content: false
                initially_load_all_pages: false
  update_actions:
    change:
      dependencies:
        module:
          - helfi_tpr
          - user
      display:
        default:
          display_options:
            pager:
              type: full
              options:
                tags:
                  next: Next
                  previous: Previous
                  first: First
                  last: Last
                quantity: 9
views.view.unit_search:
  expected_config:
    dependencies:
      module:
        - address
        - helfi_tpr
        - user
        - views_infinite_scroll
    display:
      default:
        display_options:
          pager:
            type: infinite_scroll
            options:
              tags:
                previous: '‹ Previous'
                next: 'Next ›'
              views_infinite_scroll:
                button_text: 'Load more results'
                automatically_load_content: false
                initially_load_all_pages: false
  update_actions:
    change:
      dependencies:
        module:
          - address
          - helfi_tpr
          - user
      display:
        default:
          display_options:
            pager:
              type: full
              options:
                tags:
                  next: Next
                  previous: Previous
                  first: First
                  last: Last
                quantity: 9
