field.field.tpr_unit.tpr_unit.field_content:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            contact_card_listing: contact_card_listing
          target_bundles_drag_drop:
            contact_card:
              enabled: false
              weight: 30
            contact_card_listing:
              enabled: true
              weight: 31
            social_media_link:
              enabled: false
              weight: 46
field.field.tpr_unit.tpr_unit.field_lower_content:
  expected_config: {  }
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            contact_card_listing: contact_card_listing
          target_bundles_drag_drop:
            contact_card:
              enabled: false
              weight: 30
            contact_card_listing:
              enabled: true
              weight: 31
            social_media_link:
              enabled: false
              weight: 46
