field.field.tpr_service.tpr_service.field_content:
  expected_config: {  }
  update_actions:
    add:
      dependencies:
        config:
          - paragraphs.paragraphs_type.remote_video
      settings:
        handler_settings:
          target_bundles:
            remote_video: remote_video
          target_bundles_drag_drop:
            remote_video:
              enabled: true
              weight: 41
field.field.tpr_unit.tpr_unit.field_content:
  expected_config: {  }
  update_actions:
    add:
      dependencies:
        config:
          - paragraphs.paragraphs_type.remote_video
      settings:
        handler_settings:
          target_bundles:
            remote_video: remote_video
          target_bundles_drag_drop:
            remote_video:
              enabled: true
              weight: 41
