core.entity_view_display.tpr_unit.tpr_unit.default:
  expected_config:
    content:
      service_map_embed:
        settings:
          link_title: 'View the map in new window'
  update_actions:
    change:
      content:
        service_map_embed:
          settings:
            link_title: 'Open the map in a new window'
