<?php

/**
 * @file
 * Contains installation tasks for helfi_paragraphs_liftup_with_image module.
 */

declare(strict_types=1);

/**
 * UHF-9088: Updated config translations for helfi_paragraphs_liftup_with_image.
 */
function helfi_paragraphs_liftup_with_image_update_9001(): void {
  \Drupal::service('helfi_platform_config.config_update_helper')
    ->update('helfi_paragraphs_liftup_with_image');
}
