<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraphs_liftup_with_image' module.
 */

declare(strict_types = 1);

use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_paragraphs_liftup_with_image_helfi_paragraph_types() : array {
  return [
    new ParagraphTypeCollection('paragraph', 'from_library', 'field_reusable_paragraph', 'liftup_with_image'),
  ];
}
