config_rewrite: replace
report-only:
  enable: false
  directives: {  }
  reporting:
    plugin: none
enforce:
  enable: true
  directives:
    object-src:
      base: self
      sources:
        - 'https://*.youtube-nocookie.com'
        - 'https://*.youtube.com'
        - 'https://*.youtu.be'
        - 'https://*.vimeo.com'
        - 'https://suite.icareus.com'
        - 'https://players.icareus.com'
        - 'https://events.icareus.com'
        - 'https://*.helsinkikanava.fi'
    frame-src:
      base: self
      sources:
        - 'https://*.hel.fi'
        - 'https://*.siteimprove.com'
        - 'https://*.userneeds.com'
        - 'https://agreeable-island-03e85b803.azurestaticapps.net'
        - 'https://*.hotjar.com'
        - 'https://suite.icareus.com'
        - 'https://*.helsinkikanava.fi'
        - 'https://*.youtube.com'
        - 'https://*.youtu.be'
        - 'https://*.facebook.com'
        - 'https://*.twitter.com'
        - 'https://*.linkedin.com'
        - 'https://*.readspeaker.com'
        - 'https://*.vimeo.com'
        - 'https://*.google.com'
        - 'https://*.siteimproveanalytics.com'
        - 'https://*.snoobi.com'
        - 'https://*.dreambroker.com'
        - 'https://youtu.be'
        - 'https://dreambroker.com'
        - 'https://pollev.com'
        - 'https://e.infogram.com'
        - 'https://infogram.com'
        - 'https://tyoterveys-helsinki-pv.mail-eur.net'
        - 'https://walls.io'
        - 'https://*.youtube-nocookie.com'
        - 'https://*.flockler.com'
        - 'https://*.lightwidget.com'
        - 'https://hel-thk-botti.kuurahealth.com'
        - 'https://*.giosg.com'
        - 'https://*.giosgusercontent.com'
        - 'https://helfi.fi1.frosmo.com'
        - 'https://survey.feedbackly.com'
        - 'https://survey.userneeds.com'
        - 'https://*.powerbi.com'
        - 'https://hkp.maanmittauslaitos.fi'
        - 'https://reittiopas.hsl.fi'
        - 'https://players.icareus.com'
        - 'https://wds.ace.teliacompany.com'
        - 'https://events.icareus.com'
    default-src:
      base: self
    connect-src:
      base: self
      sources:
        - 'https://*.hel.fi'
        - 'https://www.youtube-nocookie.com'
        - 'https://data.reactandshare.com'
        - 'https://webanalytics.digiaiiris.com'
        - 'https://*.askem.com'
        - 'https://*.siteimprove.com'
        - 'https://connect.facebook.net'
        - 'https://hel.humany.net'
        - 'https://wds.ace.teliacompany.com'
        - 'https://chat.ace.teliacompany.net'
        - 'https://api.ace.teliacompany.net'
    font-src:
      base: self
      sources:
        - 'https://*.hel.fi'
        - 'https://hel.humany.net'
        - 'https://makasiini.hel.ninja'
        - 'https://ace-knowledge-cdn.teliacompany.net'
    img-src:
      base: any
      sources:
        - 'data:'
        - '*.blob.core.windows.net'
        - 'https://data.reactandshare.com'
    media-src:
      base: self
      sources:
        - 'data:'
    script-src:
      base: self
      flags:
        - report-sample
        - unsafe-inline
        - unsafe-eval
        - wasm-unsafe-eval
      sources:
        - 'https://*.hel.fi'
        - 'https://cdn.reactandshare.com'
        - 'https://data.reactandshare.com'
        - 'https://*.askem.com'
        - 'https://webanalytics.digiaiiris.com'
        - 'https://connect.facebook.net'
        - 'https://wds.ace.teliacompany.com'
        - 'https://e.infogram.com'
    style-src:
      base: self
      flags:
        - report-sample
        - unsafe-inline
      sources:
        - 'https://*.hel.fi'
        - 'https://hel.humany.net'
        - 'https://wds.ace.teliacompany.com'
    base-uri:
      base: none
    frame-ancestors:
      base: self
  reporting:
    plugin: raven
