<?php

/**
 * @file
 * Contains hooks for 'helfi_node_landing_page' module.
 */

declare(strict_types = 1);

use Drupal\helfi_platform_config\DTO\EnableParagraphTypes;

/**
 * Implements hook_enable_paragraph_fields().
 */
function helfi_node_landing_page_enable_paragraph_fields() : array {
  return [
    new EnableParagraphTypes('node', 'landing_page', ['field_hero'], 'hero'),
    new EnableParagraphTypes('node', 'landing_page', ['field_content'], 'content_card'),
    new EnableParagraphTypes('node', 'landing_page', ['field_content'], 'content_cards'),
    new EnableParagraphTypes('node', 'landing_page', ['field_content'], 'content_liftup'),
    new EnableParagraphTypes('node', 'landing_page', ['field_content'], 'columns'),
    new EnableParagraphTypes('node', 'landing_page', ['field_content'], 'banner'),
    new EnableParagraphTypes('node', 'landing_page', ['field_content'], 'list_of_links'),
    new EnableParagraphTypes('node', 'landing_page', ['field_content'], 'liftup_with_image'),
    new EnableParagraphTypes('node', 'landing_page', ['field_content'], 'remote_video'),
    new EnableParagraphTypes('node', 'landing_page', ['field_content'], 'current'),
    new EnableParagraphTypes('node', 'landing_page', ['field_content'], 'target_group_links'),
    new EnableParagraphTypes('node', 'landing_page', ['field_content'], 'map'),
  ];
}
