<?php

/**
 * @file
 * Contains hooks for 'helfi_node_landing_page' module.
 */

declare(strict_types = 1);

use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_node_landing_page_helfi_paragraph_types() : array {
  $types = [
    'field_hero' => [
      'hero',
    ],
    'field_content' => [
      'columns',
      'list_of_links' ,
      'content_cards',
      'banner',
      'liftup_with_image',
      'from_library',
      'chart',
      'remote_video',
      'map',
      'news_list',
      'events',
      'phasing',
      'popular_services',
      'target_group_links',
    ],
  ];

  $enabled = [];
  foreach ($types as $field => $paragraphTypes) {
    foreach ($paragraphTypes as $paragraphType) {
      $enabled[] = new ParagraphTypeCollection('node', 'landing_page', $field, $paragraphType);
    }
  }
  return $enabled;
}

