<?php

/**
 * @file
 * Contains hooks for 'helfi_node_landing_page' module.
 */

declare(strict_types=1);

use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_node_landing_page_helfi_paragraph_types() : array {
  $types = [
    'field_hero' => [
      'hero' => 0,
    ],
    'field_content' => [
      'list_of_links' => 0,
      'content_cards' => 1,
      'banner' => 2,
      'liftup_with_image' => 3,
      'popular_services' => 4,
      'from_library' => 5,
      'columns' => 6,
      'phasing' => 7,
      'map' => 8,
      'remote_video' => 9,
      'chart' => 10,
      'target_group_links' => 12,
      'event_list' => 13,
      'news_list' => 14,
      'image_gallery' => 15,
    ],
  ];

  $enabled = [];
  foreach ($types as $field => $paragraphTypes) {
    foreach ($paragraphTypes as $paragraphType => $weight) {
      $enabled[] = new ParagraphTypeCollection('node', 'landing_page', $field, $paragraphType, $weight);
    }
  }

  return $enabled;
}
