block.block.reactandshare:
  expected_config:
    visibility: {  }
  update_actions:
    change:
      visibility:
        'entity_bundle:node':
          id: 'entity_bundle:node'
          bundles:
            announcement: announcement
            news_item: news_item
          negate: true
          context_mapping:
            node: '@node.node_route_context:node'
