field.field.node.news_item.field_lead_in:
  expected_config:
    description: 'Lead-in should be less than 320 characters.'
    label: Lead-in
  update_actions:
    change:
      description: 'Lead is visible on the content page, content listings, search results and on social media. Lead should be less than 320 characters.'
      label: Lead
node.type.news_item:
  expected_config:
    description: 'Content type for pages that include information that ages quickly.'
  update_actions:
    change:
      description: 'Content type for news items.'
core.entity_form_display.node.news_item.default:
  expected_config:
    content:
      langcode:
        settings:
          include_locked: true
  update_actions:
    change:
      content:
        langcode:
          settings:
            include_locked: false
