user.role.admin:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'create news_item content'
        - 'create terms in news_tags'
        - 'delete any news_item content'
        - 'delete news_item revisions'
        - 'delete own news_item content'
        - 'delete terms in news_tags'
        - 'edit any news_item content'
        - 'edit own news_item content'
        - 'edit terms in news_tags'
        - 'revert news_item revisions'
        - 'set news_item published on date'
        - 'translate news_item node'
        - 'translate news_tags taxonomy_term'
        - 'view news_item revisions'
user.role.content_producer:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'create news_item content'
        - 'delete own news_item content'
        - 'edit any news_item content'
        - 'edit own news_item content'
        - 'revert news_item revisions'
        - 'set news_item published on date'
        - 'view news_item revisions'
user.role.editor:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'create news_item content'
        - 'delete any news_item content'
        - 'delete news_item revisions'
        - 'delete own news_item content'
        - 'edit any news_item content'
        - 'edit own news_item content'
        - 'revert news_item revisions'
        - 'set news_item published on date'
        - 'translate news_item node'
        - 'translate news_tags taxonomy_term'
        - 'view news_item revisions'
user.role.read_only:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'view any unpublished news_item content'
