core.base_field_override.node.news_item.promote:
  expected_config:
    default_value:
      -1:
        value: 0
  update_actions:
    change:
      default_value:
        -1:
          value: 1
field.field.node.news_item.field_news_item_links_title:
  expected_config:
    default_value: {  }
  update_actions:
    change:
      default_value:
        -1:
          value: 'Learn more'
