<?php

/**
 * @file
 * Contains hooks for hdbt cookie banner test module.
 */

declare(strict_types=1);

/**
 * Implements hook_page_attachments().
 */
function hdbt_cookie_banner_test_page_attachments(array &$attachments) : void {
  // Alter the HDBT cookie banner settings.
  $attachments['#attached']['drupalSettings']['hdbt_cookie_banner']['spacerParentSelector'] = '.test-footer';
  global $base_url;
  $attachments['#attached']['drupalSettings']['hdbt_cookie_banner']['apiUrl'] = $base_url . '/api/cookie-banner';
}
