config_rewrite: 'replace'
content_root: ''
assertiveness: smart
no_load: ''
ignore_all_if_absent: ''
ignore_elements: '.card img, .picture--computed img, .content-card__image img, .card-teaser__img img, .components--computed *'
panel_no_cover: ''
embedded_content_warning: ''
download_links: ''
link_strings_new_windows: ''
ignore_link_strings: ''
link_ignore_selector: 'svg.ext, svg.mailto, .link-purpose-text'
hidden_handlers: ''
element_hides_overflow: ''
ed11y_theme: sleekTheme
panel_pin: right
shadow_components: ''
detect_shadow: false
watch_for_changes: 'true'
disable_sync: false
preserve_params: ''
redundant_prefix: ''
custom_tests: 0
disable_live: false
live_h_inherit: ''
live_h2: 'form[id^="node-"] #edit-body-wrapper .ck-content'
live_h3: ''
live_h4: ''
hide_edit_links: ''
ck5_table_headers: row
ignore_tests:
  linkNewWindow: '0'
  linkNoText: '0'
  altEmptyLinked: '0'
  linkDocument: '0'
  linkTextIsURL: '0'
  linkTextIsGeneric: '0'
  textPossibleList: '0'
  textPossibleHeading: '0'
  textUppercase: '0'
  tableNoHeaderCells: '0'
  tableEmptyHeaderCell: '0'
  tableContainsContentHeading: '0'
  embedVideo: embedVideo
  embedAudio: '0'
  embedVisualization: '0'
  embedTwitter: '0'
  embedCustom: '0'
  headingEmpty: '0'
  headingIsLong: '0'
  headingLevelSkipped: '0'
  blockquoteIsShort: '0'
  altMissing: '0'
  altNull: '0'
  altMeaningless: '0'
  altURL: '0'
  altImageOf: '0'
  altDeadspace: '0'
  altLong: '0'
  altPartOfLinkWithText: '0'
