name: Laskeutumissivu
description: 'Laskeutumissivu sisältötyyppiä suositellaan käytettäväksi silloin kun sivua halutaan käyttää jonkin tietyn osion tai aiheen etusivuna. Laskeutumissivu koostuu pääosin nostoista, listauksista ja linkeistä.'
