label: Sisältönosto
description: 'Sisältönostolla voit nostaa yksittäisen sisällön tämän sivuston sisältä. Sisällön tiedot haetaan automaattisesti viitteen kautta ja sisältö esitetään korttinäkymässä.'
