label: Haitari
description: 'Haitari-elementtiä käytetään toissijaisen tiedon tallentamiseen kompaktissa muodossa. Sivuston käyttäjät näkevät tiedosta otsikon verran ensimmäisellä silmäyksellä ja voivat tarkastella sisältöä tarkemmin klikkaamalla otsikon auki.'
