label: Palstat
description: 'Palstat paragraafilla sisällöntuottaja voi sijoittaa sisältöä kahteen palstaan. Palstajaot voivat olla 50/50 tai 30/70 | 70/30 levyisiä. Paragraafin palstoihin voi vapaasti liittää erilaisia komponentteja.'
