label: Arkisto
description: 'Kaikki sisältö, kuukausittain lajiteltuna.'
display:
  default:
    display_title: Oletus
    display_options:
      title: Arkisto
      exposed_form:
        options:
          submit_button: Käytä
          reset_button_label: Palauta
          exposed_sorts_label: Lajittele
          sort_asc_label: Nousevasti
          sort_desc_label: Laskevasti
      pager:
        options:
          expose:
            items_per_page_label: 'Merkintöjä sivua kohti'
            items_per_page_options_all_label: '- Kaikki -'
            offset_label: Offset
          tags:
            previous: '‹ Edellinen'
            next: 'Seuraava ›'
  block_1:
    display_title: Lohko
  page_1:
    display_title: Sivu
