label: 'Uusin sisältö'
description: 'Uusin sisältö.'
display:
  default:
    display_title: Oletus
    display_options:
      exposed_form:
        options:
          submit_button: Käytä
          reset_button_label: Palauta
          exposed_sorts_label: Lajittele
          sort_asc_label: Nousevasti
          sort_desc_label: Laskevasti
      fields:
        changed:
          separator: ', '
      title: 'Uusin sisältö'
      empty:
        area_text_custom:
          content: 'Ei sisältöä.'
      use_more_text: Lisää
  block_1:
    display_title: Lohko
