label: 'Uudelleenkäytettävät lohkot'
display:
  default:
    display_title: Oletus
    display_options:
      exposed_form:
        options:
          submit_button: Suodatin
          reset_button_label: Palauta
          exposed_sorts_label: Lajittele
          sort_asc_label: Nousevasti
          sort_desc_label: Laskevasti
      pager:
        options:
          tags:
            previous: '‹ Edellinen'
            next: 'Seuraava ›'
          expose:
            items_per_page_label: 'Merkintöjä sivua kohti'
            items_per_page_options_all_label: '- Kaikki -'
            offset_label: Offset
      fields:
        label:
          label: Otsikko
          separator: ', '
        type:
          label: Tyyppi
          separator: ', '
        paragraphs__target_id:
          label: Lohkot
          separator: ', '
        langcode:
          label: Kieli
          separator: ', '
        id:
          label: ID
          separator: ', '
        changed:
          label: Muuttunut
          separator: ', '
        operations:
          label: Toimenpiteet
      filters:
        label:
          expose:
            label: Otsikko
          group_info:
            label: Otsikko
        type:
          expose:
            label: Tyyppi
      title: 'Uudelleenkäytettävät lohkot'
  page_1:
    display_title: Sivu
