core.entity_form_display.paragraph.event_list.default:
  expected_config:
    content:
      field_load_more:
        region: content
        settings:
          display_label: true
        third_party_settings: {  }
        type: boolean_checkbox
        weight: 3
  update_actions:
    delete:
      content:
        field_load_more:
          region: content
          settings:
            display_label: true
          third_party_settings: {  }
          type: boolean_checkbox
          weight: 3
    add:
      content:
        field_event_count:
          region: content
          settings: {  }
          third_party_settings: {  }
          type: options_select
          weight: 4
core.entity_view_display.paragraph.event_list.default:
  expected_config:
    hidden:
      field_load_more: true
  update_actions:
    delete:
      hidden:
        field_load_more: true
    add:
      content:
        field_event_count:
          label: above
          region: content
          settings: {  }
          third_party_settings: {  }
          type: list_default
          weight: 2
