<?php


/**
 * Base configurations for HELfi Languages.
 */
function helfi_languages_update_9001() {
  /** @var \Drupal\update_helper\Updater $updateHelper */
  $updateHelper = \Drupal::service('update_helper.updater');

  // Execute configuration update definitions with logging of success.
  $updateHelper->executeUpdate('helfi_languages', 'helfi_languages_update_9001');

  // Output logged messages to related channel of update execution.
  return $updateHelper->logger()->output();
}
