core.entity_form_display.node.announcement.default:
  expected_config:
    content:
      langcode:
        settings:
          include_locked: true
  update_actions:
    change:
      content:
        langcode:
          settings:
            include_locked: false
