core.entity_form_display.node.announcement.default:
  expected_config:
    content:
      field_announcement_content_pages:
        settings:
          autocomplete: false
          match_limit: 10
  update_actions:
    change:
      content:
        field_announcement_content_pages:
          settings:
            autocomplete: true
            match_limit: 20
