dependencies:
  config:
    - field.field.paragraph.content_liftup.field_content_liftup_unit
content:
  field_content_liftup_unit:
    weight: 2
    label: hidden
    settings:
      view_mode: wide_teaser
      link: false
    third_party_settings: {  }
    type: entity_reference_entity_view
    region: content
