# Schema for the site settings configurations.
# @todo Find out if we can change the hdbt_admin_tools configuration prefix without BC breaks.

hdbt_admin_tools.site_settings:
  type: config_object
  label: 'Site settings'
  mapping:
    site_settings:
      label: 'Site settings'
      type: mapping
      mapping:
        default_icon:
          label: 'Default icon'
          type: label
        theme_color:
          label: 'Theme color'
          type: label
        koro:
          label: 'Koro'
          type: label
    footer_settings:
      label: 'Footer settings'
      type: mapping
      mapping:
        footer_color:
          label: 'Footer color'
          type: label
