name: 'HELfi Base config'
type: module
description: 'Provides base configuration and basic site features to run the Drupal in most efficient way.'
core: 8.x
core_version_requirement: '^8 || ^9'
version: 9.x-1.0
package: HELfi
dependencies:
  - admin_toolbar
  - block
  - features
  - views
  - taxonomy
  - gin_toolbar
  - hdbt_component_library
  - hdbt_custom_blocks
  - helfi_example_content
  - helfi_languages
  - menu_link_content
  - system
  - twig_tweak
