name: 'HELfi Base config'
type: module
description: 'Provides base configuration and basic site features to run the Drupal in most efficient way.'
core: 8.x
core_version_requirement: '^8 || ^9'
version: 9.x-1.0
package: HELfi
dependencies:
  - admin_toolbar
  - block
  - config_translation
  - ctools
  - easy_breadcrumb
  - features
  - gin_toolbar
  - hdbt_admin_editorial
  - hdbt_admin_tools
  - hdbt_component_library
  - hdbt_content
  - hdbt_hyphenopoly
  - helfi_example_content
  - helfi_languages
  - helfi_media
  - menu_block_current_language
  - menu_link_content
  - node
  - pathauto
  - system
  - taxonomy
  - token
  - twig_tweak
  - views
