general_settings:
  radio_behavior: simple
  context_lines_leading: 1
  context_lines_trailing: 1
  revision_pager_limit: 50
  layout_plugins:
    visual_inline:
      enabled: true
      weight: 0
    split_fields:
      weight: 1
      enabled: false
    unified_fields:
      weight: 2
      enabled: false
  visual_inline_theme: admin
