<?php

declare(strict_types = 1);

namespace Drupal\helfi_navigation\Plugin\Block;

use Drupal\helfi_api_base\Environment\Project;
use Drupal\helfi_navigation\ExternalMenuTree;

/**
 * Provides an external menu block.
 *
 * @Block(
 *   id = "external_menu_block",
 *   admin_label = @Translation("External menu block"),
 *   category = @Translation("External menu"),
 *   deriver = "Drupal\helfi_navigation\Plugin\Derivative\ExternalMenuBlock"
 * )
 */
class ExternalMenuBlock extends ExternalMenuBlockBase {

  /**
   * Build external menu render array.
   *
   * @return array|null
   *   Returns the render array.
   */
  public function build():? array {
    $build = [];

    $menu_type = $this->getDerivativeId();
    // @todo Handle menu request elsewhere,
    // Maybe cache the request and build from cached request data.
    /** @var \Drupal\helfi_navigation\ExternalMenuTree $menu_tree */
    $menu_tree = $this->buildFromJson(
      $this->globalNavigationService->makeRequest(
        Project::ETUSIVU,
        'GET',
        "/global-menus/$menu_type"
      )
    );

    if ($menu_tree instanceof ExternalMenuTree) {
      $build['#cache'] = [
        'cache_context' => $this->getCacheContexts(),
        'cache_tags' => $this->getCacheTags()
      ];

      $build['#sorted'] = TRUE;
      $build['#items'] = $menu_tree->getTree();
      $build['#theme'] = 'menu__external_menu';
      $build['#menu_type'] = $menu_type;
    }

    return $build;
  }

  public function getCacheContexts()
  {
    return parent::getCacheContexts(); // TODO: Change the autogenerated stub
  }

  public function getCacheTags()
  {
    return [$this->getCacheKey()];
  }

  protected function getCacheKey(): string {
    $context = 'ExternalMenuBlock';
    $menu_type = $this->getDerivativeId();
    return sprintf('%s:%s', $context, $menu_type);
  }

}
