<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraphs_hearings' module.
 */

declare(strict_types = 1);

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_hearings_helfi_paragraph_types() : array {
  $types = [
    'field_content' => [
      'hearings',
    ],
  ];

  $enabled = [];
  foreach ($types as $field => $paragraphTypes) {
    foreach ($paragraphTypes as $paragraphType) {
      $enabled[] = new ParagraphTypeCollection('node', 'landing_page', $field, $paragraphType);
    }
  }
  return $enabled;
}

/**
 * Implements hook_cron().
 */
function helfi_paragraphs_hearings_cron(): void {
}
