<?php

/**
 * @file
 * Contains helfi_toc module hooks.
 */

declare(strict_types=1);

use Drupal\Core\Entity\ContentEntityInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function helfi_toc_form_tpr_service_form_alter(&$form) : void {
  helfi_toc_apply_form_theme($form);
}

/**
 * Implements hook_theme().
 */
function helfi_toc_theme(): array {
  $module_path = \Drupal::service('extension.list.module')
    ->getPath('helfi_toc');

  return [
    'field__toc_enabled' => [
      'base hook' => 'field',
      'render element' => 'element',
      'template' => 'field--toc-enabled',
      'path' => "$module_path/templates",
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_field_alter().
 */
function helfi_toc_theme_suggestions_field_alter(array &$suggestions, array $variables): void {
  if (($variables['element']['#field_name'] ?? NULL) === 'toc_enabled') {
    $suggestions[] = 'field__toc_enabled';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function helfi_toc_form_tpr_unit_form_alter(&$form) : void {
  helfi_toc_apply_form_theme($form);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function helfi_toc_form_node_form_alter(&$form) : void {
  helfi_toc_apply_form_theme($form);
}

/**
 * Handle Table of contents fields visibility and access.
 *
 * @param array $form
 *   Form.
 */
function helfi_toc_apply_form_theme(array &$form) : void {
  $whitelisted_forms = [
    'node_page_edit_form',
    'node_page_form',
    'tpr_service_form',
    'tpr_unit_form',
    'node_district_edit_form',
    'node_district_form',
  ];

  $form['toc_enabled']['#access'] = FALSE;
  $form['toc_title']['#access'] = FALSE;

  // Control Table of contents title field visibility via checkbox states.
  if (in_array($form['#form_id'], $whitelisted_forms)) {
    $form['toc_enabled']['#access'] = TRUE;
    $form['toc_title']['#access'] = FALSE;
    $form['toc_title']['#states'] = [
      'visible' => [
        ':input[name="toc_enabled[value]"]' => ['checked' => FALSE],
      ],
    ];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function helfi_toc_preprocess_field__toc_enabled(&$variables) : void {
  $entity = $variables['element']['#object'];

  if (!$entity instanceof ContentEntityInterface) {
    return;
  }

  $variables['toc_enabled'] = (bool) $entity->get('toc_enabled')->value;
  $variables['toc_title'] = t('On this page');
  if ($variables['toc_enabled']) {
    $variables['#attached']['library'][] = 'helfi_toc/table_of_contents';
  }
}
