<?php

/**
 * @file
 * Contains helfi_toc module hooks.
 */

declare(strict_types=1);

use Drupal\Core\Entity\ContentEntityInterface;

/**
 * Implements hook_theme().
 */
function helfi_toc_theme(): array {
  $module_path = \Drupal::service('extension.list.module')
    ->getPath('helfi_toc');

  return [
    'field__toc_enabled' => [
      'base hook' => 'field',
      'render element' => 'element',
      'template' => 'field--toc-enabled',
      'path' => "$module_path/templates",
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_field_alter().
 */
function helfi_toc_theme_suggestions_field_alter(array &$suggestions, array $variables): void {
  if (($variables['element']['#field_name'] ?? NULL) === 'toc_enabled') {
    $suggestions[] = 'field__toc_enabled';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function helfi_toc_preprocess_field__toc_enabled(&$variables) : void {
  $entity = $variables['element']['#object'];

  if (!$entity instanceof ContentEntityInterface) {
    return;
  }

  $variables['toc_enabled'] = (bool) $entity->get('toc_enabled')->value;
  $variables['toc_title'] = t('On this page');
  if ($variables['toc_enabled']) {
    $variables['#attached']['library'][] = 'helfi_toc/table_of_contents';
  }
}
