<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraphs_remote_video' module.
 */

declare(strict_types=1);

use Drupal\helfi_paragraphs_remote_video\Entity\ParagraphRemoteVideo;


/**
 * Implements hook_entity_bundle_info_alter().
 */
function helfi_paragraphs_remote_video_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['paragraph']['remote_video'])) {
    $bundles['paragraph']['remote_video']['class'] = ParagraphRemoteVideo::class;
  }
}

/**
 * Implements hook_preprocess_paragraph__type().
 */
function helfi_paragraphs_remote_video_preprocess_paragraph__remote_video(&$variables) {
  /** @var \Drupal\helfi_paragraphs_remote_video\Entity\ParagraphRemoteVideo $paragraph */
  $paragraph = $variables['paragraph'];
  $paragraph->setMediaEntityIframeTitle();
}
