<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraphs_remote_video' module.
 */

declare(strict_types = 1);

use Drupal\helfi_media_remote_video\Entity\RemoteVideo;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function helfi_paragraphs_remote_video_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['media']['remote_video'])) {
    $bundles['media']['remote_video']['class'] = RemoteVideo::class;
  }
}
