name: 'HELfi TPR configuration'
type: module
core_version_requirement: '^9 || ^10'
package: HELfi
dependencies:
  - 'allowed_formats:allowed_formats'
  - 'field_group:field_group'
  - 'hdbt_admin_tools:hdbt_admin_tools'
  - 'helfi_base_content:helfi_base_content'
  - 'helfi_media:helfi_media'
  - 'helfi_image_styles:helfi_image_styles'
  - 'helfi_tpr:helfi_tpr'
  - 'imagecache_external:imagecache_external'
  - 'views:views'
  - 'views_bulk_edit:views_bulk_edit'
  - 'views_bulk_operations:views_bulk_operations'
  - 'content_lock:content_lock'
'interface translation project': helfi_tpr_config
'interface translation server pattern': modules/contrib/helfi_platform_config/modules/helfi_tpr_config/translations/%language.po
