name: 'HELfi TPR configuration'
type: module
core_version_requirement: '^9 || ^10'
package: HELfi
dependencies:
  - 'field_group:field_group'
  - 'hdbt_admin_tools:hdbt_admin_tools'
  - 'helfi_base_content:helfi_base_content'
  - 'helfi_media:helfi_media'
  - 'helfi_paragraphs_content_liftup:helfi_paragraphs_content_liftup'
  - 'helfi_tpr:helfi_tpr'
  - 'imagecache_external:imagecache_external'
  - 'views:views'
  - 'views_bulk_edit:views_bulk_edit'
  - 'views_bulk_operations:views_bulk_operations'
'interface translation project': helfi_tpr_config
'interface translation server pattern': modules/contrib/helfi_platform_config/helfi_features/helfi_tpr_config/translations/%language.po
