<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraphs_map' module.
 */

declare(strict_types=1);

use Drupal\helfi_paragraphs_map\Entity\Map;
use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_paragraphs_map_helfi_paragraph_types() : array {
  return [
    new ParagraphTypeCollection('paragraphs_library_item', 'paragraphs_library_item', 'paragraphs', 'map'),
  ];
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function helfi_paragraphs_map_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['paragraph']['map'])) {
    $bundles['paragraph']['map']['class'] = Map::class;
  }
}
