<?php

/**
 * @file
 * Contains alterations for the Hel.fi navigation.
 */

declare(strict_types = 1);

use Drupal\menu_link_content\MenuLinkContentInterface;
use Drupal\system\MenuInterface;

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function helfi_navigation_menu_update(MenuInterface $entity) {
  if ($entity->id() === 'main') {
    _helfi_navigation_queue_item($entity);
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function helfi_navigation_menu_link_content_update(MenuLinkContentInterface $entity) {
  if ($entity->getMenuName() === 'main') {
    _helfi_navigation_queue_item($entity);
  }
}

/**
 * Create menu update queue item.
 */
function _helfi_navigation_queue_item($entity) {

  // @todo Remove once testing phase is over.
  /*
  $menuUpdater = \Drupal::service('helfi_navigation.menu_updater');
  $menuUpdater->syncMenu();
   */

  // Add item to menu queue.
  // Sanitize the queue manually by adding an item only if the queue is empty.
  $queue = \Drupal::queue('helfi_navigation_menu_queue');
  if ($queue->numberOfItems() < 1) {
    $queue->createItem($entity);
  }
}
