helfi_calculator.settings:
  type: config_object
  label: 'Calculator settings'
  mapping:
    calculators:
      type: sequence
      label: Calculators
      sequence:
        type: mapping
        mapping:
          active:
            label: 'Is active'
            type: boolean
          json:
            label: Json
            type: text
          label:
            label: 'Calculator label'
            type: label
