views.view.content:
  expected_config:
    display:
      default:
        display_options:
          filter_groups:
            groups:
              1: AND
          filters:
            langcode:
              expose:
                reduce: false
              value: {  }
            status:
              group_info:
                group_items:
                  1:
                    operator: '='
                    title: Published
                    value: '1'
                  2:
                    operator: '='
                    title: Unpublished
                    value: '0'
          style:
            options:
              info:
                name:
                  sortable: false
        display_title: Default
  update_actions:
    delete:
      display:
        default:
          display_options:
            filter_groups:
              groups:
                1: AND
            filters:
              status:
                group_info:
                  group_items:
                    1:
                      operator: '='
                      title: Published
                      value: '1'
                    2:
                      operator: '='
                      title: Unpublished
                      value: '0'
    add:
      display:
        default:
          cache_metadata:
            contexts:
              - 'languages:language_content'
              - 'languages:language_interface'
              - url
              - url.query_args
              - user
              - 'user.node_grants:view'
              - user.permissions
          display_options:
            fields:
              langcode:
                admin_label: ''
                alter:
                  absolute: false
                  alt: ''
                  alter_text: false
                  ellipsis: true
                  external: false
                  html: false
                  link_class: ''
                  make_link: false
                  max_length: 0
                  more_link: false
                  more_link_path: ''
                  more_link_text: ''
                  nl2br: false
                  path: ''
                  path_case: none
                  prefix: ''
                  preserve_tags: ''
                  rel: ''
                  replace_spaces: false
                  strip_tags: false
                  suffix: ''
                  target: ''
                  text: ''
                  trim: false
                  trim_whitespace: false
                  word_boundary: true
                click_sort_column: value
                delta_first_last: false
                delta_limit: 0
                delta_offset: 0
                delta_reversed: false
                element_class: ''
                element_default_classes: true
                element_label_class: ''
                element_label_colon: true
                element_label_type: ''
                element_type: ''
                element_wrapper_class: ''
                element_wrapper_type: ''
                empty: ''
                empty_zero: false
                entity_field: langcode
                entity_type: node
                exclude: false
                field: langcode
                field_api_classes: false
                group_column: value
                group_columns: {  }
                group_rows: true
                group_type: group
                hide_alter_empty: true
                hide_empty: false
                id: langcode
                label: Language
                multi_type: separator
                plugin_id: field
                relationship: none
                separator: ', '
                settings:
                  link_to_entity: false
                  native_language: false
                table: node_field_data
                type: language
            filters:
              langcode:
                expose:
                  remember_roles:
                    admin: '0'
                    content_producer: '0'
            style:
              options:
                columns:
                  langcode: langcode
                  operations: operations
                info:
                  langcode:
                    align: ''
                    default_sort_order: asc
                    empty_column: false
                    responsive: ''
                    separator: ''
                    sortable: true
                  operations:
                    align: ''
                    empty_column: false
                    responsive: ''
                    separator: ''
        page_1:
          cache_metadata:
            contexts:
              - 'languages:language_content'
              - 'languages:language_interface'
              - url
              - url.query_args
              - user
              - 'user.node_grants:view'
              - user.permissions
    change:
      display:
        default:
          display_options:
            filter_groups:
              groups:
                - AND
                - AND
            filters:
              langcode:
                expose:
                  reduce: true
                value:
                  en: en
                  fi: fi
                  sv: sv
              status:
                group_info:
                  group_items:
                    -
                      operator: '='
                      title: Published
                      value: '1'
                    -
                      operator: '='
                      title: Unpublished
                      value: '0'
                    -
                      operator: '='
                      title: Published
                      value: '1'
                    -
                      operator: '='
                      title: Unpublished
                      value: '0'
            style:
              options:
                info:
                  name:
                    sortable: true
          display_title: Master
simple_sitemap.custom_links.default:
  expected_config: {  }
  update_actions:
    add:
      links:
        -
          changefreq: daily
          path: /
          priority: '1.0'
simple_sitemap.settings:
  expected_config: {  }
  update_actions:
    add:
      enabled_entity_types:
        - node
        - taxonomy_term
        - menu_link_content
pathauto.settings:
  expected_config: {  }
  update_actions:
    add:
      enabled_entity_types:
        - user
      safe_tokens:
        - alias
        - path
        - join-path
        - login-url
        - url
        - url-brief
