block.block.language_switcher_admin:
  expected_config:
    visibility:
      request_path:
        pages: "/node/*\r\n/admin/content/integrations/tpr-unit/*/edit\r\n/admin/content/integrations/tpr-service/*/edit"
  update_actions:
    change:
      visibility:
        request_path:
          pages: "/node/*\r\n/admin/content/integrations/tpr-unit/*/edit\r\n/admin/content/integrations/tpr-service/*/edit\r\n/group/*/content/create/*"
