name: 'HELfi Media map configuration'
type: module
core_version_requirement: '^8.9 || ^9'
package: HELfi
dependencies:
  - 'drupal:field'
  - 'drupal:media'
  - 'drupal:media_library'
  - 'drupal:text'
  - 'paragraphs:paragraphs'
  - 'helfi_content:helfi_content'
  - 'helfi_media_map:helfi_media_map'
