display:
  default:
    display_options:
      filters:
        combine:
          group_info:
            description: ''
            label: 'Kentät yhdistävä suodatin'
          expose:
            label: Etsi
      empty:
        area:
          content:
            value: "<p>Ei tuloksia</p>\r\n"
      pager:
        options:
          tags:
            previous: '‹ Edellinen'
            next: 'Seuraava ›'
          expose:
            items_per_page_label: 'Merkintöjä sivua kohti'
            items_per_page_options_all_label: '- Kaikki -'
            offset_label: Offset
          views_infinite_scroll:
            button_text: 'Lataa lisää'
      arguments:
        id:
          exception:
            title: Kaikki
    display_title: Oletus
  block:
    display_title: Lohko
  entity_reference:
    display_title: Entiteettiviittaus
label: Toimipistehaku
