display:
  default:
    display_options:
      filters:
        combine:
          group_info:
            description: ''
            label: 'Kentät yhdistävä suodatin'
          expose:
            label: Etsi
      empty:
        area:
          content:
            value: "<p>Ei tuloksia</p>\r\n"
      exposed_form:
        options:
          submit_button: Käytä
          reset_button_label: Palauta
          exposed_sorts_label: Järjestä
          sort_asc_label: Nouseva
          sort_desc_label: Laskeva
      pager:
        options:
          tags:
            next: Seuraava
            previous: Edellinen
            first: Ensimmäinen
            last: Viimeinen
          expose:
            items_per_page_label: 'Merkintöjä sivua kohti'
            items_per_page_options_all_label: '- Kaikki -'
            offset_label: Offset
      arguments:
        id:
          exception:
            title: Kaikki
    display_title: Oletus
  block:
    display_title: Lohko
  entity_reference:
    display_title: Entiteettiviittaus
label: Toimipistehaku
