display:
  default:
    display_title: Oletus
    display_options:
      exposed_form:
        options:
          submit_button: Etsi
          reset_button_label: Palauta
          exposed_sorts_label: Lajittele
          sort_asc_label: Nousevasti
          sort_desc_label: Laskevasti
      pager:
        options:
          tags:
            previous: '‹ Edellinen'
            next: 'Seuraava ›'
          expose:
            items_per_page_label: 'Merkintöjä sivua kohti'
            items_per_page_options_all_label: '- Kaikki -'
          views_infinite_scroll:
            button_text: 'Lataa lisää palveluita'
      arguments:
        id:
          exception:
            title: Kaikki
      empty:
        area:
          content:
            value: "<p>Ei tuloksia</p>\r\n"
            format: full_html
  block_1:
    display_options:
      exposed_form:
        options:
          submit_button: Etsi
      pager:
        options:
          tags:
            previous: 'Edellinen'
            next: 'Seuraava'
      filters:
        combine:
          expose:
            label: 'Neuvontapalvelun nimi tai hakusana'
            placeholder: 'Esim. Sosiaalineuvonta, terveys tai digi'
