<?php

/**
 * @file
 * Calculators.
 */

declare(strict_types=1);

use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements template_preprocess_paragraph().
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 *   - paragraph: The paragraph object.
 *   - view_mode: View mode; e.g., 'full', 'teaser'...
 */
function helfi_calculator_preprocess_paragraph__calculator(array &$variables) {
  // Get calculator data without applying module overrides for the calculators.
  $config = \Drupal::configFactory()->getEditable('helfi_calculator.settings');
  $calculator_settings = $config->getOriginal('calculators', FALSE);
  $active = [];
  foreach ($calculator_settings as $key => $value) {
    $variables['#attached']['drupalSettings'][$key] = $value['json'];
    if ($value['active']) {
      $active[] = $key;
    }
  }

  $selected_calculator = $variables['paragraph']->get('field_calculator')->value;
  $variables['is_active'] = in_array($selected_calculator, $active);
}

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_calculator_helfi_paragraph_types() : array {
  $types = [
    'field_content' => [
      'calculator' => 19,
    ],
    'field_lower_content' => [
      'calculator' => 20,
    ],
  ];

  $enabled = [];
  foreach ($types as $field => $paragraphTypes) {
    foreach ($paragraphTypes as $paragraphType => $weight) {
      $enabled[] = new ParagraphTypeCollection('node', 'page', $field, $paragraphType, $weight);
    }
  }
  return $enabled;
}

/**
 * Implements hook_config_ignore_settings_alter().
 */
function helfi_calculator_config_ignore_settings_alter(array &$settings) {
  if (!in_array('helfi_calculator.settings', $settings)) {
    array_push($settings, 'helfi_calculator.settings');
  }
}
