<?php

/**
 * @file
 * Calculators.
 */

use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements template_preprocess_paragraph().
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 *   - paragraph: The paragraph object.
 *   - view_mode: View mode; e.g., 'full', 'teaser'...
 */
function helfi_calculator_preprocess_paragraph__calculator(array &$variables) {
  $config = Drupal::config('helfi_calculator.settings');
  $calculator_settings = $config->get('calculators');
  $active = [];
  foreach ($calculator_settings as $key => $value) {
    $variables['#attached']['drupalSettings'][$key] = $value['json'];
    if ($value['active']) {
      $active[] = $key;
    }
  }

  $selected_calculator = $variables['paragraph']->get('field_calculator')->value;
  $variables['is_active'] = in_array($selected_calculator, $active);
}

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_calculator_helfi_paragraph_types() : array {
  $types = [
    'field_content' => [
      'calculator',
    ],
    'field_lower_content' => [
      'calculator',
    ],
  ];

  $enabled = [];
  foreach ($types as $field => $paragraphTypes) {
    foreach ($paragraphTypes as $paragraphType) {
      $enabled[] = new ParagraphTypeCollection('node', 'page', $field, $paragraphType);
    }
  }
  return $enabled;
}

/**
 * Implements hook_config_ignore_settings_alter().
 */
function helfi_calculator_config_ignore_settings_alter(array &$settings) {
  $add_ignore = [
    'helfi_calculator.settings'
  ];

  foreach($add_ignore as $config) {
    if (in_array($config, $settings)) { continue; }
    array_push($settings, $config);
  }
}
