# Schema for the configuration files of the HELfi Hotjar.

helfi_hotjar.settings:
  type: config_object
  label: 'HELfi Hotjar settings'
  mapping:
    hjid:
      type: string
      label: 'Hotjar ID'
    hjsv:
      type: string
      label: 'Hotjar snippet version'
