name: 'HELfi Base config'
type: module
description: 'Provides base configuration and basic site features to run the Drupal in most efficient way.'
core_version_requirement: '^8.9 || ^9'
package: HELfi
dependencies:
  - 'admin_toolbar:admin_toolbar'
  - 'admin_toolbar_tools:admin_toolbar_tools'
  - 'config_rewrite:config_rewrite'
  - 'config_ignore:config_ignore'
  - 'ctools:ctools'
  - 'diff:diff'
  - 'drupal:block'
  - 'drupal:config_translation'
  - 'drupal:field_ui'
  - 'drupal:menu_link_attributes'
  - 'drupal:menu_link_content'
  - 'drupal:node'
  - 'drupal:system'
  - 'drupal:taxonomy'
  - 'drupal:user'
  - 'drupal:views'
  - 'drupal:views_ui'
  - 'easy_breadcrumb:easy_breadcrumb'
  - 'field_group:field_group'
  - 'hdbt_admin_editorial:hdbt_admin_editorial'
  - 'hdbt_admin_tools:hdbt_admin_tools'
  - 'hdbt_component_library:hdbt_component_library'
  - 'hdbt_content:hdbt_content'
  - 'helfi_content:helfi_content'
  - 'helfi_gdpr_compliance:helfi_gdpr_compliance'
  - 'helfi_languages:helfi_languages'
  - 'helfi_media:helfi_media'
  - 'linkit:linkit'
  - 'menu_block_current_language:menu_block_current_language'
  - 'pathauto:pathauto'
  - 'select2_icon:select2_icon'
  - 'simple_sitemap:simple_sitemap'

  - 'token:token'
  - 'twig_tweak:twig_tweak'
  - 'update_helper:update_helper'
'interface translation project': helfi_base_config
'interface translation server pattern': modules/contrib/helfi_platform_config/helfi_features/helfi_base_config/translations/%language.po
