<?php

/**
 * @file
 * Primary module hooks for helfi_media_map module.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function helfi_media_map_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if ($entity_type->id() === 'media' && $bundle === 'hel_map') {
    if (isset($fields['field_media_hel_map'])) {
      $fields['field_media_hel_map']->addConstraint('ValidMediaMapLink', []);
    }
  }
}

/**
 * Implements hook_theme().
 */
function helfi_media_map_theme($existing, $type, $theme, $path) {
  return [
    'helfi_media_map' => [
      'variables' => ['link' => NULL, 'iframe' => NULL],
      'template' => 'helfi-media-map'
    ],
  ];
}
