helfi_eu_cookie_compliance.cookie_consent_intro:
  type: config_object
  label: 'Cookie consent intro'
  mapping:
    cc:
      label: 'Cookie consent'
      type: mapping
      mapping:
        title:
          label: 'Cookie consent intro title'
          type: label
        content:
          label: 'Cookie consent intro content'
          type: text_format
