<?php

/**
 * @file
 * Contains hooks for 'helfi_node_survey' module.
 */

declare(strict_types=1);

/**
 * Implements hook_form_FORM_ID_alter().
 */
function helfi_node_survey_form_node_form_alter(&$form, &$form_state, $form_id) : void {
  switch ($form_id) {
    case 'node_survey_edit_form':
    case 'node_survey_form':
      $form['field_survey_content_pages']['#states'] = [
        'visible' => [
          ':input[name="field_survey_all_pages[value]"]' => ['checked' => FALSE],
        ],
      ];
      break;
  }
}
