core.entity_form_display.paragraph.contact_card.default:
  expected_config:
    content:
      field_contact_description:
        weight: 5
      field_contact_name:
        weight: 1
      field_contact_social_media:
        weight: 6
      field_contact_title:
        weight: 4
      field_email:
        weight: 2
      field_phone_number:
        weight: 3
  update_actions:
    add:
      content:
        field_contact_image_photographer:
          region: content
          settings:
            placeholder: ''
            size: 60
          third_party_settings: {  }
          type: string_textfield
          weight: 1
      dependencies:
        config:
          - field.field.paragraph.contact_card.field_contact_image_photographer
    change:
      content:
        field_contact_description:
          weight: 6
        field_contact_name:
          weight: 2
        field_contact_social_media:
          weight: 7
        field_contact_title:
          weight: 3
        field_email:
          weight: 4
        field_phone_number:
          weight: 5
core.entity_form_display.paragraph.contact_card_listing.default:
  expected_config:
    content:
      field_contact_card:
        weight: 3
      field_description:
        type: string_textarea
  update_actions:
    change:
      content:
        field_contact_card:
          weight: 2
        field_description:
          type: text_textarea
core.entity_view_display.paragraph.contact_card.default:
  expected_config:
    content:
      field_phone_number:
        settings:
          link_to_entity: false
        type: string
  update_actions:
    delete:
      content:
        field_phone_number:
          settings:
            link_to_entity: false
    add:
      content:
        field_contact_image_photographer:
          label: hidden
          region: content
          settings:
            link_to_entity: false
          third_party_settings: {  }
          type: string
          weight: 7
    change:
      content:
        field_phone_number:
          settings:
            title: ''
          type: telephone_link
core.entity_view_display.paragraph.contact_card_listing.default:
  expected_config:
    content:
      field_description:
        type: basic_string
        weight: 3
  update_actions:
    change:
      content:
        field_description:
          type: text_default
          weight: 1
field.field.paragraph.contact_card.field_contact_image:
  expected_config:
    description: ''
  update_actions:
    change:
      description: 'Use a square image for the best result. Portrait and landscape images will be cropped to a square, horizontally centred and vertically aligned to the top.'
field.field.paragraph.contact_card_listing.field_description:
  expected_config:
    field_type: string_long
  update_actions:
    add:
      third_party_settings:
        allowed_formats:
          allowed_formats:
            - minimal
    change:
      field_type: text_long
field.storage.paragraph.field_description:
  expected_config:
    module: core
    settings:
      case_sensitive: false
    type: string_long
  update_actions:
    delete:
      settings:
        case_sensitive: false
    change:
      module: text
      settings: {  }
      type: text_long
field.storage.paragraph.field_phone_number:
  expected_config:
    cardinality: 1
  update_actions:
    change:
      cardinality: 4
