<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraphs_text' module.
 */

declare(strict_types = 1);

use Drupal\helfi_platform_config\DTO\EnableParagraphTypes;

/**
 * Implements hook_enable_paragraph_fields().
 */
function helfi_paragraphs_text_enable_paragraph_fields() : array {
  return [
    // @todo Figure out all content types and paragraphs fields.
    new EnableParagraphTypes('node', 'page', ['field_content', 'field_lower_content'], 'text'),
  ];
}

