language.entity.en:
  expected_config:
    weight: 0
  update_actions:
    change:
      weight: -8
language.negotiation:
  expected_config:
    selected_langcode: site_default
    url:
      prefixes:
        en: ''
  update_actions:
    add:
      url:
        domains:
          fi: ''
          sv: ''
    change:
      selected_langcode: fi
      url:
        prefixes:
          en: en
          fi: fi
          sv: sv
language.types:
  expected_config:
    negotiation:
      language_interface:
        enabled:
          language-url: 0
  update_actions:
    add:
      configurable:
        - language_content
      negotiation:
        language_content:
          enabled:
            language-selected: -14
            language-url: -20
          method_weights:
            language-browser: -16
            language-content-entity: -19
            language-interface: -15
            language-selected: -14
            language-session: -18
            language-url: -20
            language-user: -17
    change:
      negotiation:
        language_interface:
          enabled:
            language-selected: 12
            language-url: -8
            language-user-admin: -10
          method_weights:
            language-browser: -2
            language-selected: 12
            language-session: -6
            language-url: -8
            language-user: -4
            language-user-admin: -10
locale.settings:
  expected_config:
    translation:
      path: ''
  update_actions:
    change:
      translation:
        path: sites/default/files/translations
