<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraphs_list_of_links' module.
 */

declare(strict_types = 1);

use Drupal\helfi_paragraphs_list_of_links\Entity\ListOfLinksItem;
use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_paragraphs_list_of_links_helfi_paragraph_types() : array {
  return [
    new ParagraphTypeCollection('paragraph', 'list_of_links', 'field_list_of_links_links', 'list_of_links_item'),
    new ParagraphTypeCollection('paragraphs_library_item', 'paragraphs_library_item', 'paragraphs', 'list_of_links'),
  ];
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function helfi_paragraphs_list_of_links_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['paragraph']['list_of_links_item'])) {
    $bundles['paragraph']['list_of_links_item']['class'] = ListOfLinksItem::class;
  }
}
