<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraphs_popular_services' module.
 */

declare(strict_types = 1);

use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_paragraphs_popular_services_helfi_paragraph_types() : array {
  return [
    new ParagraphTypeCollection('paragraph', 'popular_services', 'field_service_items', 'popular_service_item'),
  ];
}
