<?php

/**
 * @file
 * Contains hooks for 'helfi_paragraphs_popular_services' module.
 */

declare(strict_types=1);

use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_paragraphs_popular_services_helfi_paragraph_types() : array {
  return [
    new ParagraphTypeCollection('paragraph', 'popular_services', 'field_service_items', 'popular_service_item'),
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function helfi_paragraphs_popular_services_preprocess_field(array $variables): void {
  if ($variables['field_name'] !== 'field_service_links') {
    return;
  }

  // Add class to popular service links.
  foreach ($variables['items'] as $item) {
    $existing = $item['content']['#url']->getOption('attributes');
    $attributes = array_merge($existing ?? [], [
      'class' => [
        'link__style--highlight',
      ],
    ]);
    $item['content']['#url']->setOption('attributes', $attributes);
  }
}
