<?php

/**
 * @file
 * Contains hooks for 'helfi_node_news_item' module.
 */

declare(strict_types=1);

use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_node_news_item_helfi_paragraph_types() : array {
  $types = [
    'field_content' => [
      'text' => 0,
      'image' => 1,
      'remote_video' => 2,
      'banner' => 3,
    ],
  ];

  $enabled = [];
  foreach ($types as $field => $paragraphTypes) {
    foreach ($paragraphTypes as $paragraphType => $weight) {
      $enabled[] = new ParagraphTypeCollection('node', 'news_item', $field, $paragraphType, $weight);
    }
  }
  return $enabled;
}
