<?php

/**
 * @file
 * Contains hooks for 'helfi_node_news_item' module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\entity\BundleFieldDefinition;
use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;
use Drupal\node\NodeInterface;

/**
 * Implements hook_platform_config_grant_permissions().
 */
function helfi_node_news_item_platform_config_grant_permissions() : array {
  return [
    'admin' => [
      'create news_item content',
      'create terms in news_group',
      'create terms in news_neighbourhoods',
      'create terms in news_tags',
      'delete any news_item content',
      'delete news_item revisions',
      'delete own news_item content',
      'delete terms in news_group',
      'delete terms in news_neighbourhoods',
      'delete terms in news_tags',
      'edit any news_item content',
      'edit own news_item content',
      'edit terms in news_group',
      'edit terms in news_neighbourhoods',
      'edit terms in news_tags',
      'revert news_item revisions',
      'set news_item published on date',
      'translate news_group taxonomy_term',
      'translate news_item node',
      'translate news_neighbourhoods taxonomy_term',
      'translate news_tags taxonomy_term',
      'view news_item revisions',
    ],
    'content_producer' => [
      'create news_item content',
      'delete own news_item content',
      'edit any news_item content',
      'edit own news_item content',
      'revert news_item revisions',
      'set news_item published on date',
      'view news_item revisions',
    ],
    'editor' => [
      'create news_item content',
      'delete any news_item content',
      'delete news_item revisions',
      'delete own news_item content',
      'edit any news_item content',
      'edit own news_item content',
      'revert news_item revisions',
      'set news_item published on date',
      'translate news_group taxonomy_term',
      'translate news_item node',
      'translate news_neighbourhoods taxonomy_term',
      'translate news_tags taxonomy_term',
      'view news_item revisions',
    ],
    'read_only' => [
      'view any unpublished news_item content',
    ],
  ];
}

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_node_news_item_helfi_paragraph_types() : array {
  $types = [
    'field_content' => [
      'text' => 0,
      'image' => 1,
      'remote_video' => 2,
      'banner' => 3,
    ],
  ];

  $enabled = [];
  foreach ($types as $field => $paragraphTypes) {
    foreach ($paragraphTypes as $paragraphType => $weight) {
      $enabled[] = new ParagraphTypeCollection('node', 'news_item', $field, $paragraphType, $weight);
    }
  }
  return $enabled;
}

/**
 * Get the changed_at bundle field definition.
 */
function _helfi_node_news_item_changed_at_field(): BundleFieldDefinition {
  return BundleFieldDefinition::create('timestamp')
    ->setName('changed_at')
    ->setLabel(t('Content changed on'))
    ->setDescription(t('Timestamp of when content was last changed via form.'))
    ->setTargetEntityTypeId('node')
    ->setTargetBundle('news_item')
    ->setRevisionable(TRUE)
    ->setTranslatable(TRUE)
    ->setDisplayConfigurable('view', TRUE)
    ->setDisplayConfigurable('form', FALSE);
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 *
 * Adds a 'changed_at' field to news_item nodes.
 */
function helfi_node_news_item_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle): void {
  if ($entity_type->id() === 'node' && $bundle === 'news_item') {
    $fields['changed_at'] = _helfi_node_news_item_changed_at_field();
  }
}

/**
 * Implements hook_entity_field_storage_info().
 */
function helfi_node_news_item_entity_field_storage_info(EntityTypeInterface $entity_type): array {
  if ($entity_type->id() === 'node') {
    return ['changed_at' => _helfi_node_news_item_changed_at_field()];
  }
  return [];
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form.
 *
 * Adds submit handler to update changed_at field on form saves.
 */
function helfi_node_news_item_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id): void {
  if (!str_contains($form_id, 'news_item')) {
    return;
  }

  array_unshift($form['actions']['submit']['#submit'], '_helfi_node_news_item_update_changed_at');
}

/**
 * Submit handler to update changed_at field for news_item nodes.
 */
function _helfi_node_news_item_update_changed_at($form, FormStateInterface $form_state): void {
  $node = $form_state->getFormObject()->getEntity();

  if ($node instanceof NodeInterface && $node->bundle() === 'news_item') {
    $node->set('changed_at', \Drupal::time()->getRequestTime());
  }
}
