<?php

/**
 * @file
 * Contains installation tasks for helfi_node_news_item module.
 */

declare(strict_types=1);

/**
 * UHF-10555: Removed references to media display that is no longer used.
 */
function helfi_node_news_item_update_9005(): void {
  // This is automated now.
}

/**
 * UHF-11232: Use HelfiLinkitWidget for link fields.
 */
function helfi_node_news_item_update_9006(): void {
  \Drupal::service('helfi_platform_config.config_update_helper')
    ->update('helfi_node_news_item');
}
