user.role.admin:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'use siteimprove'
        - 'administer siteimprove'
        - 'use siteimprove prepublish'
user.role.content_producer:
  expected_config: {  }
  update_actions:
    add:
      permissions:
        - 'use siteimprove'
        - 'use siteimprove prepublish'
