name: 'HELfi Siteimprove configuration'
type: module
core_version_requirement: '^8.9 || ^9'
package: HELfi
dependencies:
  - 'update_helper:update_helper'
'interface translation project': helfi_siteimprovement_config
'interface translation server pattern': modules/contrib/helfi_platform_config/helfi_features/helfi_siteimprovement_config/translations/%language.po
