<?php

/**
 * @file
 * Contains module hooks for 'helfi_platform_config_update_test' module.
 */

declare(strict_types=1);

use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;

/**
 * Implements hook_platform_config_grant_permissions().
 */
function helfi_platform_config_update_test_platform_config_grant_permissions() : array {
  return [
    'authenticated' => [
      'access content',
    ],
  ];
}

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_platform_config_update_test_helfi_paragraph_types(): array {
  return [
    new ParagraphTypeCollection('node', 'page', 'field_paragraphs', 'text', 1),
    new ParagraphTypeCollection('node', 'page', 'field_paragraphs', 'image', 2),
    new ParagraphTypeCollection('paragraphs_library_item', 'paragraphs_library_item', 'paragraphs', 'test_paragraph'),
  ];
}
