field.field.node.landing_page.field_content:
  expected_config: {}
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            unit_contact_card: unit_contact_card
          target_bundles_drag_drop:
            unit_contact_card:
              enabled: true
              weight: 35
field.field.node.page.field_lower_content:
  expected_config: {}
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            unit_contact_card: unit_contact_card
          target_bundles_drag_drop:
            unit_contact_card:
              enabled: true
              weight: 35
field.field.tpr_unit.tpr_unit.field_lower_content:
  expected_config: {}
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            unit_contact_card: unit_contact_card
          target_bundles_drag_drop:
            unit_contact_card:
              enabled: true
              weight: 35
field.field.tpr_service.tpr_service.field_lower_content:
  expected_config: {}
  update_actions:
    add:
      settings:
        handler_settings:
          target_bundles:
            unit_contact_card: unit_contact_card
          target_bundles_drag_drop:
            unit_contact_card:
              enabled: true
              weight: 35
