name: 'HELfi Matomo configuration'
type: module
core_version_requirement: '^8.9 || ^9'
package: HELfi
dependencies:
  - 'update_helper:update_helper'
  - 'matomo:matomo'
  - 'matomo_reports:matomo_reports'
