helfi_ai.settings:
  type: config_object
  label: 'HELfi AI settings'
  mapping:
    enable_seo_title:
      type: boolean
      label: 'Enable AI SEO title'
    enable_tone_check:
      type: boolean
      label: 'Enable AI tone check'
    enable_ai_summary:
      type: boolean
      label: 'Enable AI summary'
    seo_title_bundles:
      type: sequence
      label: 'Content types offering AI SEO title suggestions'
      sequence:
        type: string
        label: 'Content type machine name'
