<?php

use Drupal\helfi_paragraphs_event_list\LinkedEvents;

/**
 * Implements hook_preprocess_paragraph().
 */
function helfi_paragraphs_event_list_preprocess_paragraph__event_list(&$variables) {
  // Expose event list variables to frontend
  if(isset($variables['paragraph'])) {
    $paragraph = $variables['paragraph'];
    $linkedEvents = Drupal::service('helfi_paragraphs_event_list_linked_events');

    if (!$paragraph->get('field_api_url')->isEmpty()) {
      $intialUrl = $paragraph->get('field_api_url')->first()->getUrl()->toString();
      $params = $linkedEvents->parseParams($intialUrl);
      $variables['#attached']['drupalSettings']['helfi_paragraphs_event_list']['eventsUrl'] = $linkedEvents->getEventsRequest($params);

      // Render link for refiging serach in events service for use in frontend
      $variables['#attached']['drupalSettings']['helfi_paragraphs_event_list']['refineSearchButton'] = twig_render_template(
        drupal_get_path('theme', 'hdbt') . '/templates/navigation/link-button.html.twig',
        [
          'type' => 'secondary',
          'label' => t('Refine search in tapahtumat.hel.fi'),
          'class' => 'event-list__refine-button',
          'url' => $intialUrl,
          'theme_hook_original' => ''
        ]
      );
    }

    if ($loadMore = $paragraph->get('field_load_more')->value) {
      $variables['#attached']['drupalSettings']['helfi_paragraphs_event_list']['loadMore'] = $loadMore;
    }
  }

  // Render link to events service for use in frontend
  $variables['#attached']['drupalSettings']['helfi_paragraphs_event_list']['seeAllButton'] = twig_render_template(
    drupal_get_path('theme', 'hdbt') . '/templates/navigation/link-button.html.twig',
    [
      'type' => 'primary',
      'label' => t('See all events'),
      'class' => 'event-list__see-all-button',
      'url' => LinkedEvents::BASE_URL,
      'theme_hook_original' => ''
    ]
  );

  //Render image placeholder for use in frontend
  $variables['#attached']['drupalSettings']['helfi_paragraphs_event_list']['imagePlaceholder'] = twig_render_template(
    drupal_get_path('theme', 'hdbt') . '/templates/misc/image-placeholder.twig',
    [
      'image_placeholder' => 'calendar-clock',
      'theme_hook_original' => ''
    ]
  );

  $variables['#attached']['library'][] = 'helfi_paragraphs_event_list/events_list';
  $variables['#attached']['drupalSettings']['helfi_paragraphs_event_list']['baseUrl'] = LinkedEvents::BASE_URL;
  $variables['#attached']['drupalSettings']['helfi_paragraphs_event_list']['translations'] = _helfi_paragraphs_event_list_translations();
}

/**
 * Returns string translations for frontend
 *
 * @return array
 *   the translated strings
 */
function _helfi_paragraphs_event_list_translations() : array {
  return [
    'at' => t('at', [], ['context' => 'Indication that events take place in a certain timeframe']),
    'emptyList' => t('This event list is empty.'),
    'emptyListSubText' => t('No worries though, this city does not run out of things to do.'),
    'eventKeywords' => t('Event keywords'),
    'eventsCount' => t('events'),
    'externalLink' => t(
      'Link leads to external service',
      [],
      ['context' => 'Explanation for screen-reader software that the icon visible next to this link means that the link leads to an external service.']
    ),
    'loadMore' => t('Load more events'),
  ];
}
