hdbt_cookie_banner.settings:
  type: config_object
  label: HDBT cookie banner
  mapping:
    site_settings:
      type: string
      translatable: false
      label: Site settings
      nullable: true
    use_custom_settings:
      type: boolean
      translatable: false
      label: Use custom settings
      nullable: true
    use_internal_hds_cookie_js:
      type: boolean
      translatable: false
      label: Use local JS file
      nullable: true
    hds_cookie_js_override:
      type: string
      translatable: false
      label: Override HDS cookie JS
      nullable: true
    theme:
      type: string
      translatable: false
      label: Theme
      nullable: true
    settings_page_selector:
      type: string
      translatable: false
      label: Settings page selector
      nullable: true
    cookie_information:
      label: Cookie information
      type: mapping
      mapping:
        title:
          label: Cookie information title
          translatable: true
          type: label
        content:
          label: Cookie information content
          translatable: true
          type: text
