<?php

/**
 * @file
 * Contains HELfi test content alterations.
 */

declare(strict_types = 1);

/**
 * Implements hook_modules_installed().
 */
function helfi_test_content_modules_installed(array $modules) : void {
  // Install instance specific test content if the helfi_test_content has
  // been installed.
  if (in_array('helfi_test_content', $modules)) {
    /** @var \Drupal\Core\Extension\ModuleExtensionList $moduleExtensionList */
    $moduleExtensionList = Drupal::service('extension.list.module');
    $allModules = $moduleExtensionList->getList();
    if (array_key_exists('helfi_custom_test_content', $allModules)) {
      /** @var \Drupal\Core\Extension\ModuleInstallerInterface $moduleInstaller */
      $moduleInstaller = Drupal::service('module_installer');
      $moduleInstaller->install(['helfi_custom_test_content']);

      // Re-import instance specific custom test content as the default_content
      // sorter function will not sort the dependencies correctly if the
      // dependable content is located in another module.
      $testContentImporter = Drupal::service('helfi_test_content.helper.import');
      $testContentImporter->importContent([
        'helfi_test_content',
        'helfi_custom_test_content',
      ]);
    }
  }
}
