<?php

/**
 * @file
 * Contains HELfi test content alterations.
 */

declare(strict_types=1);

use Drupal\Core\Config\ImmutableConfig;

/**
 * Implements hook_modules_installed().
 */
function helfi_test_content_modules_installed(array $modules) : void {
  if (in_array('helfi_test_content', $modules)) {
    // Install instance specific test content if the helfi_test_content has
    // been installed.
    /** @var \Drupal\Core\Extension\ModuleExtensionList $moduleExtensionList */
    $moduleExtensionList = Drupal::service('extension.list.module');
    $allModules = $moduleExtensionList->getList();

    if (array_key_exists('helfi_custom_test_content', $allModules)) {
      /** @var \Drupal\Core\Extension\ModuleInstallerInterface $moduleInstaller */
      $moduleInstaller = Drupal::service('module_installer');
      $moduleInstaller->install(['helfi_custom_test_content']);
    }

    // Set the announcement remote entities setting to false.
    $announcement_config = \Drupal::config('block.block.announcements');
    assert($announcement_config instanceof ImmutableConfig);;
    $announcement_settings = $announcement_config->get('settings');
    $announcement_settings['use_remote_entities'] = FALSE;
    $announcement_config->set('settings', $announcement_settings)->save();
  }
}
