<?php

/**
 * @file
 * Contains alterations for the Hel.fi media module.
 */

declare(strict_types=1);

use Drupal\config_rewrite\ConfigRewriterInterface;

/**
 * Implements hook_platform_config_grant_permissions().
 */
function helfi_media_platform_config_grant_permissions() : array {
  return [
    'admin' => [
      // @file.
      'access files overview',
      // @media.
      'access media overview',
      'create file media',
      'create image media',
      'create media',
      'delete any file media',
      'delete any image media',
      'delete any media',
      'delete media',
      'delete own file media',
      'delete own image media',
      'edit any file media',
      'edit any image media',
      'edit own file media',
      'edit own image media',
      'translate file media',
      'translate image media',
      'update any media',
      'update media',
      'view media',
      'view all media revisions',
      'view own unpublished media',
    ],
    'anonymous' => [
      'view media',
    ],
    'authenticated' => [
      'view media',
    ],
    'content_producer' => [
      // @file.
      'access files overview',
      // @media.
      'access media overview',
      'create file media',
      'create image media',
      'create media',
      'delete media',
      'delete own file media',
      'delete own image media',
      'edit any file media',
      'edit any image media',
      'edit own file media',
      'edit own image media',
      'translate file media',
      'translate image media',
      'update media',
      'view all media revisions',
      'view own unpublished media',
    ],
    'editor' => [
      // @file.
      'access files overview',
      // @media.
      'access media overview',
      'create file media',
      'create image media',
      'create media',
      'delete any file media',
      'delete any image media',
      'delete any media',
      'delete media',
      'delete own file media',
      'delete own image media',
      'edit any file media',
      'edit any image media',
      'edit own file media',
      'edit own image media',
      'translate file media',
      'translate image media',
      'update any media',
      'update media',
      'view all media revisions',
      'view own unpublished media',
    ],
  ];
}

/**
 * Implements hook_rewrite_config_update().
 */
function helfi_media_config_rewrite_config_update(string $module, ConfigRewriterInterface $configRewriter): void {
  // Rewrite module configuration.
  if ($module === 'helfi_media') {
    $configRewriter->rewriteModuleConfig('helfi_media');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function helfi_media_preprocess_image(&$variables): void {
  // Convert double "double quotes" to empty string for image alt-texts.
  if (isset($variables['alt']) && $variables['alt'] === '""') {
    $variables['attributes']['alt'] = '';
  }
}
