label: Redirect
description: Uudelleenohjaukset
display:
  default:
    display_title: Oletus
    display_options:
      fields:
        redirect_bulk_form:
          action_title: Valinnalla
        redirect_source__path:
          label: Lähettäjä
        created:
          label: Luotu
      filters:
        redirect_source__path:
          expose:
            label: Lähettäjä
        redirect_redirect__uri:
          expose:
            label: Osoitteeseen
        status_code:
          expose:
            label: Tilakoodi
          group_info:
            label: Tilakoodi
            group_items:
              -
                title: '300 Useita valintoja'
              -
                title: '301 Pysyvästi siirretty'
              -
                title: '302 Löydetty'
              -
                title: '303 Kts. toinen'
              -
                title: '304 Muuttamaton'
              -
                title: '305 Käytä proxyä'
              -
                title: '307 Tilapäinen uudelleenohjaus'
        language:
          expose:
            label: 'Alkuperäinen kieli'
      empty:
        area_text_custom:
          content: 'Ei ole vielä uudelleenohjaksia.'
  page_1:
    display_title: Sivu
