label: 'Ajastettu sisältö'
description: 'Etsi ja ylläpidä ajastettua sisältöä.'
display:
  default:
    display_options:
      fields:
        node_bulk_form:
          action_title: Toiminto
        title:
          label: Otsikko
        type:
          label: Sisältötyyppi
        name:
          label: Kirjoittaja
        status:
          label: Tila
          settings:
            format_custom_true: Julkaistu
            format_custom_false: Julkaisematon
        publish_on:
          label: Julkaisuaika
        unpublish_on:
          label: 'Ajastettu piilottaminen'
        operations:
          label: Toimenpiteet
      filters:
        title:
          expose:
            label: Otsikko
        type:
          expose:
            label: Sisältötyyppi
        status:
          expose:
            label: Tila
          group_info:
            label: Julkaisutila
            group_items:
              1:
                title: Julkaistu
              2:
                title: Julkaisematon
        langcode:
          expose:
            label: Kieli
      title: 'Ajastettu sisältö'
      empty:
        area_text_custom:
          content: 'Ei vielä ajastettua sisältöä.'
    display_title: Oletus
  overview:
    display_options:
      menu:
        title: Ajastettu
      tab_options:
        title: Sisältö
      display_description: 'Yleiskatsaus koko ajoitetusta sisällöstä.'
    display_title: Sisältö
  user_page:
    display_options:
      menu:
        title: Ajastettu
      tab_options:
        title: Sisältö
      arguments:
        uid:
          exception:
            title: Kaikki
      empty:
        area_text_custom:
          content: '{{ arguments.uid }} käyttäjä ei ole ajastanut sisältöä.'
    display_title: Käyttäjäprofiili
