dependencies:
  config:
    - paragraphs.paragraphs_type.map
settings:
  handler_settings:
    negate: '0'
    target_bundles:
      map: map
    target_bundles_drag_drop:
      map:
        enabled: true
        weight: 31
