on:
  release:
    types: [published]
name: Cleanup
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 20
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
