label: Filer
description: 'Hitta och hantera filer.'
display:
  default:
    display_title: Förvald
    display_options:
      fields:
        fid:
          label: Fid
        filename:
          label: Namn
        filemime:
          label: 'Typ av MIME'
        filesize:
          label: Storlek
        status:
          label: Status
          settings:
            format_custom_false: Temporär
            format_custom_true: Permanent
        created:
          label: 'Datum för uppladdning'
        changed:
          label: 'Datum för ändring'
        count:
          label: 'Används i'
      filters:
        filename:
          expose:
            label: Filnamn
        filemime:
          expose:
            label: 'Typ av MIME'
        status:
          expose:
            label: Status
      title: Filer
      empty:
        area_text_custom:
          content: 'Inga filer tillgängliga.'
  page_1:
    display_title: 'Översikt av filer'
    display_options:
      menu:
        title: Filer
  page_2:
    display_title: Filanvändning
    display_options:
      fields:
        entity_label:
          label: Objekt
        type:
          label: Objektstyp
        module:
          label: 'Registrerar modul'
        count:
          label: 'Antal använd'
      title: Filanvändning
      arguments:
        fid:
          exception:
            title: Alla
          title: 'Information om filanvändande för {{ arguments.fid }}'
