display:
  default:
    display_options:
      fields:
        node_bulk_form:
          action_title: Åtgärd
        title:
          label: Titel
        type:
          label: Innehållstyp
        name:
          label: Författare
        status:
          label: Status
          settings:
            format_custom_true: Publicerad
            format_custom_false: 'Ej publicerad'
        publish_on:
          label: 'Publicera den'
        unpublish_on:
          label: 'Avpublicera den'
        operations:
          label: Funktioner
      filters:
        title:
          expose:
            label: Titel
        type:
          expose:
            label: Innehållstyp
        status:
          expose:
            label: Status
          group_info:
            label: 'Status för publicering'
            group_items:
              1:
                title: Publicerad
              2:
                title: 'Ej publicerad'
        langcode:
          expose:
            label: Språk
    display_title: Förvald
  overview:
    display_options:
      menu:
        title: Schemalagd
      tab_options:
        title: Innehåll
  user_page:
    display_options:
      menu:
        title: Schemalagd
      tab_options:
        title: Innehåll
      arguments:
        uid:
          exception:
            title: Alla
