permissions:
  - 'create news_item content'
  - 'delete own news_item content'
  - 'edit any news_item content'
  - 'edit own news_item content'
  - 'revert news_item revisions'
  - 'set news_item published on date'
  - 'view news_item revisions'
