<?php

/**
 * @file
 * Contains helfi_paragraphs_curated_event_list module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\entity\BundleFieldDefinition;
use Drupal\helfi_paragraphs_curated_event_list\Entity\LinkedEventsEvent;
use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;
use Drupal\paragraphs\ParagraphInterface;

/**
 * Implements hook hook_ENTITY_TYPE_view().
 */
function helfi_paragraphs_curated_event_list_paragraph_view(
  array &$build,
  ParagraphInterface $entity,
  EntityViewDisplayInterface $display,
  string $view_mode,
): void {
  if ($entity->bundle() !== 'curated_event_list') {
    return;
  }

  $selections = $entity->get('field_events')->referencedEntities();

  if (
    !$display->getComponent('field_events') ||
    empty($selections)
  ) {
    return;
  }

  $storage = Drupal::entityTypeManager()
    ->getStorage('linkedevents_event');

  $ids = array_map(function (LinkedEventsEvent $event) {
    return $event->id();
  }, $selections);

  /** @var \Drupal\helfi_paragraphs_curated_event_list\Entity\LinkedEventsEvent[] */
  $entities = $storage->loadMultiple($ids);

  foreach ($entities as $item) {
    $item->addCacheableDependency($entity);

    $build[$item->getEventType()][] = Drupal::entityTypeManager()
      ->getViewBuilder('linkedevents_event')
      ->view($item);
  }

  if (
    isset($build['future_or_ongoing']) &&
    count($build['future_or_ongoing']) > 3
  ) {
    $build['future_or_ongoing'] = array_slice($build['future_or_ongoing'], 0, 3);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function helfi_paragraphs_curated_event_list_preprocess_external_entity__linkedevents_event(
  array &$variables,
): void {
  /** @var \Drupal\helfi_paragraphs_curated_event_list\Entity\LinkedEventsEvent $event */
  $event = $variables['external_entity'];

  $start = $event->get('start_time')->getValue() ? $event->start_time->date->getTimeStamp() : NULL;
  $end = $event->get('end_time')->getValue() ? $event->end_time->date->getTimeStamp() : NULL;

  $variables['start_timestamp'] = $start;
  $variables['end_timestamp'] = $end;
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function helfi_paragraphs_curated_event_list_entity_bundle_field_info_alter(
  &$fields,
  EntityTypeInterface $entity_type,
  $bundle,
): void {
  if ($entity_type->id() === 'linkedevents_event') {
    $fields['main_image'] = BundleFieldDefinition::create('link')
      ->setName('main_image')
      ->setLabel('Main image')
      ->setTargetEntityTypeId($entity_type->id())
      ->setTargetBundle($bundle)
      ->setSettings([
        'max_length' => 1024,
      ])
      ->setDisplayConfigurable('view', TRUE);
    $fields['start_time'] = BundleFieldDefinition::create('datetime')
      ->setName('start_time')
      ->setLabel('Event start time')
      ->setDefaultValue('')
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'datetime_default',
      ])
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayConfigurable('form', TRUE);
    $fields['end_time'] = BundleFieldDefinition::create('datetime')
      ->setName('end_time')
      ->setLabel('Event end time')
      ->setDefaultValue('')
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'datetime_default',
      ])
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayConfigurable('form', TRUE);
    $fields['external_link'] = BundleFieldDefinition::create('link')
      ->setName('external_link')
      ->setLabel('External link')
      ->setDefaultValue('')
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'link_default',
      ])
      ->setTranslatable(TRUE)
      ->setDisplayConfigurable('view', TRUE);
  }

  if (
    $entity_type->id() === 'paragraph' &&
    $bundle === 'curated_event_list' &&
    array_key_exists('field_events', $fields)
  ) {
    $fields['field_events']->addConstraint('CuratedEvent', []);
  }
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function helfi_paragraphs_curated_event_list_entity_bundle_info_alter(array &$bundles) : void {
  if (isset($bundles['linkedevents_event']['linkedevents_event'])) {
    $bundles['linkedevents_event']['linkedevents_event']['class'] = LinkedEventsEvent::class;
  }
}

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_paragraphs_curated_event_list_helfi_paragraph_types() : array {
  $types = [
    'field_content' => [
      'curated_event_list' => 15,
    ],
  ];

  $enabled = [];
  foreach ($types as $field => $paragraphTypes) {
    foreach ($paragraphTypes as $paragraphType => $weight) {
      $enabled[] = new ParagraphTypeCollection('node', 'landing_page', $field, $paragraphType, $weight);
    }
  }
  return $enabled;
}
