<?php

/**
 * @file
 * Contains helfi_paragraphs_curated_event_list module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Htmx\Htmx;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Url;
use Drupal\entity\BundleFieldDefinition;
use Drupal\helfi_paragraphs_curated_event_list\Entity\LinkedEventsEvent;
use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;
use Drupal\paragraphs\ParagraphInterface;

/**
 * Implements hook hook_ENTITY_TYPE_view().
 */
function helfi_paragraphs_curated_event_list_paragraph_view(
  array &$build,
  ParagraphInterface $entity,
  EntityViewDisplayInterface $display,
  string $view_mode,
): void {
  if ($entity->bundle() !== 'curated_event_list' || !$display->getComponent('field_events')) {
    return;
  }
  $htmx = new Htmx();
  $htmx->get(new Url('helfi_paragraphs_curated_event_list.htmx', ['paragraph' => $entity->id()]))
    ->trigger('load');

  $build['events_list'] = [
    '#theme' => 'helfi_htmx_preview',
    '#num_items' => 3,
    '#message' => new TranslatableMarkup('Loading ...'),
    '#wrapper'=> 'ul',
    '#attributes' => ['class'=> ['curated-event-list__events']],
  ];
  $htmx->applyTo($build['events_list']);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function helfi_paragraphs_curated_event_list_preprocess_external_entity__linkedevents_event(
  array &$variables,
): void {
  /** @var \Drupal\helfi_paragraphs_curated_event_list\Entity\LinkedEventsEvent $event */
  $event = $variables['external_entity'];
  $start = NULL;
  try {
    $start = $event->get('start_time')->getValue() ?
      $event->get('start_time')->first()->get('date')->getValue()->getTimestamp() :
      NULL;
  }
  catch (\Exception) {
  }

  $end = NULL;
  try {
    $end = $event->get('end_time')->getValue() ?
      $event->get('end_time')->first()->get('date')->getValue()->getTimestamp() :
      NULL;
  }
  catch (\Exception) {
  }

  $variables['start_timestamp'] = $start;
  $variables['end_timestamp'] = $end;
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function helfi_paragraphs_curated_event_list_entity_bundle_field_info_alter(
  &$fields,
  EntityTypeInterface $entity_type,
  $bundle,
): void {
  if ($entity_type->id() === 'linkedevents_event') {
    $fields['main_image'] = BundleFieldDefinition::create('link')
      ->setName('main_image')
      ->setLabel('Main image')
      ->setTargetEntityTypeId($entity_type->id())
      ->setTargetBundle($bundle)
      ->setSettings([
        'max_length' => 1024,
      ])
      ->setDisplayConfigurable('view', TRUE);
    $fields['start_time'] = BundleFieldDefinition::create('datetime')
      ->setName('start_time')
      ->setLabel('Event start time')
      ->setDefaultValue('')
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'datetime_default',
      ])
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayConfigurable('form', TRUE);
    $fields['end_time'] = BundleFieldDefinition::create('datetime')
      ->setName('end_time')
      ->setLabel('Event end time')
      ->setDefaultValue('')
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'datetime_default',
      ])
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayConfigurable('form', TRUE);
    $fields['external_link'] = BundleFieldDefinition::create('link')
      ->setName('external_link')
      ->setLabel('External link')
      ->setDefaultValue('')
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'type' => 'link_default',
      ])
      ->setTranslatable(TRUE)
      ->setDisplayConfigurable('view', TRUE);
  }

  if (
    $entity_type->id() === 'paragraph' &&
    $bundle === 'curated_event_list' &&
    array_key_exists('field_events', $fields)
  ) {
    $fields['field_events']->addConstraint('CuratedEvent', []);
  }
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function helfi_paragraphs_curated_event_list_entity_bundle_info_alter(array &$bundles) : void {
  if (isset($bundles['linkedevents_event']['linkedevents_event'])) {
    $bundles['linkedevents_event']['linkedevents_event']['class'] = LinkedEventsEvent::class;
  }
}

/**
 * Implements hook_helfi_paragraph_types().
 */
function helfi_paragraphs_curated_event_list_helfi_paragraph_types() : array {
  $types = [
    'field_content' => [
      'curated_event_list' => 15,
    ],
  ];

  $enabled = [];
  foreach ($types as $field => $paragraphTypes) {
    foreach ($paragraphTypes as $paragraphType => $weight) {
      $enabled[] = new ParagraphTypeCollection('node', 'landing_page', $field, $paragraphType, $weight);
    }
  }
  return $enabled;
}
